
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-02T09:55:35+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff9789cc21210203f1b1fe455937515f5493aec1",
 "version": "1.8.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
