
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T04:44:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5afabb5e4d569c5bdadda25bc342667b47b5742a",
 "version": "1.18.4.post0.dev71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
