
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-25T19:03:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e70a6ea23bfdcbac0efcb938dbfaee358be5421",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
