
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-31T14:03:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "70705bbc7c94b9af46136a73a41f6ded545401b1",
 "version": "v1.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
