from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    AcmeChallengeSetIn: t.typedef = ...
    AcmeChallengeSetOut: t.typedef = ...
    RotateChallengesRequestIn: t.typedef = ...
    RotateChallengesRequestOut: t.typedef = ...
    AcmeTxtRecordIn: t.typedef = ...
    AcmeTxtRecordOut: t.typedef = ...

class FuncList:
    acmeChallengeSetsRotateChallenges: t.func = ...
    acmeChallengeSetsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_acmedns() -> Import: ...
