from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    UrlChannelsIn: t.typedef = ...
    UrlChannelsOut: t.typedef = ...
    ReportIn: t.typedef = ...
    ReportOut: t.typedef = ...
    CustomChannelIn: t.typedef = ...
    CustomChannelOut: t.typedef = ...
    AdStyleIn: t.typedef = ...
    AdStyleOut: t.typedef = ...
    AdClientIn: t.typedef = ...
    AdClientOut: t.typedef = ...
    CustomChannelsIn: t.typedef = ...
    CustomChannelsOut: t.typedef = ...
    AssociationSessionIn: t.typedef = ...
    AssociationSessionOut: t.typedef = ...
    AccountIn: t.typedef = ...
    AccountOut: t.typedef = ...
    UrlChannelIn: t.typedef = ...
    UrlChannelOut: t.typedef = ...
    AdCodeIn: t.typedef = ...
    AdCodeOut: t.typedef = ...
    AdUnitIn: t.typedef = ...
    AdUnitOut: t.typedef = ...
    AdUnitsIn: t.typedef = ...
    AdUnitsOut: t.typedef = ...
    AdClientsIn: t.typedef = ...
    AdClientsOut: t.typedef = ...
    AccountsIn: t.typedef = ...
    AccountsOut: t.typedef = ...

class FuncList:
    reportsGenerate: t.func = ...
    urlchannelsDelete: t.func = ...
    urlchannelsInsert: t.func = ...
    urlchannelsList: t.func = ...
    customchannelsUpdate: t.func = ...
    customchannelsPatch: t.func = ...
    customchannelsGet: t.func = ...
    customchannelsDelete: t.func = ...
    customchannelsInsert: t.func = ...
    customchannelsList: t.func = ...
    accountsGet: t.func = ...
    accountsList: t.func = ...
    accountsReportsGenerate: t.func = ...
    accountsAdclientsGet: t.func = ...
    accountsAdclientsList: t.func = ...
    accountsAdunitsList: t.func = ...
    accountsAdunitsGet: t.func = ...
    accountsAdunitsGetAdCode: t.func = ...
    accountsAdunitsDelete: t.func = ...
    accountsAdunitsInsert: t.func = ...
    accountsAdunitsPatch: t.func = ...
    accountsAdunitsUpdate: t.func = ...
    associationsessionsVerify: t.func = ...
    associationsessionsStart: t.func = ...
    adclientsGet: t.func = ...
    adclientsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_adsensehost() -> Import: ...
