from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SearchAllAssignmentsResponseIn: t.typedef = ...
    SearchAllAssignmentsResponseOut: t.typedef = ...
    SplitCapacityCommitmentRequestIn: t.typedef = ...
    SplitCapacityCommitmentRequestOut: t.typedef = ...
    SplitCapacityCommitmentResponseIn: t.typedef = ...
    SplitCapacityCommitmentResponseOut: t.typedef = ...
    ListReservationsResponseIn: t.typedef = ...
    ListReservationsResponseOut: t.typedef = ...
    ReservationIn: t.typedef = ...
    ReservationOut: t.typedef = ...
    CapacityCommitmentIn: t.typedef = ...
    CapacityCommitmentOut: t.typedef = ...
    TableReferenceIn: t.typedef = ...
    TableReferenceOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ListCapacityCommitmentsResponseIn: t.typedef = ...
    ListCapacityCommitmentsResponseOut: t.typedef = ...
    BiReservationIn: t.typedef = ...
    BiReservationOut: t.typedef = ...
    AutoscaleIn: t.typedef = ...
    AutoscaleOut: t.typedef = ...
    AssignmentIn: t.typedef = ...
    AssignmentOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    ListAssignmentsResponseIn: t.typedef = ...
    ListAssignmentsResponseOut: t.typedef = ...
    SearchAssignmentsResponseIn: t.typedef = ...
    SearchAssignmentsResponseOut: t.typedef = ...
    MergeCapacityCommitmentsRequestIn: t.typedef = ...
    MergeCapacityCommitmentsRequestOut: t.typedef = ...
    MoveAssignmentRequestIn: t.typedef = ...
    MoveAssignmentRequestOut: t.typedef = ...

class FuncList:
    projectsLocationsSearchAssignments: t.func = ...
    projectsLocationsSearchAllAssignments: t.func = ...
    projectsLocationsUpdateBiReservation: t.func = ...
    projectsLocationsGetBiReservation: t.func = ...
    projectsLocationsCapacityCommitmentsList: t.func = ...
    projectsLocationsCapacityCommitmentsMerge: t.func = ...
    projectsLocationsCapacityCommitmentsPatch: t.func = ...
    projectsLocationsCapacityCommitmentsDelete: t.func = ...
    projectsLocationsCapacityCommitmentsSplit: t.func = ...
    projectsLocationsCapacityCommitmentsCreate: t.func = ...
    projectsLocationsCapacityCommitmentsGet: t.func = ...
    projectsLocationsReservationsList: t.func = ...
    projectsLocationsReservationsPatch: t.func = ...
    projectsLocationsReservationsCreate: t.func = ...
    projectsLocationsReservationsDelete: t.func = ...
    projectsLocationsReservationsGet: t.func = ...
    projectsLocationsReservationsAssignmentsMove: t.func = ...
    projectsLocationsReservationsAssignmentsList: t.func = ...
    projectsLocationsReservationsAssignmentsPatch: t.func = ...
    projectsLocationsReservationsAssignmentsDelete: t.func = ...
    projectsLocationsReservationsAssignmentsCreate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_bigqueryreservation() -> Import: ...
