from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleChromeManagementV1BootPerformanceReportIn: t.typedef = ...
    GoogleChromeManagementV1BootPerformanceReportOut: t.typedef = ...
    GoogleChromeManagementV1UsbPeripheralReportIn: t.typedef = ...
    GoogleChromeManagementV1UsbPeripheralReportOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryHttpsLatencyChangeEventIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryHttpsLatencyChangeEventOut: t.typedef = ...
    GoogleChromeManagementV1DisplayDeviceIn: t.typedef = ...
    GoogleChromeManagementV1DisplayDeviceOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryUsbPeripheralsEventIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryUsbPeripheralsEventOut: t.typedef = ...
    GoogleChromeManagementV1TouchScreenInfoIn: t.typedef = ...
    GoogleChromeManagementV1TouchScreenInfoOut: t.typedef = ...
    GoogleChromeManagementV1HttpsLatencyRoutineDataIn: t.typedef = ...
    GoogleChromeManagementV1HttpsLatencyRoutineDataOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleChromeManagementV1NetworkInfoIn: t.typedef = ...
    GoogleChromeManagementV1NetworkInfoOut: t.typedef = ...
    GoogleChromeManagementV1GraphicsStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1GraphicsStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1StorageStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1StorageStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1BatterySampleReportIn: t.typedef = ...
    GoogleChromeManagementV1BatterySampleReportOut: t.typedef = ...
    GoogleChromeManagementV1ChromeAppSiteAccessIn: t.typedef = ...
    GoogleChromeManagementV1ChromeAppSiteAccessOut: t.typedef = ...
    GoogleChromeManagementV1CountChromeHardwareFleetDevicesResponseIn: t.typedef = ...
    GoogleChromeManagementV1CountChromeHardwareFleetDevicesResponseOut: t.typedef = ...
    GoogleChromeManagementV1ChromeAppRequestIn: t.typedef = ...
    GoogleChromeManagementV1ChromeAppRequestOut: t.typedef = ...
    GoogleChromeManagementV1DiskInfoIn: t.typedef = ...
    GoogleChromeManagementV1DiskInfoOut: t.typedef = ...
    GoogleChromeManagementV1CountChromeAppRequestsResponseIn: t.typedef = ...
    GoogleChromeManagementV1CountChromeAppRequestsResponseOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryUserIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryUserOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryAudioSevereUnderrunEventIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryAudioSevereUnderrunEventOut: t.typedef = ...
    GoogleChromeManagementV1StorageInfoDiskVolumeIn: t.typedef = ...
    GoogleChromeManagementV1StorageInfoDiskVolumeOut: t.typedef = ...
    GoogleChromeManagementV1CpuTemperatureInfoIn: t.typedef = ...
    GoogleChromeManagementV1CpuTemperatureInfoOut: t.typedef = ...
    GoogleChromeManagementV1MemoryInfoIn: t.typedef = ...
    GoogleChromeManagementV1MemoryInfoOut: t.typedef = ...
    GoogleChromeManagementV1StorageInfoIn: t.typedef = ...
    GoogleChromeManagementV1StorageInfoOut: t.typedef = ...
    GoogleChromeManagementV1ChromeAppPermissionIn: t.typedef = ...
    GoogleChromeManagementV1ChromeAppPermissionOut: t.typedef = ...
    GoogleChromeManagementV1BatteryInfoIn: t.typedef = ...
    GoogleChromeManagementV1BatteryInfoOut: t.typedef = ...
    GoogleChromeManagementV1AudioStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1AudioStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1AppDetailsIn: t.typedef = ...
    GoogleChromeManagementV1AppDetailsOut: t.typedef = ...
    GoogleChromeManagementV1ChromeAppInfoIn: t.typedef = ...
    GoogleChromeManagementV1ChromeAppInfoOut: t.typedef = ...
    GoogleChromeManagementV1DeviceIn: t.typedef = ...
    GoogleChromeManagementV1DeviceOut: t.typedef = ...
    GoogleChromeManagementV1CpuInfoIn: t.typedef = ...
    GoogleChromeManagementV1CpuInfoOut: t.typedef = ...
    GoogleChromeManagementV1NetworkStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1NetworkStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1PeripheralsReportIn: t.typedef = ...
    GoogleChromeManagementV1PeripheralsReportOut: t.typedef = ...
    GoogleChromeManagementV1GraphicsAdapterInfoIn: t.typedef = ...
    GoogleChromeManagementV1GraphicsAdapterInfoOut: t.typedef = ...
    GoogleChromeManagementV1OsUpdateStatusIn: t.typedef = ...
    GoogleChromeManagementV1OsUpdateStatusOut: t.typedef = ...
    GoogleChromeManagementV1AndroidAppPermissionIn: t.typedef = ...
    GoogleChromeManagementV1AndroidAppPermissionOut: t.typedef = ...
    GoogleChromeManagementV1MemoryStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1MemoryStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1ListTelemetryDevicesResponseIn: t.typedef = ...
    GoogleChromeManagementV1ListTelemetryDevicesResponseOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryUserInfoIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryUserInfoOut: t.typedef = ...
    GoogleChromeManagementV1DeviceAueCountReportIn: t.typedef = ...
    GoogleChromeManagementV1DeviceAueCountReportOut: t.typedef = ...
    GoogleChromeManagementV1FindInstalledAppDevicesResponseIn: t.typedef = ...
    GoogleChromeManagementV1FindInstalledAppDevicesResponseOut: t.typedef = ...
    GoogleChromeManagementV1NetworkDeviceIn: t.typedef = ...
    GoogleChromeManagementV1NetworkDeviceOut: t.typedef = ...
    GoogleChromeManagementV1TouchScreenDeviceIn: t.typedef = ...
    GoogleChromeManagementV1TouchScreenDeviceOut: t.typedef = ...
    GoogleChromeManagementV1CountChromeDevicesThatNeedAttentionResponseIn: t.typedef = (
        ...
    )
    GoogleChromeManagementV1CountChromeDevicesThatNeedAttentionResponseOut: t.typedef = (
        ...
    )
    GoogleChromeManagementV1TelemetryDeviceIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryDeviceOut: t.typedef = ...
    GoogleChromeManagementV1CountChromeBrowsersNeedingAttentionResponseIn: t.typedef = (
        ...
    )
    GoogleChromeManagementV1CountChromeBrowsersNeedingAttentionResponseOut: t.typedef = (
        ...
    )
    GoogleChromeManagementV1TelemetryEventIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryEventOut: t.typedef = ...
    GoogleChromeManagementV1BatteryStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1BatteryStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1InstalledAppIn: t.typedef = ...
    GoogleChromeManagementV1InstalledAppOut: t.typedef = ...
    GoogleChromeManagementV1GraphicsInfoIn: t.typedef = ...
    GoogleChromeManagementV1GraphicsInfoOut: t.typedef = ...
    GoogleChromeManagementV1CountInstalledAppsResponseIn: t.typedef = ...
    GoogleChromeManagementV1CountInstalledAppsResponseOut: t.typedef = ...
    GoogleChromeManagementV1NetworkDiagnosticsReportIn: t.typedef = ...
    GoogleChromeManagementV1NetworkDiagnosticsReportOut: t.typedef = ...
    GoogleChromeManagementV1ThunderboltInfoIn: t.typedef = ...
    GoogleChromeManagementV1ThunderboltInfoOut: t.typedef = ...
    GoogleChromeManagementV1CpuStatusReportIn: t.typedef = ...
    GoogleChromeManagementV1CpuStatusReportOut: t.typedef = ...
    GoogleChromeManagementV1BrowserVersionIn: t.typedef = ...
    GoogleChromeManagementV1BrowserVersionOut: t.typedef = ...
    GoogleChromeManagementV1TotalMemoryEncryptionInfoIn: t.typedef = ...
    GoogleChromeManagementV1TotalMemoryEncryptionInfoOut: t.typedef = ...
    GoogleChromeManagementV1ListTelemetryUsersResponseIn: t.typedef = ...
    GoogleChromeManagementV1ListTelemetryUsersResponseOut: t.typedef = ...
    GoogleChromeManagementV1DisplayInfoIn: t.typedef = ...
    GoogleChromeManagementV1DisplayInfoOut: t.typedef = ...
    GoogleChromeManagementV1CountChromeVersionsResponseIn: t.typedef = ...
    GoogleChromeManagementV1CountChromeVersionsResponseOut: t.typedef = ...
    GoogleTypeDateIn: t.typedef = ...
    GoogleTypeDateOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryDeviceInfoIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryDeviceInfoOut: t.typedef = ...
    GoogleChromeManagementV1TelemetryUserDeviceIn: t.typedef = ...
    GoogleChromeManagementV1TelemetryUserDeviceOut: t.typedef = ...
    GoogleChromeManagementV1ListTelemetryEventsResponseIn: t.typedef = ...
    GoogleChromeManagementV1ListTelemetryEventsResponseOut: t.typedef = ...
    GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponseIn: t.typedef = (
        ...
    )
    GoogleChromeManagementV1CountChromeDevicesReachingAutoExpirationDateResponseOut: t.typedef = (
        ...
    )
    GoogleChromeManagementV1AndroidAppInfoIn: t.typedef = ...
    GoogleChromeManagementV1AndroidAppInfoOut: t.typedef = ...
    GoogleChromeManagementV1DeviceHardwareCountReportIn: t.typedef = ...
    GoogleChromeManagementV1DeviceHardwareCountReportOut: t.typedef = ...

class FuncList:
    customersReportsCountChromeDevicesThatNeedAttention: t.func = ...
    customersReportsCountChromeHardwareFleetDevices: t.func = ...
    customersReportsFindInstalledAppDevices: t.func = ...
    customersReportsCountInstalledApps: t.func = ...
    customersReportsCountChromeBrowsersNeedingAttention: t.func = ...
    customersReportsCountChromeDevicesReachingAutoExpirationDate: t.func = ...
    customersReportsCountChromeVersions: t.func = ...
    customersTelemetryUsersList: t.func = ...
    customersTelemetryUsersGet: t.func = ...
    customersTelemetryEventsList: t.func = ...
    customersTelemetryDevicesGet: t.func = ...
    customersTelemetryDevicesList: t.func = ...
    customersAppsCountChromeAppRequests: t.func = ...
    customersAppsAndroidGet: t.func = ...
    customersAppsChromeGet: t.func = ...
    customersAppsWebGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_chromemanagement() -> Import: ...
