from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    ListServicesResponseIn: t.typedef = ...
    ListServicesResponseOut: t.typedef = ...
    ProjectBillingInfoIn: t.typedef = ...
    ProjectBillingInfoOut: t.typedef = ...
    SkuIn: t.typedef = ...
    SkuOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    AggregationInfoIn: t.typedef = ...
    AggregationInfoOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    GeoTaxonomyIn: t.typedef = ...
    GeoTaxonomyOut: t.typedef = ...
    PricingExpressionIn: t.typedef = ...
    PricingExpressionOut: t.typedef = ...
    MoneyIn: t.typedef = ...
    MoneyOut: t.typedef = ...
    ListBillingAccountsResponseIn: t.typedef = ...
    ListBillingAccountsResponseOut: t.typedef = ...
    PricingInfoIn: t.typedef = ...
    PricingInfoOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    ServiceIn: t.typedef = ...
    ServiceOut: t.typedef = ...
    ListSkusResponseIn: t.typedef = ...
    ListSkusResponseOut: t.typedef = ...
    BillingAccountIn: t.typedef = ...
    BillingAccountOut: t.typedef = ...
    ListProjectBillingInfoResponseIn: t.typedef = ...
    ListProjectBillingInfoResponseOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    CategoryIn: t.typedef = ...
    CategoryOut: t.typedef = ...
    TierRateIn: t.typedef = ...
    TierRateOut: t.typedef = ...

class FuncList:
    billingAccountsList: t.func = ...
    billingAccountsGetIamPolicy: t.func = ...
    billingAccountsSetIamPolicy: t.func = ...
    billingAccountsTestIamPermissions: t.func = ...
    billingAccountsPatch: t.func = ...
    billingAccountsCreate: t.func = ...
    billingAccountsGet: t.func = ...
    billingAccountsProjectsList: t.func = ...
    projectsGetBillingInfo: t.func = ...
    projectsUpdateBillingInfo: t.func = ...
    servicesList: t.func = ...
    servicesSkusList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_cloudbilling() -> Import: ...
