from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudContactcenterinsightsV1EntityIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1EntityOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1BulkAnalyzeConversationsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1BulkAnalyzeConversationsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1BulkAnalyzeConversationsMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1BulkAnalyzeConversationsMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentWordInfoIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentWordInfoOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsMetadataIngestConversationsStatsIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsMetadataIngestConversationsStatsOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1DeployIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeployIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueAssignmentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueAssignmentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1DialogflowIntentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DialogflowIntentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1HoldDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1HoldDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CalculateIssueModelStatsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1CalculateIssueModelStatsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1PhraseMatchDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1PhraseMatchDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListIssuesResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListIssuesResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueAssignmentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueAssignmentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1CreateIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1CreateIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UploadConversationMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UploadConversationMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestTranscriptObjectConfigIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestTranscriptObjectConfigOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1DialogflowInteractionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DialogflowInteractionDataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1AnnotatorSelectorIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnnotatorSelectorOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatchDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatchDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationLevelSentimentIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationLevelSentimentOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptTranscriptSegmentWordInfoIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptTranscriptSegmentWordInfoOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1EntityMentionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1EntityMentionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelInputDataConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelInputDataConfigOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1CreateIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CreateIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1UndeployIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1UndeployIssueModelRequestOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1AnalysisResultCallAnalysisMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1AnalysisResultCallAnalysisMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationDataSourceIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationDataSourceOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1SmartReplyDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1SmartReplyDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DialogflowInteractionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DialogflowInteractionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelLabelStatsIssueStatsIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IssueModelLabelStatsIssueStatsOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ListIssueModelsResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListIssueModelsResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DialogflowSourceIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DialogflowSourceOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1CallAnnotationIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1CallAnnotationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatchRuleIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatchRuleOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListPhraseMatchersResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListPhraseMatchersResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SettingsAnalysisConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SettingsAnalysisConfigOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1UploadConversationRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1UploadConversationRequestOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1AnalysisResultIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnalysisResultOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationCallMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationCallMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1UploadConversationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1UploadConversationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1UploadConversationRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UploadConversationRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UndeployIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UndeployIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataRequestOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1GcsSourceIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1GcsSourceOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptTranscriptSegmentIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptTranscriptSegmentOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1SentimentDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SentimentDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationParticipantIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationParticipantOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeployIssueModelResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeployIssueModelResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnswerFeedbackIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnswerFeedbackOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataResponseIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataResponseOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1UndeployIssueModelResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UndeployIssueModelResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CallAnnotationIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CallAnnotationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ViewIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ViewOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1BulkAnalyzeConversationsRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1BulkAnalyzeConversationsRequestOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptTranscriptSegmentDialogflowSegmentMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationTranscriptTranscriptSegmentDialogflowSegmentMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1RedactionConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1RedactionConfigOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnalysisResultIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnalysisResultOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationSummarizationSuggestionDataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ConversationSummarizationSuggestionDataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IssueIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnswerFeedbackIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnswerFeedbackOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SmartComposeSuggestionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SmartComposeSuggestionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationDataSourceIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationDataSourceOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationTranscriptIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationTranscriptOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeleteIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeleteIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UndeployIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1UndeployIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1UndeployIssueModelResponseIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1UndeployIssueModelResponseOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1RuntimeAnnotationIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1RuntimeAnnotationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ArticleSuggestionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ArticleSuggestionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListConversationsResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListConversationsResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataRequestBigQueryDestinationIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataRequestBigQueryDestinationOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1CalculateStatsResponseTimeSeriesIntervalIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1CalculateStatsResponseTimeSeriesIntervalOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1SettingsIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SettingsOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1InterruptionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1InterruptionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestGcsSourceIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestGcsSourceOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestTranscriptObjectConfigIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestTranscriptObjectConfigOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1GcsSourceIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1GcsSourceOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1FaqAnswerDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1FaqAnswerDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CalculateStatsResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CalculateStatsResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnnotatorSelectorSummarizationConfigIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1AnnotatorSelectorSummarizationConfigOut: t.typedef = (
        ...
    )
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationLevelSentimentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationLevelSentimentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnalysisResultCallAnalysisMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1AnalysisResultCallAnalysisMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1CreateAnalysisOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1CreateAnalysisOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1UndeployIssueModelMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1UndeployIssueModelMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1SentimentDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1SentimentDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SmartReplyDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SmartReplyDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestGcsSourceIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestGcsSourceOut: t.typedef = (
        ...
    )
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeleteIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeleteIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IntentMatchDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IntentMatchDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnalysisIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnalysisOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1RuntimeAnnotationIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1RuntimeAnnotationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelResultIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelResultOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ConversationParticipantIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationParticipantOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnnotationBoundaryIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnnotationBoundaryOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1BulkAnalyzeConversationsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1BulkAnalyzeConversationsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IssueModelLabelStatsIssueStatsIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelLabelStatsIssueStatsOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelLabelStatsIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelLabelStatsOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IntentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IntentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListViewsResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListViewsResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeleteIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeleteIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SilenceDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1SilenceDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IngestConversationsMetadataIngestConversationsStatsIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsMetadataIngestConversationsStatsOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1SmartComposeSuggestionDataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1SmartComposeSuggestionDataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1AnnotatorSelectorSummarizationConfigIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1AnnotatorSelectorSummarizationConfigOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestConversationConfigIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IngestConversationsRequestConversationConfigOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1AnnotatorSelectorIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnnotatorSelectorOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataRequestOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExportInsightsDataRequestBigQueryDestinationIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ExportInsightsDataRequestBigQueryDestinationOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1RedactionConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1RedactionConfigOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueMatchDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueMatchDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CreateIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CreateIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeleteIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeleteIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1BulkAnalyzeConversationsRequestIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1BulkAnalyzeConversationsRequestOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IssueModelInputDataConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IssueModelInputDataConfigOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnalysisIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1AnalysisOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CalculateStatsResponseTimeSeriesIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1CalculateStatsResponseTimeSeriesOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1IntentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IntentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationSummarizationSuggestionDataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ConversationSummarizationSuggestionDataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestConversationConfigIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IngestConversationsRequestConversationConfigOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1PhraseMatchRuleGroupIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatchRuleGroupOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeployIssueModelMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeployIssueModelMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatcherIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatcherOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentDialogflowSegmentMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1ConversationTranscriptTranscriptSegmentDialogflowSegmentMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1EntityMentionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1EntityMentionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeployIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DeployIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1FaqAnswerDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1FaqAnswerDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1HoldDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1HoldDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DialogflowIntentIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DialogflowIntentOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1CreateIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1CreateIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnnotationBoundaryIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1AnnotationBoundaryOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DialogflowSourceIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1DialogflowSourceOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueMatchDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueMatchDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IntentMatchDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1IntentMatchDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1InterruptionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1InterruptionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListAnalysesResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ListAnalysesResponseOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelLabelStatsIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelLabelStatsOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationCallMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ConversationCallMetadataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CreateAnalysisOperationMetadataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1CreateAnalysisOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1PhraseMatchRuleConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1PhraseMatchRuleConfigOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ArticleSuggestionDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1ArticleSuggestionDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1SilenceDataIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1SilenceDataOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1BulkAnalyzeConversationsMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1BulkAnalyzeConversationsMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudContactcenterinsightsV1alpha1IssueModelResultIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1IssueModelResultOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExactMatchConfigIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1ExactMatchConfigOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeployIssueModelRequestIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeployIssueModelRequestOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1EntityIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1alpha1EntityOut: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeployIssueModelResponseIn: t.typedef = ...
    GoogleCloudContactcenterinsightsV1DeployIssueModelResponseOut: t.typedef = ...

class FuncList:
    projectsLocationsUpdateSettings: t.func = ...
    projectsLocationsGetSettings: t.func = ...
    projectsLocationsInsightsdataExport: t.func = ...
    projectsLocationsIssueModelsCalculateIssueModelStats: t.func = ...
    projectsLocationsIssueModelsGet: t.func = ...
    projectsLocationsIssueModelsDeploy: t.func = ...
    projectsLocationsIssueModelsList: t.func = ...
    projectsLocationsIssueModelsDelete: t.func = ...
    projectsLocationsIssueModelsUndeploy: t.func = ...
    projectsLocationsIssueModelsPatch: t.func = ...
    projectsLocationsIssueModelsCreate: t.func = ...
    projectsLocationsIssueModelsIssuesGet: t.func = ...
    projectsLocationsIssueModelsIssuesPatch: t.func = ...
    projectsLocationsIssueModelsIssuesDelete: t.func = ...
    projectsLocationsIssueModelsIssuesList: t.func = ...
    projectsLocationsPhraseMatchersPatch: t.func = ...
    projectsLocationsPhraseMatchersDelete: t.func = ...
    projectsLocationsPhraseMatchersList: t.func = ...
    projectsLocationsPhraseMatchersGet: t.func = ...
    projectsLocationsPhraseMatchersCreate: t.func = ...
    projectsLocationsViewsCreate: t.func = ...
    projectsLocationsViewsDelete: t.func = ...
    projectsLocationsViewsGet: t.func = ...
    projectsLocationsViewsList: t.func = ...
    projectsLocationsViewsPatch: t.func = ...
    projectsLocationsConversationsDelete: t.func = ...
    projectsLocationsConversationsList: t.func = ...
    projectsLocationsConversationsIngest: t.func = ...
    projectsLocationsConversationsPatch: t.func = ...
    projectsLocationsConversationsCalculateStats: t.func = ...
    projectsLocationsConversationsCreate: t.func = ...
    projectsLocationsConversationsGet: t.func = ...
    projectsLocationsConversationsBulkAnalyze: t.func = ...
    projectsLocationsConversationsUpload: t.func = ...
    projectsLocationsConversationsAnalysesList: t.func = ...
    projectsLocationsConversationsAnalysesDelete: t.func = ...
    projectsLocationsConversationsAnalysesGet: t.func = ...
    projectsLocationsConversationsAnalysesCreate: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_contactcenterinsights() -> Import: ...
