from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudDatapipelinesV1PipelineIn: t.typedef = ...
    GoogleCloudDatapipelinesV1PipelineOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchTemplateParametersIn: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchTemplateParametersOut: t.typedef = ...
    GoogleCloudDatapipelinesV1WorkloadIn: t.typedef = ...
    GoogleCloudDatapipelinesV1WorkloadOut: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchFlexTemplateRequestIn: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchFlexTemplateRequestOut: t.typedef = ...
    GoogleCloudDatapipelinesV1RunPipelineRequestIn: t.typedef = ...
    GoogleCloudDatapipelinesV1RunPipelineRequestOut: t.typedef = ...
    GoogleCloudDatapipelinesV1RuntimeEnvironmentIn: t.typedef = ...
    GoogleCloudDatapipelinesV1RuntimeEnvironmentOut: t.typedef = ...
    GoogleCloudDatapipelinesV1ListPipelinesResponseIn: t.typedef = ...
    GoogleCloudDatapipelinesV1ListPipelinesResponseOut: t.typedef = ...
    GoogleCloudDatapipelinesV1DataflowJobDetailsIn: t.typedef = ...
    GoogleCloudDatapipelinesV1DataflowJobDetailsOut: t.typedef = ...
    GoogleCloudDatapipelinesV1StopPipelineRequestIn: t.typedef = ...
    GoogleCloudDatapipelinesV1StopPipelineRequestOut: t.typedef = ...
    GoogleCloudDatapipelinesV1SdkVersionIn: t.typedef = ...
    GoogleCloudDatapipelinesV1SdkVersionOut: t.typedef = ...
    GoogleCloudDatapipelinesV1RunPipelineResponseIn: t.typedef = ...
    GoogleCloudDatapipelinesV1RunPipelineResponseOut: t.typedef = ...
    GoogleCloudDatapipelinesV1JobIn: t.typedef = ...
    GoogleCloudDatapipelinesV1JobOut: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchFlexTemplateParameterIn: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchFlexTemplateParameterOut: t.typedef = ...
    GoogleCloudDatapipelinesV1FlexTemplateRuntimeEnvironmentIn: t.typedef = ...
    GoogleCloudDatapipelinesV1FlexTemplateRuntimeEnvironmentOut: t.typedef = ...
    GoogleCloudDatapipelinesV1ListJobsResponseIn: t.typedef = ...
    GoogleCloudDatapipelinesV1ListJobsResponseOut: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchTemplateRequestIn: t.typedef = ...
    GoogleCloudDatapipelinesV1LaunchTemplateRequestOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudDatapipelinesV1ScheduleSpecIn: t.typedef = ...
    GoogleCloudDatapipelinesV1ScheduleSpecOut: t.typedef = ...

class FuncList:
    projectsLocationsPipelinesCreate: t.func = ...
    projectsLocationsPipelinesRun: t.func = ...
    projectsLocationsPipelinesStop: t.func = ...
    projectsLocationsPipelinesPatch: t.func = ...
    projectsLocationsPipelinesGet: t.func = ...
    projectsLocationsPipelinesList: t.func = ...
    projectsLocationsPipelinesDelete: t.func = ...
    projectsLocationsPipelinesJobsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_datapipelines() -> Import: ...
