from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    CertificateInfoIn: t.typedef = ...
    CertificateInfoOut: t.typedef = ...
    BulkCheckRequestIn: t.typedef = ...
    BulkCheckRequestOut: t.typedef = ...
    AssetIn: t.typedef = ...
    AssetOut: t.typedef = ...
    StatementIn: t.typedef = ...
    StatementOut: t.typedef = ...
    BulkCheckResponseIn: t.typedef = ...
    BulkCheckResponseOut: t.typedef = ...
    StatementTemplateIn: t.typedef = ...
    StatementTemplateOut: t.typedef = ...
    CheckResponseIn: t.typedef = ...
    CheckResponseOut: t.typedef = ...
    ListResponseIn: t.typedef = ...
    ListResponseOut: t.typedef = ...
    WebAssetIn: t.typedef = ...
    WebAssetOut: t.typedef = ...
    AndroidAppAssetIn: t.typedef = ...
    AndroidAppAssetOut: t.typedef = ...

class FuncList:
    assetlinksBulkCheck: t.func = ...
    assetlinksCheck: t.func = ...
    statementsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_digitalassetlinks() -> Import: ...
