from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    JsonSchemaIn: t.typedef = ...
    JsonSchemaOut: t.typedef = ...
    RestDescriptionIn: t.typedef = ...
    RestDescriptionOut: t.typedef = ...
    RestMethodIn: t.typedef = ...
    RestMethodOut: t.typedef = ...
    RestResourceIn: t.typedef = ...
    RestResourceOut: t.typedef = ...
    DirectoryListIn: t.typedef = ...
    DirectoryListOut: t.typedef = ...

class FuncList:
    apisGetRest: t.func = ...
    apisList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_discovery() -> Import: ...
