from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageFormFieldIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageFormFieldOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UpdateDatasetOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UpdateDatasetOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentEntityIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentEntityOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EnableProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EnableProcessorMetadataOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationCountersIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationCountersOut: t.typedef = ...
    GoogleCloudLocationLocationIn: t.typedef = ...
    GoogleCloudLocationLocationOut: t.typedef = ...
    GoogleTypeDateIn: t.typedef = ...
    GoogleTypeDateOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageMatrixIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageMatrixOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluateProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluateProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1UndeployProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1UndeployProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1GcsDocumentsIn: t.typedef = ...
    GoogleCloudDocumentaiV1GcsDocumentsOut: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentShardInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentShardInfoOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTableIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTableOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorTypeLocationInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorTypeLocationInfoOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UpdateHumanReviewConfigMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UpdateHumanReviewConfigMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2ProcessDocumentResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2ProcessDocumentResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2OperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2OperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DeployProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1DeployProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageBlockIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageBlockOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTableIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTableOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeployProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeployProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DisableProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DisableProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageAnchorIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageAnchorOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorVersionDeprecationInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorVersionDeprecationInfoOut: t.typedef = ...
    GoogleCloudDocumentaiV1GcsDocumentIn: t.typedef = ...
    GoogleCloudDocumentaiV1GcsDocumentOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1GcsSourceIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1GcsSourceOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTableTableRowIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTableTableRowOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaEntityTypePropertyIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaEntityTypePropertyOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageAnchorPageRefIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageAnchorPageRefOut: t.typedef = ...
    GoogleCloudDocumentaiV1SetDefaultProcessorVersionRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1SetDefaultProcessorVersionRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionRequestInputDataIn: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionRequestInputDataOut: t.typedef = ...
    GoogleCloudDocumentaiV1SetDefaultProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1SetDefaultProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1EnableProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1EnableProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1SetDefaultProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1SetDefaultProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageDetectedLanguageIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageDetectedLanguageOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTokenDetectedBreakIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTokenDetectedBreakOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaEntityTypeEnumValuesIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaEntityTypeEnumValuesOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentProvenanceIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentProvenanceOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageImageIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageImageOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageImageIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageImageOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageDetectedLanguageIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageDetectedLanguageOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTokenStyleInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTokenStyleInfoOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1InputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1InputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1FetchProcessorTypesResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1FetchProcessorTypesResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageMatrixIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageMatrixOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageDetectedLanguageIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageDetectedLanguageOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetMetadataDatasetResyncStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetMetadataDatasetResyncStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta1DocumentShardInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentShardInfoOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1ListEvaluationsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1ListEvaluationsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentRevisionHumanReviewIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentRevisionHumanReviewOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTokenIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTokenOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EvaluateProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EvaluateProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentShardInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentShardInfoOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationMultiConfidenceMetricsIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationMultiConfidenceMetricsOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorTypeIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorTypeOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UndeployProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UndeployProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentTextChangeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentTextChangeOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EvaluateProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EvaluateProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SetDefaultProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SetDefaultProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2BoundingPolyIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2BoundingPolyOut: t.typedef = ...
    GoogleCloudDocumentaiV1ListProcessorVersionsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1ListProcessorVersionsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ReviewDocumentResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ReviewDocumentResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentTextAnchorTextSegmentIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentTextAnchorTextSegmentOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3TrainProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3TrainProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorVersionIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorVersionOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ImportProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ImportProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageLineIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageLineOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageParagraphIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageParagraphOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3UndeployProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3UndeployProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SampleDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SampleDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageDetectedBarcodeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageDetectedBarcodeOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3BatchProcessMetadataIndividualProcessStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta3BatchProcessMetadataIndividualProcessStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3UpdateLabelerPoolOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UpdateLabelerPoolOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTableTableRowIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTableTableRowOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentEntityRelationIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentEntityRelationOut: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeleteProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeleteProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SetDefaultProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SetDefaultProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentStyleIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentStyleOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3TrainProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3TrainProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DocumentIdGCSManagedDocumentIdIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DocumentIdGCSManagedDocumentIdOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageLineIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageLineOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2GcsSourceIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2GcsSourceOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeployProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeployProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTokenIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTokenOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EvaluateProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EvaluateProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EnableProcessorResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EnableProcessorResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentProvenanceIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentProvenanceOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageDimensionIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageDimensionOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTableIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTableOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageParagraphIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageParagraphOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3TrainProcessorVersionMetadataDatasetValidationIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta3TrainProcessorVersionMetadataDatasetValidationOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentOutputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentOutputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageImageQualityScoresIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageImageQualityScoresOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataSplitExportStatIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataSplitExportStatOut: t.typedef = (
        ...
    )
    GoogleTypePostalAddressIn: t.typedef = ...
    GoogleTypePostalAddressOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageBlockIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageBlockOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentRevisionIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentRevisionOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3TrainProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3TrainProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeleteProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeleteProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataIndividualAutoLabelStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataIndividualAutoLabelStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta1DocumentRevisionHumanReviewIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentRevisionHumanReviewOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentStyleFontSizeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentStyleFontSizeOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeployProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeployProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentTextChangeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentTextChangeOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageImageQualityScoresIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageImageQualityScoresOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeployProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeployProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataIndividualExportStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataIndividualExportStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1BatchProcessMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1BatchProcessMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentStyleFontSizeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentStyleFontSizeOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DisableProcessorResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DisableProcessorResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTokenDetectedBreakIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTokenDetectedBreakOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2BatchProcessDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2BatchProcessDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2GcsDestinationIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2GcsDestinationOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageVisualElementIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageVisualElementOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentEntityRelationIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentEntityRelationOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTokenStyleInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTokenStyleInfoOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2OutputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2OutputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageImageQualityScoresDetectedDefectIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentPageImageQualityScoresDetectedDefectOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentProvenanceParentIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentProvenanceParentOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageLineIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageLineOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3CommonOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3CommonOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeleteLabelerPoolOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeleteLabelerPoolOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentProvenanceParentIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentProvenanceParentOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1NormalizedVertexIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1NormalizedVertexOut: t.typedef = ...
    GoogleCloudDocumentaiV1VertexIn: t.typedef = ...
    GoogleCloudDocumentaiV1VertexOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2BarcodeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2BarcodeOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1OutputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1OutputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTableTableCellIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTableTableCellOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentStyleIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentStyleOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageLayoutIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageLayoutOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageSymbolIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageSymbolOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentLabelIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentLabelOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageImageQualityScoresDetectedDefectIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta1DocumentPageImageQualityScoresDetectedDefectOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3DocumentIdIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DocumentIdOut: t.typedef = ...
    GoogleCloudDocumentaiV1BoundingPolyIn: t.typedef = ...
    GoogleCloudDocumentaiV1BoundingPolyOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SampleDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SampleDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeleteProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DeleteProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EnableProcessorResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EnableProcessorResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessorOut: t.typedef = ...
    GoogleTypeColorIn: t.typedef = ...
    GoogleTypeColorOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageOut: t.typedef = ...
    GoogleCloudDocumentaiV1BatchDocumentsInputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1BatchDocumentsInputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3TrainProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3TrainProcessorVersionResponseOut: t.typedef = ...
    GoogleTypeTimeZoneIn: t.typedef = ...
    GoogleTypeTimeZoneOut: t.typedef = ...
    GoogleCloudDocumentaiV1ReviewDocumentOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1ReviewDocumentOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DisableProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1DisableProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationConfidenceLevelMetricsIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationConfidenceLevelMetricsOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageVisualElementIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageVisualElementOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageFormFieldIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageFormFieldOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsMetadataIndividualImportStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsMetadataIndividualImportStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta2DocumentPageAnchorIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageAnchorOut: t.typedef = ...
    GoogleCloudDocumentaiV1DisableProcessorRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1DisableProcessorRequestOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataIndividualBatchMoveStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataIndividualBatchMoveStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentEntityNormalizedValueIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentEntityNormalizedValueOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1OperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1OperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentTextAnchorIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentTextAnchorOut: t.typedef = ...
    GoogleCloudDocumentaiV1DeleteProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1DeleteProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentEntityIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentEntityOut: t.typedef = ...
    GoogleCloudDocumentaiV1UndeployProcessorVersionRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1UndeployProcessorVersionRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1NormalizedVertexIn: t.typedef = ...
    GoogleCloudDocumentaiV1NormalizedVertexOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluateProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluateProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentProvenanceIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentProvenanceOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentEntityNormalizedValueIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentEntityNormalizedValueOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageImageIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageImageOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentTextAnchorIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentTextAnchorOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentEntityRelationIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentEntityRelationOut: t.typedef = ...
    GoogleTypeDateTimeIn: t.typedef = ...
    GoogleTypeDateTimeOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2NormalizedVertexIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2NormalizedVertexOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3TrainProcessorVersionMetadataDatasetValidationIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3TrainProcessorVersionMetadataDatasetValidationOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentPageDimensionIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageDimensionOut: t.typedef = ...
    GoogleCloudDocumentaiV1ListProcessorsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1ListProcessorsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTokenStyleInfoIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTokenStyleInfoOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1ProcessDocumentResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1ProcessDocumentResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageDetectedBarcodeIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageDetectedBarcodeOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentProvenanceParentIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentProvenanceParentOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EvaluateProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3EvaluateProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageParagraphIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageParagraphOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1TrainProcessorVersionMetadataDatasetValidationIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1TrainProcessorVersionMetadataDatasetValidationOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1ListProcessorTypesResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1ListProcessorTypesResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentTextAnchorTextSegmentIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentTextAnchorTextSegmentOut: t.typedef = ...
    GoogleCloudDocumentaiV1ReviewDocumentResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1ReviewDocumentResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTokenIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTokenOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentTextAnchorIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentTextAnchorOut: t.typedef = ...
    GoogleCloudDocumentaiV1DeployProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1DeployProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTokenDetectedBreakIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageTokenDetectedBreakOut: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1ProcessResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3CommonOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3CommonOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3CreateLabelerPoolOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3CreateLabelerPoolOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DisableProcessorResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DisableProcessorResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageAnchorPageRefIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageAnchorPageRefOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentRevisionIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentRevisionOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentEntityNormalizedValueIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentEntityNormalizedValueOut: t.typedef = ...
    GoogleCloudDocumentaiV1EnableProcessorRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1EnableProcessorRequestOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ExportProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTableTableRowIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTableTableRowOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3SampleDocumentsResponseSelectedDocumentIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3SampleDocumentsResponseSelectedDocumentOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentTextChangeIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentTextChangeOut: t.typedef = ...
    GoogleCloudDocumentaiV1DisableProcessorResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1DisableProcessorResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3SetDefaultProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3SetDefaultProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageLayoutIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageLayoutOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3BatchProcessMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3BatchProcessMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageFormFieldIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageFormFieldOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1BarcodeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1BarcodeOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageAnchorIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageAnchorOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentStyleIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentStyleOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1BatchProcessDocumentsResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1BatchProcessDocumentsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1BatchProcessRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1BatchProcessRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationMetricsIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationMetricsOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeleteProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3DeleteProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageSymbolIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageSymbolOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentRevisionIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentRevisionOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3SetDefaultProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3SetDefaultProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudLocationListLocationsResponseIn: t.typedef = ...
    GoogleCloudLocationListLocationsResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1DeployProcessorVersionRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1DeployProcessorVersionRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1VertexIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1VertexOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageLayoutIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageLayoutOut: t.typedef = ...
    GoogleCloudDocumentaiV1UndeployProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1UndeployProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationReferenceIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluationReferenceOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaEntityTypeIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentSchemaEntityTypeOut: t.typedef = ...
    GoogleTypeMoneyIn: t.typedef = ...
    GoogleTypeMoneyOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudDocumentaiV1DeleteProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1DeleteProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetMetadataIndividualDocumentResyncStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetMetadataIndividualDocumentResyncStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1EnableProcessorResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1EnableProcessorResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageImageQualityScoresDetectedDefectIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1beta2DocumentPageImageQualityScoresDetectedDefectOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentRevisionHumanReviewIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentRevisionHumanReviewOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3HumanReviewStatusIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3HumanReviewStatusOut: t.typedef = ...
    GoogleCloudDocumentaiV1BarcodeIn: t.typedef = ...
    GoogleCloudDocumentaiV1BarcodeOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigShardingConfigIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigShardingConfigOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1BatchProcessMetadataIndividualProcessStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1BatchProcessMetadataIndividualProcessStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1HumanReviewStatusIn: t.typedef = ...
    GoogleCloudDocumentaiV1HumanReviewStatusOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageSymbolIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageSymbolOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTableTableCellIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageTableTableCellOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentTextAnchorTextSegmentIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentTextAnchorTextSegmentOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageVisualElementIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageVisualElementOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageAnchorPageRefIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageAnchorPageRefOut: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluateProcessorVersionRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1EvaluateProcessorVersionRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3BatchProcessResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3BatchProcessResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1BoundingPolyIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1BoundingPolyOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2VertexIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2VertexOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2InputConfigIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2InputConfigOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentEntityIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentEntityOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageDimensionIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageDimensionOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UndeployProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3UndeployProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DisableProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3DisableProcessorMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3UndeployProcessorVersionResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3UndeployProcessorVersionResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTableTableCellIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1DocumentPageTableTableCellOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ImportProcessorVersionMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ImportProcessorVersionMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsMetadataImportConfigValidationResultIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3ImportDocumentsMetadataImportConfigValidationResultOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1RawDocumentIn: t.typedef = ...
    GoogleCloudDocumentaiV1RawDocumentOut: t.typedef = ...
    GoogleCloudDocumentaiV1ReviewDocumentRequestIn: t.typedef = ...
    GoogleCloudDocumentaiV1ReviewDocumentRequestOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ReviewDocumentOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3ReviewDocumentOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageImageQualityScoresIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageImageQualityScoresOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageMatrixIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageMatrixOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetResponseIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3ResyncDatasetResponseOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta1GcsDestinationIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta1GcsDestinationOut: t.typedef = ...
    GoogleCloudDocumentaiV1GcsPrefixIn: t.typedef = ...
    GoogleCloudDocumentaiV1GcsPrefixOut: t.typedef = ...
    GoogleCloudDocumentaiV1BatchProcessResponseIn: t.typedef = ...
    GoogleCloudDocumentaiV1BatchProcessResponseOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataIndividualBatchDeleteStatusIn: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataIndividualBatchDeleteStatusOut: t.typedef = (
        ...
    )
    GoogleCloudDocumentaiV1DocumentPageBlockIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentPageBlockOut: t.typedef = ...
    GoogleCloudDocumentaiV1CommonOperationMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1CommonOperationMetadataOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageDetectedBarcodeIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta2DocumentPageDetectedBarcodeOut: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentStyleFontSizeIn: t.typedef = ...
    GoogleCloudDocumentaiV1DocumentStyleFontSizeOut: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3RevisionRefIn: t.typedef = ...
    GoogleCloudDocumentaiUiv1beta3RevisionRefOut: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EnableProcessorMetadataIn: t.typedef = ...
    GoogleCloudDocumentaiV1beta3EnableProcessorMetadataOut: t.typedef = ...

class FuncList:
    operationsDelete: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsFetchProcessorTypes: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsProcessorsProcess: t.func = ...
    projectsLocationsProcessorsCreate: t.func = ...
    projectsLocationsProcessorsBatchProcess: t.func = ...
    projectsLocationsProcessorsDisable: t.func = ...
    projectsLocationsProcessorsList: t.func = ...
    projectsLocationsProcessorsSetDefaultProcessorVersion: t.func = ...
    projectsLocationsProcessorsGet: t.func = ...
    projectsLocationsProcessorsDelete: t.func = ...
    projectsLocationsProcessorsEnable: t.func = ...
    projectsLocationsProcessorsProcessorVersionsBatchProcess: t.func = ...
    projectsLocationsProcessorsProcessorVersionsGet: t.func = ...
    projectsLocationsProcessorsProcessorVersionsDelete: t.func = ...
    projectsLocationsProcessorsProcessorVersionsUndeploy: t.func = ...
    projectsLocationsProcessorsProcessorVersionsEvaluateProcessorVersion: t.func = ...
    projectsLocationsProcessorsProcessorVersionsProcess: t.func = ...
    projectsLocationsProcessorsProcessorVersionsList: t.func = ...
    projectsLocationsProcessorsProcessorVersionsDeploy: t.func = ...
    projectsLocationsProcessorsProcessorVersionsTrain: t.func = ...
    projectsLocationsProcessorsProcessorVersionsEvaluationsList: t.func = ...
    projectsLocationsProcessorsProcessorVersionsEvaluationsGet: t.func = ...
    projectsLocationsProcessorsHumanReviewConfigReviewDocument: t.func = ...
    projectsLocationsProcessorTypesGet: t.func = ...
    projectsLocationsProcessorTypesList: t.func = ...
    projectsOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_documentai() -> Import: ...
