from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    NoticeIn: t.typedef = ...
    NoticeOut: t.typedef = ...
    LinkIn: t.typedef = ...
    LinkOut: t.typedef = ...
    HttpBodyIn: t.typedef = ...
    HttpBodyOut: t.typedef = ...
    RdapResponseIn: t.typedef = ...
    RdapResponseOut: t.typedef = ...

class FuncList:
    ipGet: t.func = ...
    v1GetNameservers: t.func = ...
    v1GetIp: t.func = ...
    v1GetDomains: t.func = ...
    v1GetHelp: t.func = ...
    v1GetEntities: t.func = ...
    nameserverGet: t.func = ...
    domainGet: t.func = ...
    entityGet: t.func = ...
    autnumGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_domainsrdap() -> Import: ...
