from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SavedColumnListIn: t.typedef = ...
    SavedColumnListOut: t.typedef = ...
    UpdateAvailabilityResponseIn: t.typedef = ...
    UpdateAvailabilityResponseOut: t.typedef = ...
    CustomDimensionIn: t.typedef = ...
    CustomDimensionOut: t.typedef = ...
    AvailabilityIn: t.typedef = ...
    AvailabilityOut: t.typedef = ...
    CustomMetricIn: t.typedef = ...
    CustomMetricOut: t.typedef = ...
    ConversionIn: t.typedef = ...
    ConversionOut: t.typedef = ...
    ReportRowIn: t.typedef = ...
    ReportRowOut: t.typedef = ...
    ConversionListIn: t.typedef = ...
    ConversionListOut: t.typedef = ...
    ReportIn: t.typedef = ...
    ReportOut: t.typedef = ...
    ReportApiColumnSpecIn: t.typedef = ...
    ReportApiColumnSpecOut: t.typedef = ...
    ReportRequestIn: t.typedef = ...
    ReportRequestOut: t.typedef = ...
    IdMappingFileIn: t.typedef = ...
    IdMappingFileOut: t.typedef = ...
    SavedColumnIn: t.typedef = ...
    SavedColumnOut: t.typedef = ...
    UpdateAvailabilityRequestIn: t.typedef = ...
    UpdateAvailabilityRequestOut: t.typedef = ...

class FuncList:
    savedColumnsList: t.func = ...
    conversionUpdate: t.func = ...
    conversionGetByCustomerId: t.func = ...
    conversionGet: t.func = ...
    conversionInsert: t.func = ...
    conversionUpdateAvailability: t.func = ...
    reportsGetFile: t.func = ...
    reportsRequest: t.func = ...
    reportsGetIdMappingFile: t.func = ...
    reportsGet: t.func = ...
    reportsGenerate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_doubleclicksearch() -> Import: ...
