from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudEssentialcontactsV1ContactIn: t.typedef = ...
    GoogleCloudEssentialcontactsV1ContactOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudEssentialcontactsV1ListContactsResponseIn: t.typedef = ...
    GoogleCloudEssentialcontactsV1ListContactsResponseOut: t.typedef = ...
    GoogleCloudEssentialcontactsV1SendTestMessageRequestIn: t.typedef = ...
    GoogleCloudEssentialcontactsV1SendTestMessageRequestOut: t.typedef = ...
    GoogleCloudEssentialcontactsV1ComputeContactsResponseIn: t.typedef = ...
    GoogleCloudEssentialcontactsV1ComputeContactsResponseOut: t.typedef = ...

class FuncList:
    projectsContactsGet: t.func = ...
    projectsContactsPatch: t.func = ...
    projectsContactsList: t.func = ...
    projectsContactsDelete: t.func = ...
    projectsContactsCreate: t.func = ...
    projectsContactsSendTestMessage: t.func = ...
    projectsContactsCompute: t.func = ...
    foldersContactsCompute: t.func = ...
    foldersContactsCreate: t.func = ...
    foldersContactsGet: t.func = ...
    foldersContactsList: t.func = ...
    foldersContactsPatch: t.func = ...
    foldersContactsDelete: t.func = ...
    foldersContactsSendTestMessage: t.func = ...
    organizationsContactsSendTestMessage: t.func = ...
    organizationsContactsDelete: t.func = ...
    organizationsContactsPatch: t.func = ...
    organizationsContactsCreate: t.func = ...
    organizationsContactsList: t.func = ...
    organizationsContactsGet: t.func = ...
    organizationsContactsCompute: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_essentialcontacts() -> Import: ...
