from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    UrlNotificationIn: t.typedef = ...
    UrlNotificationOut: t.typedef = ...
    PublishUrlNotificationResponseIn: t.typedef = ...
    PublishUrlNotificationResponseOut: t.typedef = ...
    UrlNotificationMetadataIn: t.typedef = ...
    UrlNotificationMetadataOut: t.typedef = ...

class FuncList:
    urlNotificationsPublish: t.func = ...
    urlNotificationsGetMetadata: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_indexing() -> Import: ...
