from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    DailyCycleIn: t.typedef = ...
    DailyCycleOut: t.typedef = ...
    LDAPSSettingsIn: t.typedef = ...
    LDAPSSettingsOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityOut: t.typedef = (
        ...
    )
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    SqlIntegrationIn: t.typedef = ...
    SqlIntegrationOut: t.typedef = ...
    RestoreDomainRequestIn: t.typedef = ...
    RestoreDomainRequestOut: t.typedef = ...
    ScheduleIn: t.typedef = ...
    ScheduleOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    PeeringIn: t.typedef = ...
    PeeringOut: t.typedef = ...
    DisableMigrationRequestIn: t.typedef = ...
    DisableMigrationRequestOut: t.typedef = ...
    DomainJoinMachineResponseIn: t.typedef = ...
    DomainJoinMachineResponseOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    OnPremDomainDetailsIn: t.typedef = ...
    OnPremDomainDetailsOut: t.typedef = ...
    EnableMigrationRequestIn: t.typedef = ...
    EnableMigrationRequestOut: t.typedef = ...
    CertificateIn: t.typedef = ...
    CertificateOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    DetachTrustRequestIn: t.typedef = ...
    DetachTrustRequestOut: t.typedef = ...
    UpdatePolicyIn: t.typedef = ...
    UpdatePolicyOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    GoogleCloudManagedidentitiesV1alpha1OpMetadataIn: t.typedef = ...
    GoogleCloudManagedidentitiesV1alpha1OpMetadataOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    GoogleCloudManagedidentitiesV1OpMetadataIn: t.typedef = ...
    GoogleCloudManagedidentitiesV1OpMetadataOut: t.typedef = ...
    BackupIn: t.typedef = ...
    BackupOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    WeeklyCycleIn: t.typedef = ...
    WeeklyCycleOut: t.typedef = ...
    AttachTrustRequestIn: t.typedef = ...
    AttachTrustRequestOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameterIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameterOut: t.typedef = (
        ...
    )
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    DomainIn: t.typedef = ...
    DomainOut: t.typedef = ...
    TimeOfDayIn: t.typedef = ...
    TimeOfDayOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataOut: t.typedef = ...
    ListDomainsResponseIn: t.typedef = ...
    ListDomainsResponseOut: t.typedef = ...
    ReconfigureTrustRequestIn: t.typedef = ...
    ReconfigureTrustRequestOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceScheduleIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceScheduleOut: t.typedef = (
        ...
    )
    ListPeeringsResponseIn: t.typedef = ...
    ListPeeringsResponseOut: t.typedef = ...
    ResetAdminPasswordResponseIn: t.typedef = ...
    ResetAdminPasswordResponseOut: t.typedef = ...
    ListSqlIntegrationsResponseIn: t.typedef = ...
    ListSqlIntegrationsResponseOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1InstanceIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1InstanceOut: t.typedef = ...
    ListBackupsResponseIn: t.typedef = ...
    ListBackupsResponseOut: t.typedef = ...
    ExtendSchemaRequestIn: t.typedef = ...
    ExtendSchemaRequestOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    ValidateTrustRequestIn: t.typedef = ...
    ValidateTrustRequestOut: t.typedef = ...
    DenyMaintenancePeriodIn: t.typedef = ...
    DenyMaintenancePeriodOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceOut: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsOut: t.typedef = (
        ...
    )
    ResetAdminPasswordRequestIn: t.typedef = ...
    ResetAdminPasswordRequestOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    GoogleCloudManagedidentitiesV1beta1OpMetadataIn: t.typedef = ...
    GoogleCloudManagedidentitiesV1beta1OpMetadataOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    MaintenancePolicyIn: t.typedef = ...
    MaintenancePolicyOut: t.typedef = ...
    MaintenanceWindowIn: t.typedef = ...
    MaintenanceWindowOut: t.typedef = ...
    DomainJoinMachineRequestIn: t.typedef = ...
    DomainJoinMachineRequestOut: t.typedef = ...
    TrustIn: t.typedef = ...
    TrustOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsGlobalOperationsList: t.func = ...
    projectsLocationsGlobalOperationsGet: t.func = ...
    projectsLocationsGlobalOperationsDelete: t.func = ...
    projectsLocationsGlobalOperationsCancel: t.func = ...
    projectsLocationsGlobalDomainsTestIamPermissions: t.func = ...
    projectsLocationsGlobalDomainsGetIamPolicy: t.func = ...
    projectsLocationsGlobalDomainsGet: t.func = ...
    projectsLocationsGlobalDomainsAttachTrust: t.func = ...
    projectsLocationsGlobalDomainsDetachTrust: t.func = ...
    projectsLocationsGlobalDomainsSetIamPolicy: t.func = ...
    projectsLocationsGlobalDomainsDisableMigration: t.func = ...
    projectsLocationsGlobalDomainsDelete: t.func = ...
    projectsLocationsGlobalDomainsResetAdminPassword: t.func = ...
    projectsLocationsGlobalDomainsGetLdapssettings: t.func = ...
    projectsLocationsGlobalDomainsUpdateLdapssettings: t.func = ...
    projectsLocationsGlobalDomainsValidateTrust: t.func = ...
    projectsLocationsGlobalDomainsExtendSchema: t.func = ...
    projectsLocationsGlobalDomainsList: t.func = ...
    projectsLocationsGlobalDomainsReconfigureTrust: t.func = ...
    projectsLocationsGlobalDomainsPatch: t.func = ...
    projectsLocationsGlobalDomainsRestore: t.func = ...
    projectsLocationsGlobalDomainsEnableMigration: t.func = ...
    projectsLocationsGlobalDomainsDomainJoinMachine: t.func = ...
    projectsLocationsGlobalDomainsCreate: t.func = ...
    projectsLocationsGlobalDomainsSqlIntegrationsList: t.func = ...
    projectsLocationsGlobalDomainsSqlIntegrationsGet: t.func = ...
    projectsLocationsGlobalDomainsBackupsCreate: t.func = ...
    projectsLocationsGlobalDomainsBackupsPatch: t.func = ...
    projectsLocationsGlobalDomainsBackupsTestIamPermissions: t.func = ...
    projectsLocationsGlobalDomainsBackupsGetIamPolicy: t.func = ...
    projectsLocationsGlobalDomainsBackupsSetIamPolicy: t.func = ...
    projectsLocationsGlobalDomainsBackupsList: t.func = ...
    projectsLocationsGlobalDomainsBackupsDelete: t.func = ...
    projectsLocationsGlobalDomainsBackupsGet: t.func = ...
    projectsLocationsGlobalPeeringsTestIamPermissions: t.func = ...
    projectsLocationsGlobalPeeringsList: t.func = ...
    projectsLocationsGlobalPeeringsGet: t.func = ...
    projectsLocationsGlobalPeeringsPatch: t.func = ...
    projectsLocationsGlobalPeeringsCreate: t.func = ...
    projectsLocationsGlobalPeeringsDelete: t.func = ...
    projectsLocationsGlobalPeeringsGetIamPolicy: t.func = ...
    projectsLocationsGlobalPeeringsSetIamPolicy: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_managedidentities() -> Import: ...
