from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudMlV1_CheckTrialEarlyStoppingStateRequestIn: t.typedef = ...
    GoogleCloudMlV1_CheckTrialEarlyStoppingStateRequestOut: t.typedef = ...
    GoogleCloudMlV1_TrainingOutputIn: t.typedef = ...
    GoogleCloudMlV1_TrainingOutputOut: t.typedef = ...
    GoogleCloudMlV1_ListModelsResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListModelsResponseOut: t.typedef = ...
    GoogleIamV1_TestIamPermissionsResponseIn: t.typedef = ...
    GoogleIamV1_TestIamPermissionsResponseOut: t.typedef = ...
    GoogleApi_HttpBodyIn: t.typedef = ...
    GoogleApi_HttpBodyOut: t.typedef = ...
    GoogleCloudMlV1_StopTrialRequestIn: t.typedef = ...
    GoogleCloudMlV1_StopTrialRequestOut: t.typedef = ...
    GoogleIamV1_TestIamPermissionsRequestIn: t.typedef = ...
    GoogleIamV1_TestIamPermissionsRequestOut: t.typedef = ...
    GoogleCloudMlV1_CheckTrialEarlyStoppingStateResponseIn: t.typedef = ...
    GoogleCloudMlV1_CheckTrialEarlyStoppingStateResponseOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_ParameterSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_ParameterSpecOut: t.typedef = ...
    GoogleCloudMlV1_GetConfigResponseIn: t.typedef = ...
    GoogleCloudMlV1_GetConfigResponseOut: t.typedef = ...
    GoogleCloudMlV1_ParameterSpecIn: t.typedef = ...
    GoogleCloudMlV1_ParameterSpecOut: t.typedef = ...
    GoogleCloudMlV1_ExplanationConfigIn: t.typedef = ...
    GoogleCloudMlV1_ExplanationConfigOut: t.typedef = ...
    GoogleCloudMlV1_DiskConfigIn: t.typedef = ...
    GoogleCloudMlV1_DiskConfigOut: t.typedef = ...
    GoogleCloudMlV1_CheckTrialEarlyStoppingStateMetatdataIn: t.typedef = ...
    GoogleCloudMlV1_CheckTrialEarlyStoppingStateMetatdataOut: t.typedef = ...
    GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetricIn: t.typedef = ...
    GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetricOut: t.typedef = ...
    GoogleCloudMlV1_AddTrialMeasurementRequestIn: t.typedef = ...
    GoogleCloudMlV1_AddTrialMeasurementRequestOut: t.typedef = ...
    GoogleCloudMlV1_PredictionInputIn: t.typedef = ...
    GoogleCloudMlV1_PredictionInputOut: t.typedef = ...
    GoogleCloudMlV1_ListJobsResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListJobsResponseOut: t.typedef = ...
    GoogleCloudMlV1_ListVersionsResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListVersionsResponseOut: t.typedef = ...
    GoogleIamV1_PolicyIn: t.typedef = ...
    GoogleIamV1_PolicyOut: t.typedef = ...
    GoogleCloudMlV1_ListOptimalTrialsResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListOptimalTrialsResponseOut: t.typedef = ...
    GoogleCloudMlV1_SuggestTrialsMetadataIn: t.typedef = ...
    GoogleCloudMlV1_SuggestTrialsMetadataOut: t.typedef = ...
    GoogleCloudMlV1_TrainingInputIn: t.typedef = ...
    GoogleCloudMlV1_TrainingInputOut: t.typedef = ...
    GoogleCloudMlV1_ListStudiesResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListStudiesResponseOut: t.typedef = ...
    GoogleCloudMlV1_SchedulingIn: t.typedef = ...
    GoogleCloudMlV1_SchedulingOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpecOut: t.typedef = ...
    GoogleCloudMlV1_ModelIn: t.typedef = ...
    GoogleCloudMlV1_ModelOut: t.typedef = ...
    GoogleIamV1_AuditLogConfigIn: t.typedef = ...
    GoogleIamV1_AuditLogConfigOut: t.typedef = ...
    GoogleCloudMlV1_ListLocationsResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListLocationsResponseOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpecIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpecOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1_SuggestTrialsResponseIn: t.typedef = ...
    GoogleCloudMlV1_SuggestTrialsResponseOut: t.typedef = ...
    GoogleCloudMlV1_EncryptionConfigIn: t.typedef = ...
    GoogleCloudMlV1_EncryptionConfigOut: t.typedef = ...
    GoogleRpc_StatusIn: t.typedef = ...
    GoogleRpc_StatusOut: t.typedef = ...
    GoogleCloudMlV1_LocationIn: t.typedef = ...
    GoogleCloudMlV1_LocationOut: t.typedef = ...
    GoogleCloudMlV1_MeasurementIn: t.typedef = ...
    GoogleCloudMlV1_MeasurementOut: t.typedef = ...
    GoogleLongrunning_ListOperationsResponseIn: t.typedef = ...
    GoogleLongrunning_ListOperationsResponseOut: t.typedef = ...
    GoogleCloudMlV1_AutoScalingIn: t.typedef = ...
    GoogleCloudMlV1_AutoScalingOut: t.typedef = ...
    GoogleCloudMlV1_PredictRequestIn: t.typedef = ...
    GoogleCloudMlV1_PredictRequestOut: t.typedef = ...
    GoogleCloudMlV1_SuggestTrialsRequestIn: t.typedef = ...
    GoogleCloudMlV1_SuggestTrialsRequestOut: t.typedef = ...
    GoogleCloudMlV1_Measurement_MetricIn: t.typedef = ...
    GoogleCloudMlV1_Measurement_MetricOut: t.typedef = ...
    GoogleCloudMlV1_ManualScalingIn: t.typedef = ...
    GoogleCloudMlV1_ManualScalingOut: t.typedef = ...
    GoogleCloudMlV1_AutomatedStoppingConfigIn: t.typedef = ...
    GoogleCloudMlV1_AutomatedStoppingConfigOut: t.typedef = ...
    GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfigIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfigOut: t.typedef = (
        ...
    )
    GoogleLongrunning_OperationIn: t.typedef = ...
    GoogleLongrunning_OperationOut: t.typedef = ...
    GoogleCloudMlV1_BuiltInAlgorithmOutputIn: t.typedef = ...
    GoogleCloudMlV1_BuiltInAlgorithmOutputOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpecOut: t.typedef = ...
    GoogleProtobuf_EmptyIn: t.typedef = ...
    GoogleProtobuf_EmptyOut: t.typedef = ...
    GoogleType_ExprIn: t.typedef = ...
    GoogleType_ExprOut: t.typedef = ...
    GoogleIamV1_SetIamPolicyRequestIn: t.typedef = ...
    GoogleIamV1_SetIamPolicyRequestOut: t.typedef = ...
    GoogleCloudMlV1_ReplicaConfigIn: t.typedef = ...
    GoogleCloudMlV1_ReplicaConfigOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_MetricSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_MetricSpecOut: t.typedef = ...
    GoogleCloudMlV1_ConfigIn: t.typedef = ...
    GoogleCloudMlV1_ConfigOut: t.typedef = ...
    GoogleIamV1_BindingIn: t.typedef = ...
    GoogleIamV1_BindingOut: t.typedef = ...
    GoogleCloudMlV1_CompleteTrialRequestIn: t.typedef = ...
    GoogleCloudMlV1_CompleteTrialRequestOut: t.typedef = ...
    GoogleCloudMlV1_JobIn: t.typedef = ...
    GoogleCloudMlV1_JobOut: t.typedef = ...
    GoogleCloudMlV1_EnvVarIn: t.typedef = ...
    GoogleCloudMlV1_EnvVarOut: t.typedef = ...
    GoogleCloudMlV1_TrialIn: t.typedef = ...
    GoogleCloudMlV1_TrialOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpecOut: t.typedef = ...
    GoogleCloudMlV1_HyperparameterSpecIn: t.typedef = ...
    GoogleCloudMlV1_HyperparameterSpecOut: t.typedef = ...
    GoogleCloudMlV1_OperationMetadataIn: t.typedef = ...
    GoogleCloudMlV1_OperationMetadataOut: t.typedef = ...
    GoogleCloudMlV1_AcceleratorConfigIn: t.typedef = ...
    GoogleCloudMlV1_AcceleratorConfigOut: t.typedef = ...
    GoogleCloudMlV1_MetricSpecIn: t.typedef = ...
    GoogleCloudMlV1_MetricSpecOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpecOut: t.typedef = ...
    GoogleCloudMlV1_CapabilityIn: t.typedef = ...
    GoogleCloudMlV1_CapabilityOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigOut: t.typedef = ...
    GoogleCloudMlV1_StudyIn: t.typedef = ...
    GoogleCloudMlV1_StudyOut: t.typedef = ...
    GoogleCloudMlV1_CancelJobRequestIn: t.typedef = ...
    GoogleCloudMlV1_CancelJobRequestOut: t.typedef = ...
    GoogleCloudMlV1_ContainerPortIn: t.typedef = ...
    GoogleCloudMlV1_ContainerPortOut: t.typedef = ...
    GoogleCloudMlV1_SampledShapleyAttributionIn: t.typedef = ...
    GoogleCloudMlV1_SampledShapleyAttributionOut: t.typedef = ...
    GoogleIamV1_AuditConfigIn: t.typedef = ...
    GoogleIamV1_AuditConfigOut: t.typedef = ...
    GoogleCloudMlV1_XraiAttributionIn: t.typedef = ...
    GoogleCloudMlV1_XraiAttributionOut: t.typedef = ...
    GoogleCloudMlV1_ExplainRequestIn: t.typedef = ...
    GoogleCloudMlV1_ExplainRequestOut: t.typedef = ...
    GoogleCloudMlV1_VersionIn: t.typedef = ...
    GoogleCloudMlV1_VersionOut: t.typedef = ...
    GoogleCloudMlV1_Trial_ParameterIn: t.typedef = ...
    GoogleCloudMlV1_Trial_ParameterOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpecIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpecOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1_RouteMapIn: t.typedef = ...
    GoogleCloudMlV1_RouteMapOut: t.typedef = ...
    GoogleCloudMlV1_PredictionOutputIn: t.typedef = ...
    GoogleCloudMlV1_PredictionOutputOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpecIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpecOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1_ContainerSpecIn: t.typedef = ...
    GoogleCloudMlV1_ContainerSpecOut: t.typedef = ...
    GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfigIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfigOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1_IntegratedGradientsAttributionIn: t.typedef = ...
    GoogleCloudMlV1_IntegratedGradientsAttributionOut: t.typedef = ...
    GoogleCloudMlV1_ListTrialsResponseIn: t.typedef = ...
    GoogleCloudMlV1_ListTrialsResponseOut: t.typedef = ...
    GoogleCloudMlV1_RequestLoggingConfigIn: t.typedef = ...
    GoogleCloudMlV1_RequestLoggingConfigOut: t.typedef = ...
    GoogleCloudMlV1_HyperparameterOutputIn: t.typedef = ...
    GoogleCloudMlV1_HyperparameterOutputOut: t.typedef = ...
    GoogleCloudMlV1_ListOptimalTrialsRequestIn: t.typedef = ...
    GoogleCloudMlV1_ListOptimalTrialsRequestOut: t.typedef = ...
    GoogleCloudMlV1_SetDefaultVersionRequestIn: t.typedef = ...
    GoogleCloudMlV1_SetDefaultVersionRequestOut: t.typedef = ...

class FuncList:
    projectsGetConfig: t.func = ...
    projectsPredict: t.func = ...
    projectsExplain: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsStudiesGet: t.func = ...
    projectsLocationsStudiesList: t.func = ...
    projectsLocationsStudiesCreate: t.func = ...
    projectsLocationsStudiesDelete: t.func = ...
    projectsLocationsStudiesTrialsListOptimalTrials: t.func = ...
    projectsLocationsStudiesTrialsAddMeasurement: t.func = ...
    projectsLocationsStudiesTrialsGet: t.func = ...
    projectsLocationsStudiesTrialsCreate: t.func = ...
    projectsLocationsStudiesTrialsStop: t.func = ...
    projectsLocationsStudiesTrialsSuggest: t.func = ...
    projectsLocationsStudiesTrialsList: t.func = ...
    projectsLocationsStudiesTrialsComplete: t.func = ...
    projectsLocationsStudiesTrialsDelete: t.func = ...
    projectsLocationsStudiesTrialsCheckEarlyStoppingState: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsModelsGetIamPolicy: t.func = ...
    projectsModelsDelete: t.func = ...
    projectsModelsPatch: t.func = ...
    projectsModelsSetIamPolicy: t.func = ...
    projectsModelsGet: t.func = ...
    projectsModelsList: t.func = ...
    projectsModelsCreate: t.func = ...
    projectsModelsTestIamPermissions: t.func = ...
    projectsModelsVersionsSetDefault: t.func = ...
    projectsModelsVersionsPatch: t.func = ...
    projectsModelsVersionsDelete: t.func = ...
    projectsModelsVersionsGet: t.func = ...
    projectsModelsVersionsList: t.func = ...
    projectsModelsVersionsCreate: t.func = ...
    projectsOperationsGet: t.func = ...
    projectsOperationsCancel: t.func = ...
    projectsOperationsList: t.func = ...
    projectsJobsCreate: t.func = ...
    projectsJobsList: t.func = ...
    projectsJobsTestIamPermissions: t.func = ...
    projectsJobsGetIamPolicy: t.func = ...
    projectsJobsGet: t.func = ...
    projectsJobsCancel: t.func = ...
    projectsJobsSetIamPolicy: t.func = ...
    projectsJobsPatch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_ml() -> Import: ...
