from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    NotificationSettingIn: t.typedef = ...
    NotificationSettingOut: t.typedef = ...

class FuncList:
    accountsGetNotificationSetting: t.func = ...
    accountsUpdateNotificationSetting: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_mybusinessnotifications() -> Import: ...
