from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    HourlyMetricsIn: t.typedef = ...
    HourlyMetricsOut: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    ListBusinessCallsInsightsResponseIn: t.typedef = ...
    ListBusinessCallsInsightsResponseOut: t.typedef = ...
    BusinessCallsSettingsIn: t.typedef = ...
    BusinessCallsSettingsOut: t.typedef = ...
    BusinessCallsInsightsIn: t.typedef = ...
    BusinessCallsInsightsOut: t.typedef = ...
    AggregateMetricsIn: t.typedef = ...
    AggregateMetricsOut: t.typedef = ...
    WeekDayMetricsIn: t.typedef = ...
    WeekDayMetricsOut: t.typedef = ...

class FuncList:
    locationsUpdateBusinesscallssettings: t.func = ...
    locationsGetBusinesscallssettings: t.func = ...
    locationsBusinesscallsinsightsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_mybusinessbusinesscalls() -> Import: ...
