from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TokeninfoIn: t.typedef = ...
    TokeninfoOut: t.typedef = ...
    UserinfoIn: t.typedef = ...
    UserinfoOut: t.typedef = ...

class FuncList:
    Tokeninfo: t.func = ...
    userinfoGet: t.func = ...
    userinfoV2MeGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_oauth2() -> Import: ...
