from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionCancellationDetailsIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionCancellationDetailsOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ExtendSubscriptionResponseIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ExtendSubscriptionResponseOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1UndoCancelSubscriptionRequestIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1UndoCancelSubscriptionRequestOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ListProductsResponseIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ListProductsResponseOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1FindEligiblePromotionsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1FindEligiblePromotionsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1PromotionIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1PromotionOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1UndoCancelSubscriptionResponseIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1UndoCancelSubscriptionResponseOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1GoogleOnePayloadIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1GoogleOnePayloadOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ProductIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ProductOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ProductPayloadIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ProductPayloadOut: t.typedef = ...
    GoogleTypeLocalizedTextIn: t.typedef = ...
    GoogleTypeLocalizedTextOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1FindEligiblePromotionsRequestIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1FindEligiblePromotionsRequestOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1EntitleSubscriptionResponseIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1EntitleSubscriptionResponseOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionPromotionSpecIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionPromotionSpecOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1LocationIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1LocationOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetailsIntroductoryPricingSpecIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetailsIntroductoryPricingSpecOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItemIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItemOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1AmountIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1AmountOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ExtendSubscriptionRequestIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ExtendSubscriptionRequestOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ServicePeriodIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ServicePeriodOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionResponseIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionResponseOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetailsIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetailsOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ListPromotionsResponseIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ListPromotionsResponseOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItemOneTimeRecurrenceDetailsIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItemOneTimeRecurrenceDetailsOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionUpgradeDowngradeDetailsIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionUpgradeDowngradeDetailsOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1YoutubePayloadIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1YoutubePayloadOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1DurationIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1DurationOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionRequestIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionRequestOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1SubscriptionOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1EntitleSubscriptionRequestIn: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1EntitleSubscriptionRequestOut: t.typedef = (
        ...
    )
    GoogleCloudPaymentsResellerSubscriptionV1ExtensionIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ExtensionOut: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ProductPriceConfigIn: t.typedef = ...
    GoogleCloudPaymentsResellerSubscriptionV1ProductPriceConfigOut: t.typedef = ...

class FuncList:
    partnersSubscriptionsEntitle: t.func = ...
    partnersSubscriptionsExtend: t.func = ...
    partnersSubscriptionsProvision: t.func = ...
    partnersSubscriptionsCreate: t.func = ...
    partnersSubscriptionsGet: t.func = ...
    partnersSubscriptionsUndoCancel: t.func = ...
    partnersSubscriptionsCancel: t.func = ...
    partnersProductsList: t.func = ...
    partnersPromotionsFindEligible: t.func = ...
    partnersPromotionsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_paymentsresellersubscription() -> Import: ...
