from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleIamV1BindingIn: t.typedef = ...
    GoogleIamV1BindingOut: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipIn: t.typedef = (
        ...
    )
    GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipOut: t.typedef = (
        ...
    )
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleTypeExprIn: t.typedef = ...
    GoogleTypeExprOut: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1TroubleshootIamPolicyRequestIn: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1TroubleshootIamPolicyRequestOut: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1BindingExplanationIn: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1BindingExplanationOut: t.typedef = ...
    GoogleIamV1PolicyIn: t.typedef = ...
    GoogleIamV1PolicyOut: t.typedef = ...
    GoogleIamV1AuditLogConfigIn: t.typedef = ...
    GoogleIamV1AuditLogConfigOut: t.typedef = ...
    GoogleIamV1AuditConfigIn: t.typedef = ...
    GoogleIamV1AuditConfigOut: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1TroubleshootIamPolicyResponseIn: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1TroubleshootIamPolicyResponseOut: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1AccessTupleIn: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1AccessTupleOut: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1ExplainedPolicyIn: t.typedef = ...
    GoogleCloudPolicytroubleshooterV1ExplainedPolicyOut: t.typedef = ...

class FuncList:
    iamTroubleshoot: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_policytroubleshooter() -> Import: ...
