from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudResourcesettingsV1SettingIn: t.typedef = ...
    GoogleCloudResourcesettingsV1SettingOut: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueStringMapIn: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueStringMapOut: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueIn: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueOut: t.typedef = ...
    GoogleCloudResourcesettingsV1SettingMetadataIn: t.typedef = ...
    GoogleCloudResourcesettingsV1SettingMetadataOut: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueEnumValueIn: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueEnumValueOut: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueStringSetIn: t.typedef = ...
    GoogleCloudResourcesettingsV1ValueStringSetOut: t.typedef = ...
    GoogleCloudResourcesettingsV1ListSettingsResponseIn: t.typedef = ...
    GoogleCloudResourcesettingsV1ListSettingsResponseOut: t.typedef = ...

class FuncList:
    organizationsSettingsPatch: t.func = ...
    organizationsSettingsList: t.func = ...
    organizationsSettingsGet: t.func = ...
    foldersSettingsGet: t.func = ...
    foldersSettingsList: t.func = ...
    foldersSettingsPatch: t.func = ...
    projectsSettingsPatch: t.func = ...
    projectsSettingsGet: t.func = ...
    projectsSettingsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_resourcesettings() -> Import: ...
