from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleAdsSearchads360V0Common_RealTimeBiddingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_RealTimeBiddingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionTrackingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionTrackingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_ListCustomColumnsResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_ListCustomColumnsResponseOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_ManualCpmIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_ManualCpmOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetRoasIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetRoasOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_KeywordViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_KeywordViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_GeoTargetTypeSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_GeoTargetTypeSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_GenderViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_GenderViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignCriterionIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignCriterionOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ProductGroupViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ProductGroupViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AgeRangeViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AgeRangeViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorDetailsIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorDetailsOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterionIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterionOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360ResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360ResponseOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetRestrictionIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetRestrictionOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_EnhancedCpcIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_EnhancedCpcOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorCodeIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorCodeOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_KeywordIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_KeywordOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_UserListInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_UserListInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_BiddingStrategyIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_BiddingStrategyOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_DeviceInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_DeviceInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_SegmentsIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_SegmentsOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterionLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterionLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_AgeRangeInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_AgeRangeInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360TextAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360TextAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_FloodlightSettingsIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_ConversionAction_FloodlightSettingsOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_Campaign_DynamicSearchAdsSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_DynamicSearchAdsSettingOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common_SearchAds360ExpandedDynamicSearchAdInfoIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common_SearchAds360ExpandedDynamicSearchAdInfoOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_Campaign_ShoppingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_ShoppingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorLocationIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorLocationOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_AttributionModelSettingsIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_ConversionAction_AttributionModelSettingsOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_AdGroupAudienceViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupAudienceViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_WebpageConditionInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_WebpageConditionInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupAdIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupAdOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_QuotaErrorDetailsIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_QuotaErrorDetailsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_LanguageInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_LanguageInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_MetricsIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_MetricsOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360RequestIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360RequestOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_SearchAds360FailureIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_SearchAds360FailureOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360ResponsiveSearchAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360ResponsiveSearchAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetSpendIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetSpendOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionActionIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionActionOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_SearchAds360ErrorIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_SearchAds360ErrorOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignBudgetIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignBudgetOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_CustomColumnHeaderIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_CustomColumnHeaderOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomerClientIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomerClientOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_MaximizeConversionValueIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_MaximizeConversionValueOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360FieldsResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360FieldsResponseOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetCpaIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetCpaOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_DynamicSearchAdsSearchTermViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_DynamicSearchAdsSearchTermViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_UserListIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_UserListOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_NetworkSettingsIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_NetworkSettingsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_GenderInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_GenderInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360FieldsRequestIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchSearchAds360FieldsRequestOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360ProductAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360ProductAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_SelectiveOptimizationIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_SelectiveOptimizationOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomerIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomerOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupAdLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupAdLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_ManualCpcIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_ManualCpcOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_WebpageViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_WebpageViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_LabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_LabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterion_QualityInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterion_QualityInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_PercentCpcIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_PercentCpcOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_TrackingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_TrackingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_ListingGroupInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_ListingGroupInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_LocationViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_LocationViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupOut: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchAds360RowIn: t.typedef = ...
    GoogleAdsSearchads360V0Services_SearchAds360RowOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_ValueSettingsIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_ValueSettingsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_KeywordInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_KeywordInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_OptimizationGoalSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_OptimizationGoalSettingOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common_TargetOutrankShareIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetOutrankShareOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_WebpageInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_WebpageInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomerManagerLinkIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomerManagerLinkOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360ExpandedTextAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_SearchAds360ExpandedTextAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_ValueIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_ValueOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupBidModifierIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupBidModifierOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_FrequencyCapEntryIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_FrequencyCapEntryOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetImpressionShareIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetImpressionShareOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorLocation_FieldPathElementIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorLocation_FieldPathElementOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_ManualCpaIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_ManualCpaOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_DoubleClickCampaignManagerSettingIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_DoubleClickCampaignManagerSettingOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common_LocationInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_LocationInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TextLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TextLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_MaximizeConversionsIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_MaximizeConversionsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_CustomParameterIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_CustomParameterOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetCpmIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_TargetCpmOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_SearchAds360FieldIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_SearchAds360FieldOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignAudienceViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CampaignAudienceViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common_LocationGroupInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common_LocationGroupInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomColumnIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_CustomColumnOut: t.typedef = ...

class FuncList:
    customersCustomColumnsList: t.func = ...
    customersCustomColumnsGet: t.func = ...
    customersSearchAds360Search: t.func = ...
    searchAds360FieldsGet: t.func = ...
    searchAds360FieldsSearch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_searchads360() -> Import: ...
