from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ListEndpointsResponseIn: t.typedef = ...
    ListEndpointsResponseOut: t.typedef = ...
    ResolveServiceResponseIn: t.typedef = ...
    ResolveServiceResponseOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    ServiceIn: t.typedef = ...
    ServiceOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ListServicesResponseIn: t.typedef = ...
    ListServicesResponseOut: t.typedef = ...
    ResolveServiceRequestIn: t.typedef = ...
    ResolveServiceRequestOut: t.typedef = ...
    EndpointIn: t.typedef = ...
    EndpointOut: t.typedef = ...
    NamespaceIn: t.typedef = ...
    NamespaceOut: t.typedef = ...
    GetPolicyOptionsIn: t.typedef = ...
    GetPolicyOptionsOut: t.typedef = ...
    ListNamespacesResponseIn: t.typedef = ...
    ListNamespacesResponseOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    GetIamPolicyRequestIn: t.typedef = ...
    GetIamPolicyRequestOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...

class FuncList:
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsNamespacesList: t.func = ...
    projectsLocationsNamespacesDelete: t.func = ...
    projectsLocationsNamespacesCreate: t.func = ...
    projectsLocationsNamespacesGetIamPolicy: t.func = ...
    projectsLocationsNamespacesGet: t.func = ...
    projectsLocationsNamespacesSetIamPolicy: t.func = ...
    projectsLocationsNamespacesPatch: t.func = ...
    projectsLocationsNamespacesTestIamPermissions: t.func = ...
    projectsLocationsNamespacesServicesTestIamPermissions: t.func = ...
    projectsLocationsNamespacesServicesList: t.func = ...
    projectsLocationsNamespacesServicesGetIamPolicy: t.func = ...
    projectsLocationsNamespacesServicesSetIamPolicy: t.func = ...
    projectsLocationsNamespacesServicesPatch: t.func = ...
    projectsLocationsNamespacesServicesCreate: t.func = ...
    projectsLocationsNamespacesServicesDelete: t.func = ...
    projectsLocationsNamespacesServicesResolve: t.func = ...
    projectsLocationsNamespacesServicesGet: t.func = ...
    projectsLocationsNamespacesServicesEndpointsDelete: t.func = ...
    projectsLocationsNamespacesServicesEndpointsPatch: t.func = ...
    projectsLocationsNamespacesServicesEndpointsGet: t.func = ...
    projectsLocationsNamespacesServicesEndpointsCreate: t.func = ...
    projectsLocationsNamespacesServicesEndpointsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_servicedirectory() -> Import: ...
