from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SiteVerificationWebResourceListResponseIn: t.typedef = ...
    SiteVerificationWebResourceListResponseOut: t.typedef = ...
    SiteVerificationWebResourceGettokenRequestIn: t.typedef = ...
    SiteVerificationWebResourceGettokenRequestOut: t.typedef = ...
    SiteVerificationWebResourceGettokenResponseIn: t.typedef = ...
    SiteVerificationWebResourceGettokenResponseOut: t.typedef = ...
    SiteVerificationWebResourceResourceIn: t.typedef = ...
    SiteVerificationWebResourceResourceOut: t.typedef = ...

class FuncList:
    webResourceInsert: t.func = ...
    webResourceList: t.func = ...
    webResourcePatch: t.func = ...
    webResourceGet: t.func = ...
    webResourceGetToken: t.func = ...
    webResourceUpdate: t.func = ...
    webResourceDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_siteVerification() -> Import: ...
