from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    RecognitionMetadataIn: t.typedef = ...
    RecognitionMetadataOut: t.typedef = ...
    ListPhraseSetResponseIn: t.typedef = ...
    ListPhraseSetResponseOut: t.typedef = ...
    TranscriptOutputConfigIn: t.typedef = ...
    TranscriptOutputConfigOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    RecognitionConfigIn: t.typedef = ...
    RecognitionConfigOut: t.typedef = ...
    PhraseIn: t.typedef = ...
    PhraseOut: t.typedef = ...
    SpeechRecognitionResultIn: t.typedef = ...
    SpeechRecognitionResultOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    SpeechContextIn: t.typedef = ...
    SpeechContextOut: t.typedef = ...
    SpeechRecognitionAlternativeIn: t.typedef = ...
    SpeechRecognitionAlternativeOut: t.typedef = ...
    LongRunningRecognizeRequestIn: t.typedef = ...
    LongRunningRecognizeRequestOut: t.typedef = ...
    ABNFGrammarIn: t.typedef = ...
    ABNFGrammarOut: t.typedef = ...
    WordInfoIn: t.typedef = ...
    WordInfoOut: t.typedef = ...
    LongRunningRecognizeMetadataIn: t.typedef = ...
    LongRunningRecognizeMetadataOut: t.typedef = ...
    RecognitionAudioIn: t.typedef = ...
    RecognitionAudioOut: t.typedef = ...
    CreatePhraseSetRequestIn: t.typedef = ...
    CreatePhraseSetRequestOut: t.typedef = ...
    SpeakerDiarizationConfigIn: t.typedef = ...
    SpeakerDiarizationConfigOut: t.typedef = ...
    RecognizeResponseIn: t.typedef = ...
    RecognizeResponseOut: t.typedef = ...
    RecognizeRequestIn: t.typedef = ...
    RecognizeRequestOut: t.typedef = ...
    CustomClassIn: t.typedef = ...
    CustomClassOut: t.typedef = ...
    PhraseSetIn: t.typedef = ...
    PhraseSetOut: t.typedef = ...
    CreateCustomClassRequestIn: t.typedef = ...
    CreateCustomClassRequestOut: t.typedef = ...
    LongRunningRecognizeResponseIn: t.typedef = ...
    LongRunningRecognizeResponseOut: t.typedef = ...
    SpeechAdaptationIn: t.typedef = ...
    SpeechAdaptationOut: t.typedef = ...
    SpeechAdaptationInfoIn: t.typedef = ...
    SpeechAdaptationInfoOut: t.typedef = ...
    ClassItemIn: t.typedef = ...
    ClassItemOut: t.typedef = ...
    ListCustomClassesResponseIn: t.typedef = ...
    ListCustomClassesResponseOut: t.typedef = ...

class FuncList:
    projectsLocationsCustomClassesDelete: t.func = ...
    projectsLocationsCustomClassesCreate: t.func = ...
    projectsLocationsCustomClassesGet: t.func = ...
    projectsLocationsCustomClassesPatch: t.func = ...
    projectsLocationsCustomClassesList: t.func = ...
    projectsLocationsPhraseSetsCreate: t.func = ...
    projectsLocationsPhraseSetsDelete: t.func = ...
    projectsLocationsPhraseSetsPatch: t.func = ...
    projectsLocationsPhraseSetsGet: t.func = ...
    projectsLocationsPhraseSetsList: t.func = ...
    speechRecognize: t.func = ...
    speechLongrunningrecognize: t.func = ...
    operationsGet: t.func = ...
    operationsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_speech() -> Import: ...
