from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TaskIn: t.typedef = ...
    TaskOut: t.typedef = ...
    TaskListsIn: t.typedef = ...
    TaskListsOut: t.typedef = ...
    TasksIn: t.typedef = ...
    TasksOut: t.typedef = ...
    TaskListIn: t.typedef = ...
    TaskListOut: t.typedef = ...

class FuncList:
    tasklistsUpdate: t.func = ...
    tasklistsInsert: t.func = ...
    tasklistsPatch: t.func = ...
    tasklistsDelete: t.func = ...
    tasklistsGet: t.func = ...
    tasklistsList: t.func = ...
    tasksPatch: t.func = ...
    tasksInsert: t.func = ...
    tasksGet: t.func = ...
    tasksClear: t.func = ...
    tasksDelete: t.func = ...
    tasksMove: t.func = ...
    tasksList: t.func = ...
    tasksUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_tasks() -> Import: ...
