from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ConnectorIn: t.typedef = ...
    ConnectorOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    SubnetIn: t.typedef = ...
    SubnetOut: t.typedef = ...
    OperationMetadataV1Alpha1In: t.typedef = ...
    OperationMetadataV1Alpha1Out: t.typedef = ...
    OperationMetadataV1Beta1In: t.typedef = ...
    OperationMetadataV1Beta1Out: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    ListConnectorsResponseIn: t.typedef = ...
    ListConnectorsResponseOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsConnectorsPatch: t.func = ...
    projectsLocationsConnectorsList: t.func = ...
    projectsLocationsConnectorsGet: t.func = ...
    projectsLocationsConnectorsCreate: t.func = ...
    projectsLocationsConnectorsDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_vpcaccess() -> Import: ...
