from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ListScanRunsResponseIn: t.typedef = ...
    ListScanRunsResponseOut: t.typedef = ...
    XssIn: t.typedef = ...
    XssOut: t.typedef = ...
    FindingIn: t.typedef = ...
    FindingOut: t.typedef = ...
    ScheduleIn: t.typedef = ...
    ScheduleOut: t.typedef = ...
    IapTestServiceAccountInfoIn: t.typedef = ...
    IapTestServiceAccountInfoOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    StopScanRunRequestIn: t.typedef = ...
    StopScanRunRequestOut: t.typedef = ...
    IapCredentialIn: t.typedef = ...
    IapCredentialOut: t.typedef = ...
    StartScanRunRequestIn: t.typedef = ...
    StartScanRunRequestOut: t.typedef = ...
    ScanConfigErrorIn: t.typedef = ...
    ScanConfigErrorOut: t.typedef = ...
    HeaderIn: t.typedef = ...
    HeaderOut: t.typedef = ...
    ScanRunErrorTraceIn: t.typedef = ...
    ScanRunErrorTraceOut: t.typedef = ...
    ListScanConfigsResponseIn: t.typedef = ...
    ListScanConfigsResponseOut: t.typedef = ...
    VulnerableHeadersIn: t.typedef = ...
    VulnerableHeadersOut: t.typedef = ...
    FindingTypeStatsIn: t.typedef = ...
    FindingTypeStatsOut: t.typedef = ...
    XxeIn: t.typedef = ...
    XxeOut: t.typedef = ...
    CrawledUrlIn: t.typedef = ...
    CrawledUrlOut: t.typedef = ...
    ListCrawledUrlsResponseIn: t.typedef = ...
    ListCrawledUrlsResponseOut: t.typedef = ...
    VulnerableParametersIn: t.typedef = ...
    VulnerableParametersOut: t.typedef = ...
    ScanRunWarningTraceIn: t.typedef = ...
    ScanRunWarningTraceOut: t.typedef = ...
    ListFindingsResponseIn: t.typedef = ...
    ListFindingsResponseOut: t.typedef = ...
    ViolatingResourceIn: t.typedef = ...
    ViolatingResourceOut: t.typedef = ...
    GoogleAccountIn: t.typedef = ...
    GoogleAccountOut: t.typedef = ...
    ScanRunIn: t.typedef = ...
    ScanRunOut: t.typedef = ...
    ScanConfigIn: t.typedef = ...
    ScanConfigOut: t.typedef = ...
    FormIn: t.typedef = ...
    FormOut: t.typedef = ...
    CustomAccountIn: t.typedef = ...
    CustomAccountOut: t.typedef = ...
    AuthenticationIn: t.typedef = ...
    AuthenticationOut: t.typedef = ...
    OutdatedLibraryIn: t.typedef = ...
    OutdatedLibraryOut: t.typedef = ...
    ListFindingTypeStatsResponseIn: t.typedef = ...
    ListFindingTypeStatsResponseOut: t.typedef = ...

class FuncList:
    projectsScanConfigsGet: t.func = ...
    projectsScanConfigsList: t.func = ...
    projectsScanConfigsDelete: t.func = ...
    projectsScanConfigsPatch: t.func = ...
    projectsScanConfigsCreate: t.func = ...
    projectsScanConfigsStart: t.func = ...
    projectsScanConfigsScanRunsList: t.func = ...
    projectsScanConfigsScanRunsStop: t.func = ...
    projectsScanConfigsScanRunsGet: t.func = ...
    projectsScanConfigsScanRunsFindingTypeStatsList: t.func = ...
    projectsScanConfigsScanRunsFindingsGet: t.func = ...
    projectsScanConfigsScanRunsFindingsList: t.func = ...
    projectsScanConfigsScanRunsCrawledUrlsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_websecurityscanner() -> Import: ...
