
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-01T14:54:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b84dae8fa736b2f6d57f828334c5558e5c92193",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
