
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T16:50:11+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "702cef4f8146a2c63c8265c9ef5731dc5dc07fa8",
 "version": "1.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
