# Generated by Django 4.2 on 2023-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
