
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-01T15:11:11+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5485cfd5094f8f756395e41de4bc34a7ec6f32ed",
 "version": "1.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
