
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T16:05:50+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "49d2eb811917bc7010ea3f170c9843f6e5619ebf",
 "version": "1.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
