
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T19:07:41+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f066ebc5b2cd2f45a8b15a562aa6d111928827a",
 "version": "1.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
