
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T12:31:40+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d424d3f0d7a6782d7b64f65e42930c08e764e87",
 "version": "2.14.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
