# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.5.dev4+gff4e001.d20230531'
__version_tuple__ = version_tuple = (0, 2, 5, 'dev4', 'gff4e001.d20230531')
