
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T20:16:05+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f4836b18977a8a26ae653239a5014195c80a4e0",
 "version": "2.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
