
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T17:26:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c439b7c4050b11b6141e94a94cdb56a359fb14e1",
 "version": "1.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
