import typing

import kubernetes.client

class StorageV1beta1Api:
    def __init__(self, api_client: typing.Optional[kubernetes.client.ApiClient] = ...) -> None:
        ...
    def get_api_resources(self) -> kubernetes.client.V1APIResourceList:
        ...
    def list_storage_class(self, *, include_uninitialized: typing.Optional[bool] = ..., pretty: typing.Optional[str] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes.client.V1beta1StorageClassList:
        ...
    def create_storage_class(self, body: kubernetes.client.V1beta1StorageClass, *, include_uninitialized: typing.Optional[bool] = ..., pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ...) -> kubernetes.client.V1beta1StorageClass:
        ...
    def delete_collection_storage_class(self, *, include_uninitialized: typing.Optional[bool] = ..., pretty: typing.Optional[str] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes.client.V1Status:
        ...
    def read_storage_class(self, name: str, *, pretty: typing.Optional[str] = ..., exact: typing.Optional[bool] = ..., export: typing.Optional[bool] = ...) -> kubernetes.client.V1beta1StorageClass:
        ...
    def replace_storage_class(self, name: str, body: kubernetes.client.V1beta1StorageClass, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ...) -> kubernetes.client.V1beta1StorageClass:
        ...
    def delete_storage_class(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes.client.V1Status:
        ...
    def patch_storage_class(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ...) -> kubernetes.client.V1beta1StorageClass:
        ...
    def list_volume_attachment(self, *, include_uninitialized: typing.Optional[bool] = ..., pretty: typing.Optional[str] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes.client.V1beta1VolumeAttachmentList:
        ...
    def create_volume_attachment(self, body: kubernetes.client.V1beta1VolumeAttachment, *, include_uninitialized: typing.Optional[bool] = ..., pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ...) -> kubernetes.client.V1beta1VolumeAttachment:
        ...
    def delete_collection_volume_attachment(self, *, include_uninitialized: typing.Optional[bool] = ..., pretty: typing.Optional[str] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes.client.V1Status:
        ...
    def read_volume_attachment(self, name: str, *, pretty: typing.Optional[str] = ..., exact: typing.Optional[bool] = ..., export: typing.Optional[bool] = ...) -> kubernetes.client.V1beta1VolumeAttachment:
        ...
    def replace_volume_attachment(self, name: str, body: kubernetes.client.V1beta1VolumeAttachment, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ...) -> kubernetes.client.V1beta1VolumeAttachment:
        ...
    def delete_volume_attachment(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes.client.V1Status:
        ...
    def patch_volume_attachment(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ...) -> kubernetes.client.V1beta1VolumeAttachment:
        ...
