
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T19:08:50+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "938cbec5ae4bd7134bbf2bb4f5842214ec55b459",
 "version": "1.17.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
