
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T16:31:16+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "d46a9c85648ef23568c133dd2c4b0433f842fc43",
 "version": "0.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
