# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nufarm_poc/nufarm_poc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bnufarm_poc/nufarm_poc.proto\x12\x0cnufarm_proto\"<\n\x07Request\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0e\n\x06\x62\x61se64\x18\x02 \x01(\t\x12\x0f\n\x07rawJson\x18\x03 \x01(\x08\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8f\x01\n\x10NuFarmController\x12:\n\x07\x45xtract\x12\x15.nufarm_proto.Request\x1a\x16.nufarm_proto.Response0\x01\x12?\n\x06Search\x12\x1b.nufarm_proto.SearchRequest\x1a\x16.nufarm_proto.Response0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nufarm_poc.nufarm_poc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=45
  _REQUEST._serialized_end=105
  _SEARCHREQUEST._serialized_start=107
  _SEARCHREQUEST._serialized_end=137
  _RESPONSE._serialized_start=139
  _RESPONSE._serialized_end=165
  _NUFARMCONTROLLER._serialized_start=168
  _NUFARMCONTROLLER._serialized_end=311
# @@protoc_insertion_point(module_scope)
