
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-28T19:41:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a47bd664057afd7b0e21a09fb4cc2f2a54ad0ad2",
 "version": "0.1.0-rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
