
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-23T10:11:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fc7877697ae8f19709da7eb4da4f9d3103e2b00",
 "version": "23.05.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
