
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-01T21:11:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "485f3fa6d8fd046f2d93c9a99a955817bd9e807f",
 "version": "4.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
