# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ..io_adaptors import io_adaptors_pb2 as io__adaptors_dot_io__adaptors__pb2


class IOAdaptorControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FTPInBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/FTPInBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.InBoundResponse.FromString,
                )
        self.FTPOutBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/FTPOutBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.OutBoundResponse.FromString,
                )
        self.FTPRemoveFile = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/FTPRemoveFile',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.FromString,
                )
        self.FTPDirectoryStructure = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/FTPDirectoryStructure',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.FromString,
                )
        self.S3InBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/S3InBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.InBoundResponse.FromString,
                )
        self.S3OutBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/S3OutBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.OutBoundResponse.FromString,
                )
        self.S3RemoveFile = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/S3RemoveFile',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.FromString,
                )
        self.S3DirectoryStructure = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/S3DirectoryStructure',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.FromString,
                )
        self.BlobInBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/BlobInBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.InBoundResponse.FromString,
                )
        self.BlobOutBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/BlobOutBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.BlobOutBoundResponse.FromString,
                )
        self.BlobRemoveFiles = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/BlobRemoveFiles',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.FromString,
                )
        self.BlobDirectoryStructure = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/BlobDirectoryStructure',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.FromString,
                )
        self.EmailInBound = channel.unary_stream(
                '/io_adaptors_APIs_proto.IOAdaptorController/EmailInBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.EmailInBoundRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.EmailInBoundResponse.FromString,
                )
        self.EmailOutBound = channel.unary_unary(
                '/io_adaptors_APIs_proto.IOAdaptorController/EmailOutBound',
                request_serializer=io__adaptors_dot_io__adaptors__pb2.EmailOutBoundRequest.SerializeToString,
                response_deserializer=io__adaptors_dot_io__adaptors__pb2.EmailOutBoundResponse.FromString,
                )


class IOAdaptorControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FTPInBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FTPOutBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FTPRemoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FTPDirectoryStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S3InBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S3OutBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S3RemoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S3DirectoryStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlobInBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlobOutBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlobRemoveFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlobDirectoryStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailInBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailOutBound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IOAdaptorControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FTPInBound': grpc.unary_stream_rpc_method_handler(
                    servicer.FTPInBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.InBoundResponse.SerializeToString,
            ),
            'FTPOutBound': grpc.unary_stream_rpc_method_handler(
                    servicer.FTPOutBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.OutBoundResponse.SerializeToString,
            ),
            'FTPRemoveFile': grpc.unary_stream_rpc_method_handler(
                    servicer.FTPRemoveFile,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.SerializeToString,
            ),
            'FTPDirectoryStructure': grpc.unary_stream_rpc_method_handler(
                    servicer.FTPDirectoryStructure,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.FTPRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.SerializeToString,
            ),
            'S3InBound': grpc.unary_stream_rpc_method_handler(
                    servicer.S3InBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.S3Request.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.InBoundResponse.SerializeToString,
            ),
            'S3OutBound': grpc.unary_stream_rpc_method_handler(
                    servicer.S3OutBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.S3Request.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.OutBoundResponse.SerializeToString,
            ),
            'S3RemoveFile': grpc.unary_stream_rpc_method_handler(
                    servicer.S3RemoveFile,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.S3Request.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.SerializeToString,
            ),
            'S3DirectoryStructure': grpc.unary_stream_rpc_method_handler(
                    servicer.S3DirectoryStructure,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.S3Request.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.SerializeToString,
            ),
            'BlobInBound': grpc.unary_stream_rpc_method_handler(
                    servicer.BlobInBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.InBoundResponse.SerializeToString,
            ),
            'BlobOutBound': grpc.unary_stream_rpc_method_handler(
                    servicer.BlobOutBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.BlobOutBoundResponse.SerializeToString,
            ),
            'BlobRemoveFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.BlobRemoveFiles,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.SerializeToString,
            ),
            'BlobDirectoryStructure': grpc.unary_stream_rpc_method_handler(
                    servicer.BlobDirectoryStructure,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.BlobRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.SerializeToString,
            ),
            'EmailInBound': grpc.unary_stream_rpc_method_handler(
                    servicer.EmailInBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.EmailInBoundRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.EmailInBoundResponse.SerializeToString,
            ),
            'EmailOutBound': grpc.unary_unary_rpc_method_handler(
                    servicer.EmailOutBound,
                    request_deserializer=io__adaptors_dot_io__adaptors__pb2.EmailOutBoundRequest.FromString,
                    response_serializer=io__adaptors_dot_io__adaptors__pb2.EmailOutBoundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io_adaptors_APIs_proto.IOAdaptorController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IOAdaptorController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FTPInBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/FTPInBound',
            io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.InBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FTPOutBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/FTPOutBound',
            io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.OutBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FTPRemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/FTPRemoveFile',
            io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FTPDirectoryStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/FTPDirectoryStructure',
            io__adaptors_dot_io__adaptors__pb2.FTPRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def S3InBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/S3InBound',
            io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.InBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def S3OutBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/S3OutBound',
            io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.OutBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def S3RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/S3RemoveFile',
            io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def S3DirectoryStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/S3DirectoryStructure',
            io__adaptors_dot_io__adaptors__pb2.S3Request.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlobInBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/BlobInBound',
            io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.InBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlobOutBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/BlobOutBound',
            io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.BlobOutBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlobRemoveFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/BlobRemoveFiles',
            io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.RemoveFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlobDirectoryStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/BlobDirectoryStructure',
            io__adaptors_dot_io__adaptors__pb2.BlobRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.DirectoryStructureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmailInBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/EmailInBound',
            io__adaptors_dot_io__adaptors__pb2.EmailInBoundRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.EmailInBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmailOutBound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io_adaptors_APIs_proto.IOAdaptorController/EmailOutBound',
            io__adaptors_dot_io__adaptors__pb2.EmailOutBoundRequest.SerializeToString,
            io__adaptors_dot_io__adaptors__pb2.EmailOutBoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
