import typing

import kubernetes.client

class StorageV1Api:
    def __init__(self, api_client: typing.Optional[kubernetes.client.ApiClient] = ...) -> None:
        ...
    def get_api_resources(self) -> kubernetes.client.V1APIResourceList:
        ...
    def list_storage_class(self, *, pretty: typing.Optional[str] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., include_uninitialized: typing.Optional[bool] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes.client.V1StorageClassList:
        ...
    def create_storage_class(self, body: kubernetes.client.V1StorageClass, *, pretty: typing.Optional[str] = ...) -> kubernetes.client.V1StorageClass:
        ...
    def delete_collection_storage_class(self, *, pretty: typing.Optional[str] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., include_uninitialized: typing.Optional[bool] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes.client.V1Status:
        ...
    def read_storage_class(self, name: str, *, pretty: typing.Optional[str] = ..., exact: typing.Optional[bool] = ..., export: typing.Optional[bool] = ...) -> kubernetes.client.V1StorageClass:
        ...
    def replace_storage_class(self, name: str, body: kubernetes.client.V1StorageClass, *, pretty: typing.Optional[str] = ...) -> kubernetes.client.V1StorageClass:
        ...
    def delete_storage_class(self, name: str, body: kubernetes.client.V1DeleteOptions, *, pretty: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes.client.V1Status:
        ...
    def patch_storage_class(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ...) -> kubernetes.client.V1StorageClass:
        ...
