
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T15:14:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7a83a2e561fca1de8fcbc0ff06bb8ae04937116",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
