
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-01T17:39:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "355ceed50500b4e9f4cac2143cd84e08ff962a64",
 "version": "0.16.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
