# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: force_packet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66orce_packet.proto\x12\x08protocol\"\'\n\x12\x46orcePacketRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"_\n\x13\x46orcePacketResponse\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\t\n\x01\x66\x18\x02 \x01(\x01\x12\r\n\x05index\x18\x03 \x01(\x04\x12\x11\n\tsys_ts_ns\x18\x04 \x01(\x04\x12\r\n\x05valid\x18\x05 \x01(\x08\"+\n\x19\x46orceSetFIFOStatusRequest\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x1b\n\x19\x46orceGetFIFOStatusRequest\"\x18\n\x16\x46orceResetCacheRequest\"2\n\x13\x46orceStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\"9\n\x1b\x46orceToggleRecordingRequest\x12\r\n\x05start\x18\x01 \x01(\x08\x12\x0b\n\x03tag\x18\x02 \x01(\t2\x94\x04\n\x12\x46orcePacketService\x12U\n\rSetFIFOStatus\x12#.protocol.ForceSetFIFOStatusRequest\x1a\x1d.protocol.ForceStatusResponse\"\x00\x12U\n\rGetFIFOStatus\x12#.protocol.ForceGetFIFOStatusRequest\x1a\x1d.protocol.ForceStatusResponse\"\x00\x12J\n\tGetPacket\x12\x1c.protocol.ForcePacketRequest\x1a\x1d.protocol.ForcePacketResponse\"\x00\x12R\n\x0fGetPacketStream\x12\x1c.protocol.ForcePacketRequest\x1a\x1d.protocol.ForcePacketResponse\"\x00\x30\x01\x12U\n\x10ResetPacketCache\x12 .protocol.ForceResetCacheRequest\x1a\x1d.protocol.ForceStatusResponse\"\x00\x12Y\n\x0fToggleRecording\x12%.protocol.ForceToggleRecordingRequest\x1a\x1d.protocol.ForceStatusResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'force_packet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FORCEPACKETREQUEST._serialized_start=32
  _FORCEPACKETREQUEST._serialized_end=71
  _FORCEPACKETRESPONSE._serialized_start=73
  _FORCEPACKETRESPONSE._serialized_end=168
  _FORCESETFIFOSTATUSREQUEST._serialized_start=170
  _FORCESETFIFOSTATUSREQUEST._serialized_end=213
  _FORCEGETFIFOSTATUSREQUEST._serialized_start=215
  _FORCEGETFIFOSTATUSREQUEST._serialized_end=242
  _FORCERESETCACHEREQUEST._serialized_start=244
  _FORCERESETCACHEREQUEST._serialized_end=268
  _FORCESTATUSRESPONSE._serialized_start=270
  _FORCESTATUSRESPONSE._serialized_end=320
  _FORCETOGGLERECORDINGREQUEST._serialized_start=322
  _FORCETOGGLERECORDINGREQUEST._serialized_end=379
  _FORCEPACKETSERVICE._serialized_start=382
  _FORCEPACKETSERVICE._serialized_end=914
# @@protoc_insertion_point(module_scope)
