
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T05:05:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f029d20b5157029129468105d2227035588163e",
 "version": "1.18.4.post0.dev80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
