# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta_operations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from seerep.pb import project_info_pb2 as project__info__pb2
from seerep.pb import project_infos_pb2 as project__infos__pb2
from seerep.pb import projectCreation_pb2 as projectCreation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15meta_operations.proto\x12\tseerep.pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12project_info.proto\x1a\x13project_infos.proto\x1a\x15projectCreation.proto2\x95\x01\n\x0eMetaOperations\x12\x43\n\rCreateProject\x12\x1a.seerep.pb.ProjectCreation\x1a\x16.seerep.pb.ProjectInfo\x12>\n\x0bGetProjects\x12\x16.google.protobuf.Empty\x1a\x17.seerep.pb.ProjectInfosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_operations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METAOPERATIONS._serialized_start=130
  _METAOPERATIONS._serialized_end=279
# @@protoc_insertion_point(module_scope)
