from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from wwtp_paas_main_bus_service.api.build_calc_dosage_config_api import BuildCalcDosageConfigApi
from wwtp_paas_main_bus_service.api.calculate_dosage_api import CalculateDosageApi
from wwtp_paas_main_bus_service.api.dosing_param_setting_api import DosingParamSettingApi
from wwtp_paas_main_bus_service.api.dosing_statistic_daily_api import DosingStatisticDailyApi
from wwtp_paas_main_bus_service.api.dosing_statistic_monthly_api import DosingStatisticMonthlyApi
from wwtp_paas_main_bus_service.api.general_data_api import GeneralDataApi
from wwtp_paas_main_bus_service.api.global_config_api import GlobalConfigApi
from wwtp_paas_main_bus_service.api.history_data_api import HistoryDataApi
from wwtp_paas_main_bus_service.api.import_export_api import ImportExportApi
from wwtp_paas_main_bus_service.api.intelligent_bus_config_api import IntelligentBusConfigApi
from wwtp_paas_main_bus_service.api.intelligent_denitrification_api import IntelligentDenitrificationApi
from wwtp_paas_main_bus_service.api.intelligent_mccr_api import IntelligentMccrApi
from wwtp_paas_main_bus_service.api.main_bus_config_api import MainBusConfigApi
from wwtp_paas_main_bus_service.api.pro_num_sim_lab_api import ProNumSimLabApi
from wwtp_paas_main_bus_service.api.system_setting_api import SystemSettingApi
from wwtp_paas_main_bus_service.api.toxicity_monitor_api import ToxicityMonitorApi
from wwtp_paas_main_bus_service.api.wq_analysis_api import WQAnalysisApi
