
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T14:29:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b036d02568c22b0cfc66777233f467ec4024589",
 "version": "0.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
