VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('31')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('44')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202305311044
version_date = '2023/05/31 10:44'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
