
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T16:26:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c5fe40afe63d65a1398f3598b14cb81688fc074",
 "version": "2.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
