
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-31T10:53:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "01e28ed7e6f6cfa1d3da689805ba1d972174b45f",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
