# Generated by Django 3.2.4 on 2022-11-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badi_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'permissions': (('can_bank_transaction', 'Manage تراکنش بانکی'),), 'verbose_name': 'Bank Transaction', 'verbose_name_plural': 'Bank Transaction'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_transaction', 'Manage تراکنش ها'),), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
