# Generated by Django 3.2.4 on 2023-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badi_wallet', '0002_auto_20221110_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='info',
            field=models.TextField(blank=True, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('1', 'Buy'), ('+', 'Charge'), ('-', 'Return')], max_length=2, verbose_name='Type'),
        ),
    ]
