# Generated by Django 3.2.4 on 2023-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badi_wallet', '0003_auto_20230329_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='info',
            field=models.TextField(blank=True, verbose_name='Info'),
        ),
    ]
