# Generated by Django 3.2.4 on 2023-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badi_wallet', '0004_alter_transaction_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'permissions': (('can_bank_transaction', 'مدیریت تراکنش بانکی'),), 'verbose_name': 'Bank Transaction', 'verbose_name_plural': 'Bank Transaction'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_transaction', 'مدیریت تراکنش ها'),), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Subject'),
        ),
    ]
