from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SiteSummaryResponseIn: t.typedef = ...
    SiteSummaryResponseOut: t.typedef = ...
    ViolatingSitesResponseIn: t.typedef = ...
    ViolatingSitesResponseOut: t.typedef = ...

class FuncList:
    violatingSitesList: t.func = ...
    sitesGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_abusiveexperiencereport() -> Import: ...
