from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    AmpUrlErrorIn: t.typedef = ...
    AmpUrlErrorOut: t.typedef = ...
    BatchGetAmpUrlsResponseIn: t.typedef = ...
    BatchGetAmpUrlsResponseOut: t.typedef = ...
    BatchGetAmpUrlsRequestIn: t.typedef = ...
    BatchGetAmpUrlsRequestOut: t.typedef = ...
    AmpUrlIn: t.typedef = ...
    AmpUrlOut: t.typedef = ...

class FuncList:
    ampUrlsBatchGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_acceleratedmobilepageurl() -> Import: ...
