from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponseIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponseOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadKMSSettingsIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadKMSSettingsOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationRemediationIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationRemediationOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadResourceSettingsIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadResourceSettingsOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadPartnerPermissionsIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadPartnerPermissionsOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ListWorkloadsResponseIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ListWorkloadsResponseOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesRequestIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesRequestOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1AcknowledgeViolationResponseIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1AcknowledgeViolationResponseOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ListViolationsResponseIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ListViolationsResponseOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsGcloudIn: t.typedef = (
        ...
    )
    GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsGcloudOut: t.typedef = (
        ...
    )
    GoogleCloudAssuredworkloadsV1CreateWorkloadOperationMetadataIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1CreateWorkloadOperationMetadataOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsConsoleIn: t.typedef = (
        ...
    )
    GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsConsoleOut: t.typedef = (
        ...
    )
    GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesResponseIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesResponseOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1AcknowledgeViolationRequestIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1AcknowledgeViolationRequestOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponseIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponseOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadComplianceStatusIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadComplianceStatusOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadResourceInfoIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1WorkloadResourceInfoOut: t.typedef = ...
    GoogleCloudAssuredworkloadsV1MutatePartnerPermissionsRequestIn: t.typedef = ...
    GoogleCloudAssuredworkloadsV1MutatePartnerPermissionsRequestOut: t.typedef = ...

class FuncList:
    organizationsLocationsWorkloadsRestrictAllowedResources: t.func = ...
    organizationsLocationsWorkloadsDelete: t.func = ...
    organizationsLocationsWorkloadsGet: t.func = ...
    organizationsLocationsWorkloadsPatch: t.func = ...
    organizationsLocationsWorkloadsCreate: t.func = ...
    organizationsLocationsWorkloadsMutatePartnerPermissions: t.func = ...
    organizationsLocationsWorkloadsList: t.func = ...
    organizationsLocationsWorkloadsViolationsList: t.func = ...
    organizationsLocationsWorkloadsViolationsAcknowledge: t.func = ...
    organizationsLocationsWorkloadsViolationsGet: t.func = ...
    organizationsLocationsOperationsGet: t.func = ...
    organizationsLocationsOperationsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_assuredworkloads() -> Import: ...
