from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ContainerHealthDetailsIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ContainerHealthDetailsOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponseAppConnectionDetailsIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponseAppConnectionDetailsOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionApplicationEndpointIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionApplicationEndpointOut: t.typedef = (
        ...
    )
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1RemoteAgentDetailsIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1RemoteAgentDetailsOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1NotificationConfigIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1NotificationConfigOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1ListAppConnectionsResponseIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1ListAppConnectionsResponseOut: t.typedef = ...
    GoogleIamV1TestIamPermissionsRequestIn: t.typedef = ...
    GoogleIamV1TestIamPermissionsRequestOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorOperationMetadataIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleIamV1AuditLogConfigIn: t.typedef = ...
    GoogleIamV1AuditLogConfigOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1alphaRemoteAgentDetailsIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1alphaRemoteAgentDetailsOut: t.typedef = ...
    CloudSecurityZerotrustApplinkAppConnectorProtoGatewayIn: t.typedef = ...
    CloudSecurityZerotrustApplinkAppConnectorProtoGatewayOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorInstanceConfigIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorInstanceConfigOut: t.typedef = ...
    GoogleCloudLocationLocationIn: t.typedef = ...
    GoogleCloudLocationLocationOut: t.typedef = ...
    GoogleIamV1BindingIn: t.typedef = ...
    GoogleIamV1BindingOut: t.typedef = ...
    GoogleCloudBeyondcorpConnectorsV1alphaConnectorOperationMetadataIn: t.typedef = ...
    GoogleCloudBeyondcorpConnectorsV1alphaConnectorOperationMetadataOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1alphaAppConnectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectionsV1alphaAppConnectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpPartnerservicesV1alphaPartnerServiceOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpPartnerservicesV1alphaPartnerServiceOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleIamV1PolicyIn: t.typedef = ...
    GoogleIamV1PolicyOut: t.typedef = ...
    Tunnelv1ProtoTunnelerInfoIn: t.typedef = ...
    Tunnelv1ProtoTunnelerInfoOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ResourceInfoIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ResourceInfoOut: t.typedef = ...
    CloudSecurityZerotrustApplinkLogagentProtoLogAgentDetailsIn: t.typedef = ...
    CloudSecurityZerotrustApplinkLogagentProtoLogAgentDetailsOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1alphaContainerHealthDetailsIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1alphaContainerHealthDetailsOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpConnectionsV1alphaConnectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpConnectionsV1alphaConnectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionGatewayIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionGatewayOut: t.typedef = ...
    CloudSecurityZerotrustApplinkAppConnectorProtoConnectorDetailsIn: t.typedef = ...
    CloudSecurityZerotrustApplinkAppConnectorProtoConnectorDetailsOut: t.typedef = ...
    AppGatewayOperationMetadataIn: t.typedef = ...
    AppGatewayOperationMetadataOut: t.typedef = ...
    GoogleCloudLocationListLocationsResponseIn: t.typedef = ...
    GoogleCloudLocationListLocationsResponseOut: t.typedef = ...
    AllocatedConnectionIn: t.typedef = ...
    AllocatedConnectionOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1alphaAppConnectorOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectorsV1alphaAppConnectorOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorOut: t.typedef = ...
    GoogleIamV1AuditConfigIn: t.typedef = ...
    GoogleIamV1AuditConfigOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ImageConfigIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ImageConfigOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1NotificationConfigCloudPubSubNotificationConfigIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectorsV1NotificationConfigCloudPubSubNotificationConfigOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppgatewaysV1alphaAppGatewayOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppgatewaysV1alphaAppGatewayOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpConnectorsV1alphaContainerHealthDetailsIn: t.typedef = ...
    GoogleCloudBeyondcorpConnectorsV1alphaContainerHealthDetailsOut: t.typedef = ...
    GoogleCloudBeyondcorpClientconnectorservicesV1alphaClientConnectorServiceOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpClientconnectorservicesV1alphaClientConnectorServiceOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpClientgatewaysV1alphaClientGatewayOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpClientgatewaysV1alphaClientGatewayOperationMetadataOut: t.typedef = (
        ...
    )
    Tunnelv1ProtoTunnelerErrorIn: t.typedef = ...
    Tunnelv1ProtoTunnelerErrorOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoServiceAccountIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoServiceAccountOut: t.typedef = (
        ...
    )
    CloudSecurityZerotrustApplinkAppConnectorProtoConnectionConfigIn: t.typedef = ...
    CloudSecurityZerotrustApplinkAppConnectorProtoConnectionConfigOut: t.typedef = ...
    GoogleLongrunningCancelOperationRequestIn: t.typedef = ...
    GoogleLongrunningCancelOperationRequestOut: t.typedef = ...
    ListAppGatewaysResponseIn: t.typedef = ...
    ListAppGatewaysResponseOut: t.typedef = ...
    GoogleIamV1TestIamPermissionsResponseIn: t.typedef = ...
    GoogleIamV1TestIamPermissionsResponseOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpAppconnectionsV1AppConnectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleIamV1SetIamPolicyRequestIn: t.typedef = ...
    GoogleIamV1SetIamPolicyRequestOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ReportStatusRequestIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ReportStatusRequestOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    GoogleCloudBeyondcorpConnectorsV1alphaRemoteAgentDetailsIn: t.typedef = ...
    GoogleCloudBeyondcorpConnectorsV1alphaRemoteAgentDetailsOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudBeyondcorpPartnerservicesV1mainPartnerServiceOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudBeyondcorpPartnerservicesV1mainPartnerServiceOperationMetadataOut: t.typedef = (
        ...
    )
    AppGatewayIn: t.typedef = ...
    AppGatewayOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ListAppConnectorsResponseIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ListAppConnectorsResponseOut: t.typedef = ...
    GoogleTypeExprIn: t.typedef = ...
    GoogleTypeExprOut: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ResolveInstanceConfigResponseIn: t.typedef = ...
    GoogleCloudBeyondcorpAppconnectorsV1ResolveInstanceConfigResponseOut: t.typedef = (
        ...
    )

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsAppConnectionsTestIamPermissions: t.func = ...
    projectsLocationsAppConnectionsDelete: t.func = ...
    projectsLocationsAppConnectionsPatch: t.func = ...
    projectsLocationsAppConnectionsList: t.func = ...
    projectsLocationsAppConnectionsResolve: t.func = ...
    projectsLocationsAppConnectionsCreate: t.func = ...
    projectsLocationsAppConnectionsGetIamPolicy: t.func = ...
    projectsLocationsAppConnectionsSetIamPolicy: t.func = ...
    projectsLocationsAppConnectionsGet: t.func = ...
    projectsLocationsClientGatewaysTestIamPermissions: t.func = ...
    projectsLocationsClientGatewaysGetIamPolicy: t.func = ...
    projectsLocationsClientGatewaysSetIamPolicy: t.func = ...
    projectsLocationsAppGatewaysGet: t.func = ...
    projectsLocationsAppGatewaysCreate: t.func = ...
    projectsLocationsAppGatewaysList: t.func = ...
    projectsLocationsAppGatewaysDelete: t.func = ...
    projectsLocationsAppGatewaysGetIamPolicy: t.func = ...
    projectsLocationsAppGatewaysSetIamPolicy: t.func = ...
    projectsLocationsAppGatewaysTestIamPermissions: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsClientConnectorServicesSetIamPolicy: t.func = ...
    projectsLocationsClientConnectorServicesTestIamPermissions: t.func = ...
    projectsLocationsClientConnectorServicesGetIamPolicy: t.func = ...
    projectsLocationsAppConnectorsReportStatus: t.func = ...
    projectsLocationsAppConnectorsDelete: t.func = ...
    projectsLocationsAppConnectorsSetIamPolicy: t.func = ...
    projectsLocationsAppConnectorsList: t.func = ...
    projectsLocationsAppConnectorsPatch: t.func = ...
    projectsLocationsAppConnectorsGet: t.func = ...
    projectsLocationsAppConnectorsGetIamPolicy: t.func = ...
    projectsLocationsAppConnectorsCreate: t.func = ...
    projectsLocationsAppConnectorsResolveInstanceConfig: t.func = ...
    projectsLocationsAppConnectorsTestIamPermissions: t.func = ...
    organizationsLocationsGlobalTenantsTestIamPermissions: t.func = ...
    organizationsLocationsGlobalTenantsSetIamPolicy: t.func = ...
    organizationsLocationsGlobalTenantsGetIamPolicy: t.func = ...
    organizationsLocationsGlobalTenantsProxyConfigsGetIamPolicy: t.func = ...
    organizationsLocationsGlobalTenantsProxyConfigsSetIamPolicy: t.func = ...
    organizationsLocationsGlobalTenantsProxyConfigsTestIamPermissions: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_beyondcorp() -> Import: ...
