from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SignatureIn: t.typedef = ...
    SignatureOut: t.typedef = ...
    AttestorIn: t.typedef = ...
    AttestorOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    ListAttestorsResponseIn: t.typedef = ...
    ListAttestorsResponseOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    ValidateAttestationOccurrenceRequestIn: t.typedef = ...
    ValidateAttestationOccurrenceRequestOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    UserOwnedGrafeasNoteIn: t.typedef = ...
    UserOwnedGrafeasNoteOut: t.typedef = ...
    ValidateAttestationOccurrenceResponseIn: t.typedef = ...
    ValidateAttestationOccurrenceResponseOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    AdmissionRuleIn: t.typedef = ...
    AdmissionRuleOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    IamPolicyIn: t.typedef = ...
    IamPolicyOut: t.typedef = ...
    AdmissionWhitelistPatternIn: t.typedef = ...
    AdmissionWhitelistPatternOut: t.typedef = ...
    JwtIn: t.typedef = ...
    JwtOut: t.typedef = ...
    PkixPublicKeyIn: t.typedef = ...
    PkixPublicKeyOut: t.typedef = ...
    AttestorPublicKeyIn: t.typedef = ...
    AttestorPublicKeyOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    AttestationOccurrenceIn: t.typedef = ...
    AttestationOccurrenceOut: t.typedef = ...

class FuncList:
    systempolicyGetPolicy: t.func = ...
    projectsGetPolicy: t.func = ...
    projectsUpdatePolicy: t.func = ...
    projectsPolicyGetIamPolicy: t.func = ...
    projectsPolicySetIamPolicy: t.func = ...
    projectsPolicyTestIamPermissions: t.func = ...
    projectsAttestorsValidateAttestationOccurrence: t.func = ...
    projectsAttestorsDelete: t.func = ...
    projectsAttestorsGet: t.func = ...
    projectsAttestorsCreate: t.func = ...
    projectsAttestorsSetIamPolicy: t.func = ...
    projectsAttestorsList: t.func = ...
    projectsAttestorsGetIamPolicy: t.func = ...
    projectsAttestorsTestIamPermissions: t.func = ...
    projectsAttestorsUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_binaryauthorization() -> Import: ...
