from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ChannelIn: t.typedef = ...
    ChannelOut: t.typedef = ...
    SourceIn: t.typedef = ...
    SourceOut: t.typedef = ...
    FeatureIdProtoIn: t.typedef = ...
    FeatureIdProtoOut: t.typedef = ...
    DivisionSearchResultIn: t.typedef = ...
    DivisionSearchResultOut: t.typedef = ...
    ElectionsQueryResponseIn: t.typedef = ...
    ElectionsQueryResponseOut: t.typedef = ...
    AdministrationRegionIn: t.typedef = ...
    AdministrationRegionOut: t.typedef = ...
    GeocodingSummaryIn: t.typedef = ...
    GeocodingSummaryOut: t.typedef = ...
    ElectionIn: t.typedef = ...
    ElectionOut: t.typedef = ...
    PrecinctIn: t.typedef = ...
    PrecinctOut: t.typedef = ...
    DivisionSearchResponseIn: t.typedef = ...
    DivisionSearchResponseOut: t.typedef = ...
    CandidateIn: t.typedef = ...
    CandidateOut: t.typedef = ...
    AdministrativeBodyIn: t.typedef = ...
    AdministrativeBodyOut: t.typedef = ...
    OfficeIn: t.typedef = ...
    OfficeOut: t.typedef = ...
    ContestIn: t.typedef = ...
    ContestOut: t.typedef = ...
    RepresentativeInfoDataIn: t.typedef = ...
    RepresentativeInfoDataOut: t.typedef = ...
    RepresentativeInfoResponseIn: t.typedef = ...
    RepresentativeInfoResponseOut: t.typedef = ...
    VoterInfoResponseIn: t.typedef = ...
    VoterInfoResponseOut: t.typedef = ...
    SimpleAddressTypeIn: t.typedef = ...
    SimpleAddressTypeOut: t.typedef = ...
    OfficialIn: t.typedef = ...
    OfficialOut: t.typedef = ...
    MessageSetIn: t.typedef = ...
    MessageSetOut: t.typedef = ...
    ElectoralDistrictIn: t.typedef = ...
    ElectoralDistrictOut: t.typedef = ...
    ElectionOfficialIn: t.typedef = ...
    ElectionOfficialOut: t.typedef = ...
    PollingLocationIn: t.typedef = ...
    PollingLocationOut: t.typedef = ...
    GeographicDivisionIn: t.typedef = ...
    GeographicDivisionOut: t.typedef = ...

class FuncList:
    divisionsSearch: t.func = ...
    electionsElectionQuery: t.func = ...
    electionsVoterInfoQuery: t.func = ...
    representativesRepresentativeInfoByAddress: t.func = ...
    representativesRepresentativeInfoByDivision: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_civicinfo() -> Import: ...
