from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ProfileIn: t.typedef = ...
    ProfileOut: t.typedef = ...
    CreateProfileRequestIn: t.typedef = ...
    CreateProfileRequestOut: t.typedef = ...
    DeploymentIn: t.typedef = ...
    DeploymentOut: t.typedef = ...

class FuncList:
    projectsProfilesCreateOffline: t.func = ...
    projectsProfilesPatch: t.func = ...
    projectsProfilesCreate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_cloudprofiler() -> Import: ...
