from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    DnsPeeringIn: t.typedef = ...
    DnsPeeringOut: t.typedef = ...
    InstanceIn: t.typedef = ...
    InstanceOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ListAvailableVersionsResponseIn: t.typedef = ...
    ListAvailableVersionsResponseOut: t.typedef = ...
    ListDnsPeeringsResponseIn: t.typedef = ...
    ListDnsPeeringsResponseOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    VersionIn: t.typedef = ...
    VersionOut: t.typedef = ...
    ListInstancesResponseIn: t.typedef = ...
    ListInstancesResponseOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    NetworkConfigIn: t.typedef = ...
    NetworkConfigOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    CryptoKeyConfigIn: t.typedef = ...
    CryptoKeyConfigOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    AcceleratorIn: t.typedef = ...
    AcceleratorOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    RestartInstanceRequestIn: t.typedef = ...
    RestartInstanceRequestOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    EventPublishConfigIn: t.typedef = ...
    EventPublishConfigOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsVersionsList: t.func = ...
    projectsLocationsInstancesGetIamPolicy: t.func = ...
    projectsLocationsInstancesRestart: t.func = ...
    projectsLocationsInstancesCreate: t.func = ...
    projectsLocationsInstancesDelete: t.func = ...
    projectsLocationsInstancesSetIamPolicy: t.func = ...
    projectsLocationsInstancesTestIamPermissions: t.func = ...
    projectsLocationsInstancesGet: t.func = ...
    projectsLocationsInstancesList: t.func = ...
    projectsLocationsInstancesPatch: t.func = ...
    projectsLocationsInstancesDnsPeeringsCreate: t.func = ...
    projectsLocationsInstancesDnsPeeringsDelete: t.func = ...
    projectsLocationsInstancesDnsPeeringsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_datafusion() -> Import: ...
