from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudDatalabelingV1beta1FeedbackThreadMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1FeedbackThreadMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1ImportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1ImportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1NormalizedBoundingPolyIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1NormalizedBoundingPolyOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelTextClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelTextClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1RequesterFeedbackMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1RequesterFeedbackMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1InputConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1InputConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelImageBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelImageBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ListInstructionsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListInstructionsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImageBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1HumanAnnotationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1HumanAnnotationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ClassificationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ClassificationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageBoundingPolyAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageBoundingPolyAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1OutputConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1OutputConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelTextEntityExtractionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelTextEntityExtractionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelVideoClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelVideoClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelVideoRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelVideoRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1CreateInstructionMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1CreateInstructionMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelImageBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1OperatorMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1OperatorMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationValueIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationValueOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelVideoObjectDetectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelVideoObjectDetectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageBoundingPolyOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageBoundingPolyOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelVideoClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelVideoClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ConfusionMatrixEntryIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ConfusionMatrixEntryOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageClassificationAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageClassificationAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListDataItemsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListDataItemsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ExportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ExportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1HumanAnnotationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1HumanAnnotationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoThumbnailIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoThumbnailOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SearchExampleComparisonsRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SearchExampleComparisonsRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImagePayloadIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImagePayloadOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoClassificationAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoClassificationAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationJobConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationJobConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1InstructionIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1InstructionOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SearchExampleComparisonsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SearchExampleComparisonsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1OutputConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1OutputConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1GenerateAnalysisReportOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1GenerateAnalysisReportOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1CreateInstructionMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1CreateInstructionMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelImagePolylineOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImagePolylineOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ImageClassificationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageClassificationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1DatasetIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1DatasetOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ResumeEvaluationJobRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ResumeEvaluationJobRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelImageOrientedBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageOrientedBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1CreateEvaluationJobRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateEvaluationJobRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1GcsFolderDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1GcsFolderDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListFeedbackThreadsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListFeedbackThreadsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListAnnotatedDatasetsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListAnnotatedDatasetsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1GcsSourceIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1GcsSourceOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PolylineIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PolylineOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelStatsIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelStatsOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelTextClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelTextClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageBoundingPolyOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageBoundingPolyOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelVideoEventOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelVideoEventOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelVideoObjectTrackingOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelVideoObjectTrackingOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1CreateDatasetRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateDatasetRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SegmentationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SegmentationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelVideoObjectDetectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelVideoObjectDetectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageSegmentationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageSegmentationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageBoundingPolyOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageBoundingPolyOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1TextPayloadIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextPayloadOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TimeSegmentIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TimeSegmentOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PrCurveIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PrCurveOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PolylineConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PolylineConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateInstructionMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateInstructionMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CsvInstructionIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CsvInstructionOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SearchEvaluationsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SearchEvaluationsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BoundingPolyIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BoundingPolyOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelImageOrientedBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelImageOrientedBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelVideoObjectTrackingOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelVideoObjectTrackingOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1EvaluationMetricsIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationMetricsOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelImageBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ObjectTrackingFrameIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ObjectTrackingFrameOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImageSegmentationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageSegmentationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ClassificationMetricsIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ClassificationMetricsOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelVideoClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelVideoClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelStatsIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelStatsOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelVideoEventOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelVideoEventOperationMetadataOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationJobIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationJobOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelVideoObjectDetectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelVideoObjectDetectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1OutputConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1OutputConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ExportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ExportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1RowIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1RowOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ExportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ExportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1FeedbackMessageIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1FeedbackMessageOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelImageSegmentationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelImageSegmentationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ImportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ImportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ImportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ConfidenceMetricsEntryIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ConfidenceMetricsEntryOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelTextClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelTextClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelVideoEventOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelVideoEventOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1ExportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1ExportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImagePolylineOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImagePolylineOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1GcsDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1GcsDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotatedDatasetMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotatedDatasetMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelVideoObjectDetectionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelVideoObjectDetectionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ObjectDetectionMetricsIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ObjectDetectionMetricsOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelImageBoundingPolyOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelImageBoundingPolyOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1ExportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ExportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListDatasetsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListDatasetsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1HumanAnnotationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1HumanAnnotationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationSpecSetIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationSpecSetOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ImportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1ImportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelImagePolylineOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImagePolylineOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1TextClassificationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextClassificationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoObjectTrackingAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoObjectTrackingAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateInstructionRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateInstructionRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1NormalizedVertexIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1NormalizedVertexOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelVideoClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelVideoClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ExportDataRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExportDataRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoEventAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoEventAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ImportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ImportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotatedDatasetIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotatedDatasetOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1GcsDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1GcsDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImportDataRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImportDataRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1GcsDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1GcsDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VertexIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VertexOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1GcsFolderDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1GcsFolderDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListEvaluationJobsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListEvaluationJobsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelImageSegmentationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelImageSegmentationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1GcsFolderDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1GcsFolderDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SentimentConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SentimentConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationJobAlertConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationJobAlertConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImageClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1AnnotationSpecIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationSpecOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextClassificationAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextClassificationAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateAnnotationSpecSetRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1CreateAnnotationSpecSetRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AttemptIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AttemptOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelTextRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelTextRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ImportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1ImportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BigQuerySourceIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BigQuerySourceOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1DataItemIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1DataItemOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListAnnotationSpecSetsResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListAnnotationSpecSetsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelImageClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelImageClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelVideoObjectTrackingOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelVideoObjectTrackingOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1HumanAnnotationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1HumanAnnotationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PdfInstructionIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PdfInstructionOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelTextEntityExtractionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelTextEntityExtractionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageOrientedBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1LabelImageOrientedBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1ObjectTrackingConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ObjectTrackingConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExampleIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExampleOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelTextClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelTextClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageClassificationOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageClassificationOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelTextEntityExtractionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelTextEntityExtractionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelVideoEventOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelVideoEventOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1CreateInstructionMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1CreateInstructionMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelTextEntityExtractionOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelTextEntityExtractionOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1ImportDataOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1ImportDataOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExampleComparisonIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExampleComparisonOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImagePolylineAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImagePolylineAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelImagePolylineOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelImagePolylineOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1OutputConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1OutputConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1ExportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1ExportDataOperationResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextEntityExtractionConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextEntityExtractionConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1NormalizedPolylineIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1NormalizedPolylineOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExportDataOperationResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ExportDataOperationResponseOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PauseEvaluationJobRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1PauseEvaluationJobRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BoundingPolyConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BoundingPolyConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EventConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EventConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1GcsDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1GcsDestinationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1EvaluationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListFeedbackMessagesResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListFeedbackMessagesResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListExamplesResponseIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ListExamplesResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelStatsIn: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelStatsOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationSpecSetConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1AnnotationSpecSetConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1alpha1LabelImageOrientedBoundingBoxOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1alpha1LabelImageOrientedBoundingBoxOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1beta1TextEntityExtractionAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1TextEntityExtractionAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ObjectDetectionConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ObjectDetectionConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageSegmentationAnnotationIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ImageSegmentationAnnotationOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoPayloadIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoPayloadOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1FeedbackThreadIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1FeedbackThreadOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SequentialSegmentIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1SequentialSegmentOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ConfusionMatrixIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1ConfusionMatrixOut: t.typedef = ...
    GoogleCloudDatalabelingV1p1alpha1LabelVideoObjectTrackingOperationMetadataIn: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p1alpha1LabelVideoObjectTrackingOperationMetadataOut: t.typedef = (
        ...
    )
    GoogleCloudDatalabelingV1p2alpha1LabelOperationMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelOperationMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelStatsIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1LabelStatsOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BoundingBoxEvaluationOptionsIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1BoundingBoxEvaluationOptionsOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImageRequestIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1LabelImageRequestOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1OperatorFeedbackMetadataIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1OperatorFeedbackMetadataOut: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoClassificationConfigIn: t.typedef = ...
    GoogleCloudDatalabelingV1beta1VideoClassificationConfigOut: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1GcsFolderDestinationIn: t.typedef = ...
    GoogleCloudDatalabelingV1p2alpha1GcsFolderDestinationOut: t.typedef = ...

class FuncList:
    projectsEvaluationJobsPause: t.func = ...
    projectsEvaluationJobsPatch: t.func = ...
    projectsEvaluationJobsGet: t.func = ...
    projectsEvaluationJobsList: t.func = ...
    projectsEvaluationJobsResume: t.func = ...
    projectsEvaluationJobsDelete: t.func = ...
    projectsEvaluationJobsCreate: t.func = ...
    projectsEvaluationsSearch: t.func = ...
    projectsOperationsCancel: t.func = ...
    projectsOperationsDelete: t.func = ...
    projectsOperationsList: t.func = ...
    projectsOperationsGet: t.func = ...
    projectsInstructionsDelete: t.func = ...
    projectsInstructionsCreate: t.func = ...
    projectsInstructionsList: t.func = ...
    projectsInstructionsGet: t.func = ...
    projectsDatasetsExportData: t.func = ...
    projectsDatasetsGet: t.func = ...
    projectsDatasetsCreate: t.func = ...
    projectsDatasetsDelete: t.func = ...
    projectsDatasetsList: t.func = ...
    projectsDatasetsImportData: t.func = ...
    projectsDatasetsDataItemsGet: t.func = ...
    projectsDatasetsDataItemsList: t.func = ...
    projectsDatasetsAnnotatedDatasetsList: t.func = ...
    projectsDatasetsAnnotatedDatasetsGet: t.func = ...
    projectsDatasetsAnnotatedDatasetsDelete: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsGet: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsDelete: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsList: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsFeedbackMessagesDelete: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsFeedbackMessagesList: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsFeedbackMessagesGet: t.func = ...
    projectsDatasetsAnnotatedDatasetsFeedbackThreadsFeedbackMessagesCreate: t.func = ...
    projectsDatasetsAnnotatedDatasetsExamplesGet: t.func = ...
    projectsDatasetsAnnotatedDatasetsExamplesList: t.func = ...
    projectsDatasetsAnnotatedDatasetsDataItemsList: t.func = ...
    projectsDatasetsAnnotatedDatasetsDataItemsGet: t.func = ...
    projectsDatasetsImageLabel: t.func = ...
    projectsDatasetsVideoLabel: t.func = ...
    projectsDatasetsEvaluationsGet: t.func = ...
    projectsDatasetsEvaluationsExampleComparisonsSearch: t.func = ...
    projectsDatasetsTextLabel: t.func = ...
    projectsAnnotationSpecSetsCreate: t.func = ...
    projectsAnnotationSpecSetsList: t.func = ...
    projectsAnnotationSpecSetsDelete: t.func = ...
    projectsAnnotationSpecSetsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_datalabeling() -> Import: ...
