from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    DeploymentIn: t.typedef = ...
    DeploymentOut: t.typedef = ...
    DeploymentsStopRequestIn: t.typedef = ...
    DeploymentsStopRequestOut: t.typedef = ...
    ResourcesListResponseIn: t.typedef = ...
    ResourcesListResponseOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    TestPermissionsResponseIn: t.typedef = ...
    TestPermissionsResponseOut: t.typedef = ...
    TypeIn: t.typedef = ...
    TypeOut: t.typedef = ...
    DeploymentUpdateIn: t.typedef = ...
    DeploymentUpdateOut: t.typedef = ...
    ImportFileIn: t.typedef = ...
    ImportFileOut: t.typedef = ...
    ManifestsListResponseIn: t.typedef = ...
    ManifestsListResponseOut: t.typedef = ...
    DeploymentLabelEntryIn: t.typedef = ...
    DeploymentLabelEntryOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    ManifestIn: t.typedef = ...
    ManifestOut: t.typedef = ...
    ResourceAccessControlIn: t.typedef = ...
    ResourceAccessControlOut: t.typedef = ...
    ResourceIn: t.typedef = ...
    ResourceOut: t.typedef = ...
    GlobalSetPolicyRequestIn: t.typedef = ...
    GlobalSetPolicyRequestOut: t.typedef = ...
    ConfigFileIn: t.typedef = ...
    ConfigFileOut: t.typedef = ...
    DeploymentUpdateLabelEntryIn: t.typedef = ...
    DeploymentUpdateLabelEntryOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    TypesListResponseIn: t.typedef = ...
    TypesListResponseOut: t.typedef = ...
    OperationsListResponseIn: t.typedef = ...
    OperationsListResponseOut: t.typedef = ...
    DeploymentsCancelPreviewRequestIn: t.typedef = ...
    DeploymentsCancelPreviewRequestOut: t.typedef = ...
    ResourceUpdateIn: t.typedef = ...
    ResourceUpdateOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    TargetConfigurationIn: t.typedef = ...
    TargetConfigurationOut: t.typedef = ...
    TestPermissionsRequestIn: t.typedef = ...
    TestPermissionsRequestOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    DeploymentsListResponseIn: t.typedef = ...
    DeploymentsListResponseOut: t.typedef = ...

class FuncList:
    operationsList: t.func = ...
    operationsGet: t.func = ...
    manifestsGet: t.func = ...
    manifestsList: t.func = ...
    deploymentsStop: t.func = ...
    deploymentsCancelPreview: t.func = ...
    deploymentsList: t.func = ...
    deploymentsUpdate: t.func = ...
    deploymentsSetIamPolicy: t.func = ...
    deploymentsTestIamPermissions: t.func = ...
    deploymentsDelete: t.func = ...
    deploymentsGet: t.func = ...
    deploymentsInsert: t.func = ...
    deploymentsPatch: t.func = ...
    deploymentsGetIamPolicy: t.func = ...
    typesList: t.func = ...
    resourcesGet: t.func = ...
    resourcesList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_deploymentmanager() -> Import: ...
