from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleAppsDriveLabelsV2UpdateLabelCopyModeRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2UpdateLabelCopyModeRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldPropertiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldPropertiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestCreateSelectionChoiceRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestCreateSelectionChoiceRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseCreateFieldResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseCreateFieldResponseOut: t.typedef = (
        ...
    )
    GoogleTypeColorIn: t.typedef = ...
    GoogleTypeColorOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelLockCapabilitiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelLockCapabilitiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseResponseIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseResponseOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldListOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldListOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2BadgeConfigIn: t.typedef = ...
    GoogleAppsDriveLabelsV2BadgeConfigOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldDateOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldDateOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDeleteFieldResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDeleteFieldResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateFieldPropertiesRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateFieldPropertiesRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDisableFieldResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDisableFieldResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateSelectionChoicePropertiesRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateSelectionChoicePropertiesRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2FieldDisplayHintsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldDisplayHintsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceDisplayHintsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceDisplayHintsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableSelectionChoiceRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableSelectionChoiceRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2LabelIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDisableSelectionChoiceResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDisableSelectionChoiceResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2IntegerLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2IntegerLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2PublishLabelRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2PublishLabelRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDeleteSelectionChoiceRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDeleteSelectionChoiceRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceSchemaCapabilitiesIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceSchemaCapabilitiesOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2LockStatusIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LockStatusOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDeleteFieldRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDeleteFieldRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2SelectionLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2SelectionLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2BatchUpdateLabelPermissionsRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2BatchUpdateLabelPermissionsRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSchemaCapabilitiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSchemaCapabilitiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateLabelPropertiesRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateLabelPropertiesRequestOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2LabelPermissionIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelPermissionOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelPropertiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelPropertiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLabelPermissionsResponseIn: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLabelPermissionsResponseOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateLabelPropertiesResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateLabelPropertiesResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2LifecycleIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LifecycleOut: t.typedef = ...
    GoogleAppsDriveLabelsV2BatchUpdateLabelPermissionsResponseIn: t.typedef = ...
    GoogleAppsDriveLabelsV2BatchUpdateLabelPermissionsResponseOut: t.typedef = ...
    GoogleAppsDriveLabelsV2UserInfoIn: t.typedef = ...
    GoogleAppsDriveLabelsV2UserInfoOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceAppliedCapabilitiesIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceAppliedCapabilitiesOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2BatchDeleteLabelPermissionsRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2BatchDeleteLabelPermissionsRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DisableLabelRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DisableLabelRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLabelLocksResponseIn: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLabelLocksResponseOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateFieldTypeResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateFieldTypeResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2ListLabelsResponseIn: t.typedef = ...
    GoogleAppsDriveLabelsV2ListLabelsResponseOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldUserOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldUserOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelAppliedLabelPolicyIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelAppliedLabelPolicyOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LifecycleDisabledPolicyIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LifecycleDisabledPolicyOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateSelectionChoicePropertiesResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateSelectionChoicePropertiesResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDeleteSelectionChoiceResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseDeleteSelectionChoiceResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2UserLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2UserLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestOut: t.typedef = ...
    GoogleTypeDateIn: t.typedef = ...
    GoogleTypeDateOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseEnableSelectionChoiceResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseEnableSelectionChoiceResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateFieldPropertiesResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseUpdateFieldPropertiesResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DateLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DateLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestCreateFieldRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestCreateFieldRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldTextOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldTextOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2UserCapabilitiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2UserCapabilitiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2EnableLabelRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2EnableLabelRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelDisplayHintsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelDisplayHintsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2TextLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2TextLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestEnableSelectionChoiceRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestEnableSelectionChoiceRequestOut: t.typedef = (
        ...
    )
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldAppliedCapabilitiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldAppliedCapabilitiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelAppliedCapabilitiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelAppliedCapabilitiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2WriteControlIn: t.typedef = ...
    GoogleAppsDriveLabelsV2WriteControlOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldLongTextOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldLongTextOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelLockIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelLockOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoiceOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelSchemaCapabilitiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelSchemaCapabilitiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldIntegerOptionsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldIntegerOptionsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeleteLabelPermissionRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeleteLabelPermissionRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestEnableFieldRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestEnableFieldRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LabelLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2LongTextLimitsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2LongTextLimitsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoicePropertiesIn: t.typedef = ...
    GoogleAppsDriveLabelsV2FieldSelectionOptionsChoicePropertiesOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseEnableFieldResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseEnableFieldResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2UpdateLabelPermissionRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2UpdateLabelPermissionRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseCreateSelectionChoiceResponseIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelResponseCreateSelectionChoiceResponseOut: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestRequestIn: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestRequestOut: t.typedef = ...
    GoogleAppsDriveLabelsV2BadgeColorsIn: t.typedef = ...
    GoogleAppsDriveLabelsV2BadgeColorsOut: t.typedef = ...
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateFieldTypeRequestIn: t.typedef = (
        ...
    )
    GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestUpdateFieldTypeRequestOut: t.typedef = (
        ...
    )

class FuncList:
    labelsDelete: t.func = ...
    labelsDelta: t.func = ...
    labelsDisable: t.func = ...
    labelsUpdateLabelCopyMode: t.func = ...
    labelsGet: t.func = ...
    labelsList: t.func = ...
    labelsPublish: t.func = ...
    labelsCreate: t.func = ...
    labelsEnable: t.func = ...
    labelsUpdatePermissions: t.func = ...
    labelsLocksList: t.func = ...
    labelsRevisionsUpdatePermissions: t.func = ...
    labelsRevisionsLocksList: t.func = ...
    labelsRevisionsPermissionsBatchUpdate: t.func = ...
    labelsRevisionsPermissionsDelete: t.func = ...
    labelsRevisionsPermissionsBatchDelete: t.func = ...
    labelsRevisionsPermissionsList: t.func = ...
    labelsRevisionsPermissionsCreate: t.func = ...
    labelsPermissionsCreate: t.func = ...
    labelsPermissionsList: t.func = ...
    labelsPermissionsBatchUpdate: t.func = ...
    labelsPermissionsDelete: t.func = ...
    labelsPermissionsBatchDelete: t.func = ...
    usersGetCapabilities: t.func = ...
    limitsGetLabel: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_drivelabels() -> Import: ...
