from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    RevertInstanceRequestIn: t.typedef = ...
    RevertInstanceRequestOut: t.typedef = ...
    ListBackupsResponseIn: t.typedef = ...
    ListBackupsResponseOut: t.typedef = ...
    NfsExportOptionsIn: t.typedef = ...
    NfsExportOptionsOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameterIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameterOut: t.typedef = (
        ...
    )
    TimeOfDayIn: t.typedef = ...
    TimeOfDayOut: t.typedef = ...
    UpdatePolicyIn: t.typedef = ...
    UpdatePolicyOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsOut: t.typedef = (
        ...
    )
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    DailyCycleIn: t.typedef = ...
    DailyCycleOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceScheduleIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceScheduleOut: t.typedef = (
        ...
    )
    WeeklyCycleIn: t.typedef = ...
    WeeklyCycleOut: t.typedef = ...
    ScheduleIn: t.typedef = ...
    ScheduleOut: t.typedef = ...
    BackupIn: t.typedef = ...
    BackupOut: t.typedef = ...
    ListSnapshotsResponseIn: t.typedef = ...
    ListSnapshotsResponseOut: t.typedef = ...
    MaintenanceWindowIn: t.typedef = ...
    MaintenanceWindowOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    MaintenancePolicyIn: t.typedef = ...
    MaintenancePolicyOut: t.typedef = ...
    SnapshotIn: t.typedef = ...
    SnapshotOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    NetworkConfigIn: t.typedef = ...
    NetworkConfigOut: t.typedef = ...
    DenyMaintenancePeriodIn: t.typedef = ...
    DenyMaintenancePeriodOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceOut: t.typedef = (
        ...
    )
    FileShareConfigIn: t.typedef = ...
    FileShareConfigOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityOut: t.typedef = (
        ...
    )
    ListInstancesResponseIn: t.typedef = ...
    ListInstancesResponseOut: t.typedef = ...
    InstanceIn: t.typedef = ...
    InstanceOut: t.typedef = ...
    RestoreInstanceRequestIn: t.typedef = ...
    RestoreInstanceRequestOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1InstanceIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1InstanceOut: t.typedef = ...

class FuncList:
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsBackupsList: t.func = ...
    projectsLocationsBackupsPatch: t.func = ...
    projectsLocationsBackupsGet: t.func = ...
    projectsLocationsBackupsDelete: t.func = ...
    projectsLocationsBackupsCreate: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsInstancesCreate: t.func = ...
    projectsLocationsInstancesRevert: t.func = ...
    projectsLocationsInstancesPatch: t.func = ...
    projectsLocationsInstancesGet: t.func = ...
    projectsLocationsInstancesList: t.func = ...
    projectsLocationsInstancesDelete: t.func = ...
    projectsLocationsInstancesRestore: t.func = ...
    projectsLocationsInstancesSnapshotsDelete: t.func = ...
    projectsLocationsInstancesSnapshotsCreate: t.func = ...
    projectsLocationsInstancesSnapshotsList: t.func = ...
    projectsLocationsInstancesSnapshotsPatch: t.func = ...
    projectsLocationsInstancesSnapshotsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_file() -> Import: ...
