from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ListDatabaseInstancesResponseIn: t.typedef = ...
    ListDatabaseInstancesResponseOut: t.typedef = ...
    UndeleteDatabaseInstanceRequestIn: t.typedef = ...
    UndeleteDatabaseInstanceRequestOut: t.typedef = ...
    DisableDatabaseInstanceRequestIn: t.typedef = ...
    DisableDatabaseInstanceRequestOut: t.typedef = ...
    ReenableDatabaseInstanceRequestIn: t.typedef = ...
    ReenableDatabaseInstanceRequestOut: t.typedef = ...
    DatabaseInstanceIn: t.typedef = ...
    DatabaseInstanceOut: t.typedef = ...

class FuncList:
    projectsLocationsInstancesGet: t.func = ...
    projectsLocationsInstancesCreate: t.func = ...
    projectsLocationsInstancesList: t.func = ...
    projectsLocationsInstancesDisable: t.func = ...
    projectsLocationsInstancesReenable: t.func = ...
    projectsLocationsInstancesUndelete: t.func = ...
    projectsLocationsInstancesDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_firebasedatabase() -> Import: ...
