from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GroupsIn: t.typedef = ...
    GroupsOut: t.typedef = ...

class FuncList:
    archiveInsert: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_groupsmigration() -> Import: ...
