from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GroupsIn: t.typedef = ...
    GroupsOut: t.typedef = ...

class FuncList:
    groupsPatch: t.func = ...
    groupsGet: t.func = ...
    groupsUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_groupssettings() -> Import: ...
