from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SignJwtResponseIn: t.typedef = ...
    SignJwtResponseOut: t.typedef = ...
    SignBlobResponseIn: t.typedef = ...
    SignBlobResponseOut: t.typedef = ...
    GenerateIdTokenResponseIn: t.typedef = ...
    GenerateIdTokenResponseOut: t.typedef = ...
    SignBlobRequestIn: t.typedef = ...
    SignBlobRequestOut: t.typedef = ...
    SignJwtRequestIn: t.typedef = ...
    SignJwtRequestOut: t.typedef = ...
    GenerateAccessTokenRequestIn: t.typedef = ...
    GenerateAccessTokenRequestOut: t.typedef = ...
    GenerateIdTokenRequestIn: t.typedef = ...
    GenerateIdTokenRequestOut: t.typedef = ...
    GenerateAccessTokenResponseIn: t.typedef = ...
    GenerateAccessTokenResponseOut: t.typedef = ...

class FuncList:
    projectsServiceAccountsGenerateAccessToken: t.func = ...
    projectsServiceAccountsSignJwt: t.func = ...
    projectsServiceAccountsGenerateIdToken: t.func = ...
    projectsServiceAccountsSignBlob: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_iamcredentials() -> Import: ...
