from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1AggregatorInfoIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1AggregatorInfoOut: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponseIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponseOut: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponseIn: t.typedef = (
        ...
    )
    GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponseOut: t.typedef = (
        ...
    )
    GoogleAdsHomeservicesLocalservicesV1PhoneLeadIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1PhoneLeadOut: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1BookingLeadIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1BookingLeadOut: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1MessageLeadIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1MessageLeadOut: t.typedef = ...
    GoogleTypeTimeZoneIn: t.typedef = ...
    GoogleTypeTimeZoneOut: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1DetailedLeadReportIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1DetailedLeadReportOut: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1AccountReportIn: t.typedef = ...
    GoogleAdsHomeservicesLocalservicesV1AccountReportOut: t.typedef = ...

class FuncList:
    detailedLeadReportsSearch: t.func = ...
    accountReportsSearch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_localservices() -> Import: ...
