from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityOut: t.typedef = ...
    UpdatePolicyIn: t.typedef = ...
    UpdatePolicyOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameterIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameterOut: t.typedef = (
        ...
    )
    DenyMaintenancePeriodIn: t.typedef = ...
    DenyMaintenancePeriodOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceOut: t.typedef = (
        ...
    )
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    UpdateParametersRequestIn: t.typedef = ...
    UpdateParametersRequestOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ApplyParametersRequestIn: t.typedef = ...
    ApplyParametersRequestOut: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    WeeklyMaintenanceWindowIn: t.typedef = ...
    WeeklyMaintenanceWindowOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    NodeIn: t.typedef = ...
    NodeOut: t.typedef = ...
    RescheduleMaintenanceRequestIn: t.typedef = ...
    RescheduleMaintenanceRequestOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityOut: t.typedef = (
        ...
    )
    WeeklyCycleIn: t.typedef = ...
    WeeklyCycleOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataOut: t.typedef = ...
    GoogleCloudMemcacheV1LocationMetadataIn: t.typedef = ...
    GoogleCloudMemcacheV1LocationMetadataOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsOut: t.typedef = (
        ...
    )
    GoogleCloudMemcacheV1MaintenancePolicyIn: t.typedef = ...
    GoogleCloudMemcacheV1MaintenancePolicyOut: t.typedef = ...
    GoogleCloudMemcacheV1OperationMetadataIn: t.typedef = ...
    GoogleCloudMemcacheV1OperationMetadataOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1InstanceIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1InstanceOut: t.typedef = ...
    MaintenanceWindowIn: t.typedef = ...
    MaintenanceWindowOut: t.typedef = ...
    ScheduleIn: t.typedef = ...
    ScheduleOut: t.typedef = ...
    MaintenanceScheduleIn: t.typedef = ...
    MaintenanceScheduleOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceScheduleIn: t.typedef = (
        ...
    )
    GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceScheduleOut: t.typedef = (
        ...
    )
    TimeOfDayIn: t.typedef = ...
    TimeOfDayOut: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataIn: t.typedef = ...
    GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataOut: t.typedef = ...
    InstanceIn: t.typedef = ...
    InstanceOut: t.typedef = ...
    GoogleCloudMemcacheV1ZoneMetadataIn: t.typedef = ...
    GoogleCloudMemcacheV1ZoneMetadataOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    DailyCycleIn: t.typedef = ...
    DailyCycleOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    ZoneMetadataIn: t.typedef = ...
    ZoneMetadataOut: t.typedef = ...
    InstanceMessageIn: t.typedef = ...
    InstanceMessageOut: t.typedef = ...
    ListInstancesResponseIn: t.typedef = ...
    ListInstancesResponseOut: t.typedef = ...
    MaintenancePolicyIn: t.typedef = ...
    MaintenancePolicyOut: t.typedef = ...
    NodeConfigIn: t.typedef = ...
    NodeConfigOut: t.typedef = ...
    MemcacheParametersIn: t.typedef = ...
    MemcacheParametersOut: t.typedef = ...
    LocationMetadataIn: t.typedef = ...
    LocationMetadataOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsInstancesPatch: t.func = ...
    projectsLocationsInstancesDelete: t.func = ...
    projectsLocationsInstancesList: t.func = ...
    projectsLocationsInstancesApplyParameters: t.func = ...
    projectsLocationsInstancesGet: t.func = ...
    projectsLocationsInstancesRescheduleMaintenance: t.func = ...
    projectsLocationsInstancesUpdateParameters: t.func = ...
    projectsLocationsInstancesCreate: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_memcache() -> Import: ...
