from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    WaitForVoiceOfMerchantIn: t.typedef = ...
    WaitForVoiceOfMerchantOut: t.typedef = ...
    VerifyIn: t.typedef = ...
    VerifyOut: t.typedef = ...
    ServiceBusinessContextIn: t.typedef = ...
    ServiceBusinessContextOut: t.typedef = ...
    VerifyLocationRequestIn: t.typedef = ...
    VerifyLocationRequestOut: t.typedef = ...
    EmailVerificationDataIn: t.typedef = ...
    EmailVerificationDataOut: t.typedef = ...
    GenerateVerificationTokenRequestIn: t.typedef = ...
    GenerateVerificationTokenRequestOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    AddressVerificationDataIn: t.typedef = ...
    AddressVerificationDataOut: t.typedef = ...
    FetchVerificationOptionsResponseIn: t.typedef = ...
    FetchVerificationOptionsResponseOut: t.typedef = ...
    GenerateVerificationTokenResponseIn: t.typedef = ...
    GenerateVerificationTokenResponseOut: t.typedef = ...
    ComplyWithGuidelinesIn: t.typedef = ...
    ComplyWithGuidelinesOut: t.typedef = ...
    CompleteVerificationResponseIn: t.typedef = ...
    CompleteVerificationResponseOut: t.typedef = ...
    VoiceOfMerchantStateIn: t.typedef = ...
    VoiceOfMerchantStateOut: t.typedef = ...
    VerificationIn: t.typedef = ...
    VerificationOut: t.typedef = ...
    CompleteVerificationRequestIn: t.typedef = ...
    CompleteVerificationRequestOut: t.typedef = ...
    ListVerificationsResponseIn: t.typedef = ...
    ListVerificationsResponseOut: t.typedef = ...
    VerifyLocationResponseIn: t.typedef = ...
    VerifyLocationResponseOut: t.typedef = ...
    ResolveOwnershipConflictIn: t.typedef = ...
    ResolveOwnershipConflictOut: t.typedef = ...
    VerificationOptionIn: t.typedef = ...
    VerificationOptionOut: t.typedef = ...
    VerificationTokenIn: t.typedef = ...
    VerificationTokenOut: t.typedef = ...
    PostalAddressIn: t.typedef = ...
    PostalAddressOut: t.typedef = ...
    FetchVerificationOptionsRequestIn: t.typedef = ...
    FetchVerificationOptionsRequestOut: t.typedef = ...

class FuncList:
    locationsGetVoiceOfMerchantState: t.func = ...
    locationsFetchVerificationOptions: t.func = ...
    locationsVerify: t.func = ...
    locationsVerificationsComplete: t.func = ...
    locationsVerificationsList: t.func = ...
    verificationTokensGenerate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_mybusinessverifications() -> Import: ...
