from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValuesIn: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValuesOut: t.typedef = ...
    GoogleCloudOrgpolicyV2ConstraintIn: t.typedef = ...
    GoogleCloudOrgpolicyV2ConstraintOut: t.typedef = ...
    GoogleCloudOrgpolicyV2AlternatePolicySpecIn: t.typedef = ...
    GoogleCloudOrgpolicyV2AlternatePolicySpecOut: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicyIn: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicyOut: t.typedef = ...
    GoogleCloudOrgpolicyV2CustomConstraintIn: t.typedef = ...
    GoogleCloudOrgpolicyV2CustomConstraintOut: t.typedef = ...
    GoogleCloudOrgpolicyV2ConstraintListConstraintIn: t.typedef = ...
    GoogleCloudOrgpolicyV2ConstraintListConstraintOut: t.typedef = ...
    GoogleCloudOrgpolicyV2ListCustomConstraintsResponseIn: t.typedef = ...
    GoogleCloudOrgpolicyV2ListCustomConstraintsResponseOut: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicySpecPolicyRuleIn: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicySpecPolicyRuleOut: t.typedef = ...
    GoogleTypeExprIn: t.typedef = ...
    GoogleTypeExprOut: t.typedef = ...
    GoogleCloudOrgpolicyV2ListPoliciesResponseIn: t.typedef = ...
    GoogleCloudOrgpolicyV2ListPoliciesResponseOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudOrgpolicyV2ConstraintBooleanConstraintIn: t.typedef = ...
    GoogleCloudOrgpolicyV2ConstraintBooleanConstraintOut: t.typedef = ...
    GoogleCloudOrgpolicyV2ListConstraintsResponseIn: t.typedef = ...
    GoogleCloudOrgpolicyV2ListConstraintsResponseOut: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicySpecIn: t.typedef = ...
    GoogleCloudOrgpolicyV2PolicySpecOut: t.typedef = ...

class FuncList:
    projectsConstraintsList: t.func = ...
    projectsPoliciesList: t.func = ...
    projectsPoliciesCreate: t.func = ...
    projectsPoliciesDelete: t.func = ...
    projectsPoliciesGetEffectivePolicy: t.func = ...
    projectsPoliciesGet: t.func = ...
    projectsPoliciesPatch: t.func = ...
    organizationsConstraintsList: t.func = ...
    organizationsCustomConstraintsCreate: t.func = ...
    organizationsCustomConstraintsList: t.func = ...
    organizationsCustomConstraintsGet: t.func = ...
    organizationsCustomConstraintsPatch: t.func = ...
    organizationsCustomConstraintsDelete: t.func = ...
    organizationsPoliciesPatch: t.func = ...
    organizationsPoliciesList: t.func = ...
    organizationsPoliciesGetEffectivePolicy: t.func = ...
    organizationsPoliciesGet: t.func = ...
    organizationsPoliciesCreate: t.func = ...
    organizationsPoliciesDelete: t.func = ...
    foldersPoliciesCreate: t.func = ...
    foldersPoliciesGet: t.func = ...
    foldersPoliciesList: t.func = ...
    foldersPoliciesDelete: t.func = ...
    foldersPoliciesPatch: t.func = ...
    foldersPoliciesGetEffectivePolicy: t.func = ...
    foldersConstraintsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_orgpolicy() -> Import: ...
