from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    LoginProfileIn: t.typedef = ...
    LoginProfileOut: t.typedef = ...
    ImportSshPublicKeyResponseIn: t.typedef = ...
    ImportSshPublicKeyResponseOut: t.typedef = ...
    SshPublicKeyIn: t.typedef = ...
    SshPublicKeyOut: t.typedef = ...
    PosixAccountIn: t.typedef = ...
    PosixAccountOut: t.typedef = ...

class FuncList:
    usersImportSshPublicKey: t.func = ...
    usersGetLoginProfile: t.func = ...
    usersProjectsDelete: t.func = ...
    usersSshPublicKeysGet: t.func = ...
    usersSshPublicKeysPatch: t.func = ...
    usersSshPublicKeysCreate: t.func = ...
    usersSshPublicKeysDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_oslogin() -> Import: ...
