from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    CustomAppIn: t.typedef = ...
    CustomAppOut: t.typedef = ...
    OrganizationIn: t.typedef = ...
    OrganizationOut: t.typedef = ...

class FuncList:
    accountsCustomAppsCreate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_playcustomapp() -> Import: ...
