from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1PrivatePasswordLeakVerificationIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1PrivatePasswordLeakVerificationOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataGatewayInfoIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataGatewayInfoOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ScoreMetricsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ScoreMetricsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupMembershipIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RelatedAccountGroupMembershipOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionSubstituteActionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionSubstituteActionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RiskAnalysisIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RiskAnalysisOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallPolicyAssessmentIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallPolicyAssessmentOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1MetricsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1MetricsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionSetHeaderActionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionSetHeaderActionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentBehavioralTrustVerdictIn: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentBehavioralTrustVerdictOut: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1AndroidKeySettingsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AndroidKeySettingsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallPolicyIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallPolicyOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AppleDeveloperIdIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AppleDeveloperIdOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ScoreDistributionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ScoreDistributionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionAllowActionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionAllowActionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionEventIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionEventOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AssessmentIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AssessmentOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1KeyIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1KeyOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentStolenInstrumentVerdictIn: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentStolenInstrumentVerdictOut: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentCardTestingVerdictIn: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentCardTestingVerdictOut: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1WebKeySettingsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1WebKeySettingsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListRelatedAccountGroupsResponseIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListRelatedAccountGroupsResponseOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentRequestIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentRequestOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataItemIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataItemOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1SearchRelatedAccountGroupMembershipsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1SearchRelatedAccountGroupMembershipsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1TransactionDataUserIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataUserOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TokenPropertiesIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TokenPropertiesOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1WafSettingsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1WafSettingsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionRedirectActionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionRedirectActionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListKeysResponseIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListKeysResponseOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FraudPreventionAssessmentOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AccountDefenderAssessmentIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AccountDefenderAssessmentOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1SearchRelatedAccountGroupMembershipsRequestIn: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1SearchRelatedAccountGroupMembershipsRequestOut: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1TestingOptionsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TestingOptionsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionBlockActionIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1FirewallActionBlockActionOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentResponseIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AnnotateAssessmentResponseOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RetrieveLegacySecretKeyResponseIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1RetrieveLegacySecretKeyResponseOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1IOSKeySettingsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1IOSKeySettingsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1EndpointVerificationInfoIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1EndpointVerificationInfoOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListFirewallPoliciesResponseIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListFirewallPoliciesResponseOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ChallengeMetricsIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ChallengeMetricsOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AccountVerificationInfoIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1AccountVerificationInfoOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1ListRelatedAccountGroupMembershipsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1ListRelatedAccountGroupMembershipsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudRecaptchaenterpriseV1MigrateKeyRequestIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1MigrateKeyRequestOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataAddressIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1TransactionDataAddressOut: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1EventIn: t.typedef = ...
    GoogleCloudRecaptchaenterpriseV1EventOut: t.typedef = ...

class FuncList:
    projectsAssessmentsAnnotate: t.func = ...
    projectsAssessmentsCreate: t.func = ...
    projectsRelatedaccountgroupsList: t.func = ...
    projectsRelatedaccountgroupsMembershipsList: t.func = ...
    projectsFirewallpoliciesCreate: t.func = ...
    projectsFirewallpoliciesDelete: t.func = ...
    projectsFirewallpoliciesPatch: t.func = ...
    projectsFirewallpoliciesList: t.func = ...
    projectsFirewallpoliciesGet: t.func = ...
    projectsKeysPatch: t.func = ...
    projectsKeysDelete: t.func = ...
    projectsKeysCreate: t.func = ...
    projectsKeysRetrieveLegacySecretKey: t.func = ...
    projectsKeysList: t.func = ...
    projectsKeysGet: t.func = ...
    projectsKeysMigrate: t.func = ...
    projectsKeysGetMetrics: t.func = ...
    projectsRelatedaccountgroupmembershipsSearch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_recaptchaenterprise() -> Import: ...
