from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaRejoinCatalogMetadataIn: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaRejoinCatalogMetadataOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1FeatureMapIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1FeatureMapOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRangeIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRangeOut: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1alphaTuningMetadataIn: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaTuningMetadataOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ListCatalogItemsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ListCatalogItemsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1FeatureMapStringListIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1FeatureMapStringListOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurgeUserEventsRequestIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurgeUserEventsRequestOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserEventInlineSourceIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserEventInlineSourceOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsMetadataIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsMetadataOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1FeatureMapFloatListIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1FeatureMapFloatListOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductDetailIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductDetailOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPriceIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPriceOut: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1ImportCatalogItemsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportCatalogItemsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CreatePredictionApiKeyRegistrationRequestIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1CreatePredictionApiKeyRegistrationRequestOut: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1ImportErrorsConfigIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportErrorsConfigOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1BigQuerySourceIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1BigQuerySourceOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportUserEventsRequestIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportUserEventsRequestOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PredictRequestIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PredictRequestOut: t.typedef = ...
    GoogleApiHttpBodyIn: t.typedef = ...
    GoogleApiHttpBodyOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurgeUserEventsMetadataIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurgeUserEventsMetadataOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogItemIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogItemOut: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaRejoinCatalogResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaRejoinCatalogResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductEventDetailIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductEventDetailOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImageIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImageOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogInlineSourceIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogInlineSourceOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportCatalogItemsRequestIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportCatalogItemsRequestOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserInfoIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserInfoOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserEventIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserEventOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfigIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfigOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportUserEventsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportUserEventsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1EventDetailIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1EventDetailOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PredictResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PredictResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserEventImportSummaryIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1UserEventImportSummaryOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchyIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchyOut: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1ListCatalogsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ListCatalogsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurgeUserEventsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurgeUserEventsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResultIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResultOut: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1PurchaseTransactionIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PurchaseTransactionOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1InputConfigIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1InputConfigOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportMetadataIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ImportMetadataOut: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaTuningResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1alphaTuningResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ListPredictionApiKeyRegistrationsResponseIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1ListPredictionApiKeyRegistrationsResponseOut: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1GcsSourceIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1GcsSourceOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ListUserEventsResponseIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ListUserEventsResponseOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductCatalogItemIn: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1ProductCatalogItemOut: t.typedef = ...
    GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistrationIn: t.typedef = (
        ...
    )
    GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistrationOut: t.typedef = (
        ...
    )

class FuncList:
    projectsLocationsCatalogsPatch: t.func = ...
    projectsLocationsCatalogsList: t.func = ...
    projectsLocationsCatalogsEventStoresPlacementsPredict: t.func = ...
    projectsLocationsCatalogsEventStoresOperationsList: t.func = ...
    projectsLocationsCatalogsEventStoresOperationsGet: t.func = ...
    projectsLocationsCatalogsEventStoresUserEventsList: t.func = ...
    projectsLocationsCatalogsEventStoresUserEventsCollect: t.func = ...
    projectsLocationsCatalogsEventStoresUserEventsRejoin: t.func = ...
    projectsLocationsCatalogsEventStoresUserEventsWrite: t.func = ...
    projectsLocationsCatalogsEventStoresUserEventsImport: t.func = ...
    projectsLocationsCatalogsEventStoresUserEventsPurge: t.func = ...
    projectsLocationsCatalogsEventStoresPredictionApiKeyRegistrationsDelete: t.func = (
        ...
    )
    projectsLocationsCatalogsEventStoresPredictionApiKeyRegistrationsCreate: t.func = (
        ...
    )
    projectsLocationsCatalogsEventStoresPredictionApiKeyRegistrationsList: t.func = ...
    projectsLocationsCatalogsOperationsGet: t.func = ...
    projectsLocationsCatalogsOperationsList: t.func = ...
    projectsLocationsCatalogsCatalogItemsGet: t.func = ...
    projectsLocationsCatalogsCatalogItemsImport: t.func = ...
    projectsLocationsCatalogsCatalogItemsList: t.func = ...
    projectsLocationsCatalogsCatalogItemsDelete: t.func = ...
    projectsLocationsCatalogsCatalogItemsCreate: t.func = ...
    projectsLocationsCatalogsCatalogItemsPatch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_recommendationengine() -> Import: ...
