from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntrySetIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntrySetOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindFullHashesResponseIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindFullHashesResponseOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindFullHashesRequestIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindFullHashesRequestOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatListDescriptorIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatListDescriptorOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatHitThreatSourceIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatHitThreatSourceOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatHitUserInfoIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatHitUserInfoOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntryMetadataMetadataEntryIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntryMetadataMetadataEntryOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntryIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntryOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequestConstraintsIn: t.typedef = (
        ...
    )
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequestConstraintsOut: t.typedef = (
        ...
    )
    GoogleSecuritySafebrowsingV4ThreatEntryMetadataIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatEntryMetadataOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4RawIndicesIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4RawIndicesOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseListUpdateResponseIn: t.typedef = (
        ...
    )
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseListUpdateResponseOut: t.typedef = (
        ...
    )
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesResponseOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatMatchIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatMatchOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ChecksumIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ChecksumOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequestIn: t.typedef = (
        ...
    )
    GoogleSecuritySafebrowsingV4FetchThreatListUpdatesRequestListUpdateRequestOut: t.typedef = (
        ...
    )
    GoogleSecuritySafebrowsingV4RiceDeltaEncodingIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4RiceDeltaEncodingOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ClientInfoIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ClientInfoOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4RawHashesIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4RawHashesOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatInfoIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatInfoOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatHitIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ThreatHitOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindThreatMatchesResponseIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindThreatMatchesResponseOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindThreatMatchesRequestIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4FindThreatMatchesRequestOut: t.typedef = ...
    GoogleSecuritySafebrowsingV4ListThreatListsResponseIn: t.typedef = ...
    GoogleSecuritySafebrowsingV4ListThreatListsResponseOut: t.typedef = ...

class FuncList:
    threatListUpdatesFetch: t.func = ...
    threatMatchesFind: t.func = ...
    encodedUpdatesGet: t.func = ...
    encodedFullHashesGet: t.func = ...
    fullHashesFind: t.func = ...
    threatHitsCreate: t.func = ...
    threatListsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_safebrowsing() -> Import: ...
