from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    UrlInspectionResultIn: t.typedef = ...
    UrlInspectionResultOut: t.typedef = ...
    WmxSitemapContentIn: t.typedef = ...
    WmxSitemapContentOut: t.typedef = ...
    MobileFriendlyIssueIn: t.typedef = ...
    MobileFriendlyIssueOut: t.typedef = ...
    AmpInspectionResultIn: t.typedef = ...
    AmpInspectionResultOut: t.typedef = ...
    RunMobileFriendlyTestRequestIn: t.typedef = ...
    RunMobileFriendlyTestRequestOut: t.typedef = ...
    BlockedResourceIn: t.typedef = ...
    BlockedResourceOut: t.typedef = ...
    ItemIn: t.typedef = ...
    ItemOut: t.typedef = ...
    MobileUsabilityIssueIn: t.typedef = ...
    MobileUsabilityIssueOut: t.typedef = ...
    DetectedItemsIn: t.typedef = ...
    DetectedItemsOut: t.typedef = ...
    InspectUrlIndexResponseIn: t.typedef = ...
    InspectUrlIndexResponseOut: t.typedef = ...
    ApiDimensionFilterGroupIn: t.typedef = ...
    ApiDimensionFilterGroupOut: t.typedef = ...
    AmpIssueIn: t.typedef = ...
    AmpIssueOut: t.typedef = ...
    SitemapsListResponseIn: t.typedef = ...
    SitemapsListResponseOut: t.typedef = ...
    ImageIn: t.typedef = ...
    ImageOut: t.typedef = ...
    RunMobileFriendlyTestResponseIn: t.typedef = ...
    RunMobileFriendlyTestResponseOut: t.typedef = ...
    ApiDataRowIn: t.typedef = ...
    ApiDataRowOut: t.typedef = ...
    RichResultsInspectionResultIn: t.typedef = ...
    RichResultsInspectionResultOut: t.typedef = ...
    SearchAnalyticsQueryRequestIn: t.typedef = ...
    SearchAnalyticsQueryRequestOut: t.typedef = ...
    MobileUsabilityInspectionResultIn: t.typedef = ...
    MobileUsabilityInspectionResultOut: t.typedef = ...
    WmxSitemapIn: t.typedef = ...
    WmxSitemapOut: t.typedef = ...
    SitesListResponseIn: t.typedef = ...
    SitesListResponseOut: t.typedef = ...
    WmxSiteIn: t.typedef = ...
    WmxSiteOut: t.typedef = ...
    ApiDimensionFilterIn: t.typedef = ...
    ApiDimensionFilterOut: t.typedef = ...
    InspectUrlIndexRequestIn: t.typedef = ...
    InspectUrlIndexRequestOut: t.typedef = ...
    ResourceIssueIn: t.typedef = ...
    ResourceIssueOut: t.typedef = ...
    IndexStatusInspectionResultIn: t.typedef = ...
    IndexStatusInspectionResultOut: t.typedef = ...
    TestStatusIn: t.typedef = ...
    TestStatusOut: t.typedef = ...
    RichResultsIssueIn: t.typedef = ...
    RichResultsIssueOut: t.typedef = ...
    SearchAnalyticsQueryResponseIn: t.typedef = ...
    SearchAnalyticsQueryResponseOut: t.typedef = ...

class FuncList:
    searchanalyticsQuery: t.func = ...
    sitemapsDelete: t.func = ...
    sitemapsSubmit: t.func = ...
    sitemapsGet: t.func = ...
    sitemapsList: t.func = ...
    urlInspectionIndexInspect: t.func = ...
    urlTestingToolsMobileFriendlyTestRun: t.func = ...
    sitesList: t.func = ...
    sitesGet: t.func = ...
    sitesAdd: t.func = ...
    sitesDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_searchconsole() -> Import: ...
