from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleIdentityStsV1ExchangeTokenResponseIn: t.typedef = ...
    GoogleIdentityStsV1ExchangeTokenResponseOut: t.typedef = ...
    GoogleIdentityStsV1ExchangeOauthTokenResponseIn: t.typedef = ...
    GoogleIdentityStsV1ExchangeOauthTokenResponseOut: t.typedef = ...
    GoogleIdentityStsV1betaAccessBoundaryIn: t.typedef = ...
    GoogleIdentityStsV1betaAccessBoundaryOut: t.typedef = ...
    GoogleIdentityStsV1IntrospectTokenRequestIn: t.typedef = ...
    GoogleIdentityStsV1IntrospectTokenRequestOut: t.typedef = ...
    GoogleIdentityStsV1IntrospectTokenResponseIn: t.typedef = ...
    GoogleIdentityStsV1IntrospectTokenResponseOut: t.typedef = ...
    GoogleIdentityStsV1ExchangeOauthTokenRequestIn: t.typedef = ...
    GoogleIdentityStsV1ExchangeOauthTokenRequestOut: t.typedef = ...
    GoogleIamV1BindingIn: t.typedef = ...
    GoogleIamV1BindingOut: t.typedef = ...
    GoogleIdentityStsV1betaAccessBoundaryRuleIn: t.typedef = ...
    GoogleIdentityStsV1betaAccessBoundaryRuleOut: t.typedef = ...
    GoogleIdentityStsV1AccessBoundaryIn: t.typedef = ...
    GoogleIdentityStsV1AccessBoundaryOut: t.typedef = ...
    GoogleIdentityStsV1betaOptionsIn: t.typedef = ...
    GoogleIdentityStsV1betaOptionsOut: t.typedef = ...
    GoogleIdentityStsV1AccessBoundaryRuleIn: t.typedef = ...
    GoogleIdentityStsV1AccessBoundaryRuleOut: t.typedef = ...
    GoogleIdentityStsV1OptionsIn: t.typedef = ...
    GoogleIdentityStsV1OptionsOut: t.typedef = ...
    GoogleTypeExprIn: t.typedef = ...
    GoogleTypeExprOut: t.typedef = ...
    GoogleIdentityStsV1ExchangeTokenRequestIn: t.typedef = ...
    GoogleIdentityStsV1ExchangeTokenRequestOut: t.typedef = ...

class FuncList:
    v1Token: t.func = ...
    v1Oauthtoken: t.func = ...
    v1Introspect: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_sts() -> Import: ...
