from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    SynthesizeLongAudioMetadataIn: t.typedef = ...
    SynthesizeLongAudioMetadataOut: t.typedef = ...
    VoiceSelectionParamsIn: t.typedef = ...
    VoiceSelectionParamsOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    ListVoicesResponseIn: t.typedef = ...
    ListVoicesResponseOut: t.typedef = ...
    CustomVoiceParamsIn: t.typedef = ...
    CustomVoiceParamsOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    SynthesisInputIn: t.typedef = ...
    SynthesisInputOut: t.typedef = ...
    VoiceIn: t.typedef = ...
    VoiceOut: t.typedef = ...
    SynthesizeLongAudioRequestIn: t.typedef = ...
    SynthesizeLongAudioRequestOut: t.typedef = ...
    GoogleCloudTexttospeechV1SynthesizeLongAudioMetadataIn: t.typedef = ...
    GoogleCloudTexttospeechV1SynthesizeLongAudioMetadataOut: t.typedef = ...
    SynthesizeSpeechResponseIn: t.typedef = ...
    SynthesizeSpeechResponseOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    AudioConfigIn: t.typedef = ...
    AudioConfigOut: t.typedef = ...
    SynthesizeSpeechRequestIn: t.typedef = ...
    SynthesizeSpeechRequestOut: t.typedef = ...

class FuncList:
    textSynthesize: t.func = ...
    operationsCancel: t.func = ...
    operationsDelete: t.func = ...
    projectsLocationsSynthesizeLongAudio: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    voicesList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_texttospeech() -> Import: ...
