from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleRE2In: t.typedef = ...
    GoogleRE2Out: t.typedef = ...
    PipeIn: t.typedef = ...
    PipeOut: t.typedef = ...
    StaticListenerIn: t.typedef = ...
    StaticListenerOut: t.typedef = ...
    RegexMatcherIn: t.typedef = ...
    RegexMatcherOut: t.typedef = ...
    DynamicRouteConfigIn: t.typedef = ...
    DynamicRouteConfigOut: t.typedef = ...
    NodeIn: t.typedef = ...
    NodeOut: t.typedef = ...
    DynamicListenerStateIn: t.typedef = ...
    DynamicListenerStateOut: t.typedef = ...
    BuildVersionIn: t.typedef = ...
    BuildVersionOut: t.typedef = ...
    SemanticVersionIn: t.typedef = ...
    SemanticVersionOut: t.typedef = ...
    StaticClusterIn: t.typedef = ...
    StaticClusterOut: t.typedef = ...
    ListMatcherIn: t.typedef = ...
    ListMatcherOut: t.typedef = ...
    ExtensionIn: t.typedef = ...
    ExtensionOut: t.typedef = ...
    SocketAddressIn: t.typedef = ...
    SocketAddressOut: t.typedef = ...
    ClientStatusResponseIn: t.typedef = ...
    ClientStatusResponseOut: t.typedef = ...
    RoutesConfigDumpIn: t.typedef = ...
    RoutesConfigDumpOut: t.typedef = ...
    ClientConfigIn: t.typedef = ...
    ClientConfigOut: t.typedef = ...
    NodeMatcherIn: t.typedef = ...
    NodeMatcherOut: t.typedef = ...
    PerXdsConfigIn: t.typedef = ...
    PerXdsConfigOut: t.typedef = ...
    DynamicListenerIn: t.typedef = ...
    DynamicListenerOut: t.typedef = ...
    StructMatcherIn: t.typedef = ...
    StructMatcherOut: t.typedef = ...
    StaticRouteConfigIn: t.typedef = ...
    StaticRouteConfigOut: t.typedef = ...
    ValueMatcherIn: t.typedef = ...
    ValueMatcherOut: t.typedef = ...
    ListenersConfigDumpIn: t.typedef = ...
    ListenersConfigDumpOut: t.typedef = ...
    UpdateFailureStateIn: t.typedef = ...
    UpdateFailureStateOut: t.typedef = ...
    ScopedRoutesConfigDumpIn: t.typedef = ...
    ScopedRoutesConfigDumpOut: t.typedef = ...
    DynamicClusterIn: t.typedef = ...
    DynamicClusterOut: t.typedef = ...
    AddressIn: t.typedef = ...
    AddressOut: t.typedef = ...
    PathSegmentIn: t.typedef = ...
    PathSegmentOut: t.typedef = ...
    LocalityIn: t.typedef = ...
    LocalityOut: t.typedef = ...
    DoubleMatcherIn: t.typedef = ...
    DoubleMatcherOut: t.typedef = ...
    DynamicScopedRouteConfigsIn: t.typedef = ...
    DynamicScopedRouteConfigsOut: t.typedef = ...
    ClientStatusRequestIn: t.typedef = ...
    ClientStatusRequestOut: t.typedef = ...
    NullMatchIn: t.typedef = ...
    NullMatchOut: t.typedef = ...
    ClustersConfigDumpIn: t.typedef = ...
    ClustersConfigDumpOut: t.typedef = ...
    DoubleRangeIn: t.typedef = ...
    DoubleRangeOut: t.typedef = ...
    StringMatcherIn: t.typedef = ...
    StringMatcherOut: t.typedef = ...
    InlineScopedRouteConfigsIn: t.typedef = ...
    InlineScopedRouteConfigsOut: t.typedef = ...

class FuncList:
    discoveryClient_status: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_trafficdirector() -> Import: ...
