from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    WebfontListIn: t.typedef = ...
    WebfontListOut: t.typedef = ...
    AxisIn: t.typedef = ...
    AxisOut: t.typedef = ...
    WebfontIn: t.typedef = ...
    WebfontOut: t.typedef = ...

class FuncList:
    webfontsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_webfonts() -> Import: ...
