
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T16:13:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c2224e95c48b0584dab8ea06ddd01fef1548d0d",
 "version": "2.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
