
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T12:13:24-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "eaffdf350b6ae082b5f78c662e6b38a3eb776f1b",
 "version": "1.25.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
