
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T14:18:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d8f8eca48fd2b0d6b5e2825d2f8152a7f67ca54",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
