# Generated by Django 3.2 on 2023-02-02 13:21

from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPGInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to=settings_app.upload_utils.upload_logo)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio no Nasaun')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
