# Generated by Django 3.2 on 2023-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_ipginfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipginfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
