# Generated by Django 3.2 on 2023-02-24 00:50

from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_ipginfo_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipginfo',
            name='cop',
            field=models.ImageField(default='default.jpg', null=True, upload_to=settings_app.upload_utils.upload_cop),
        ),
    ]
