# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_processor/text_processor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#text_processor/text_processor.proto\x12\x14text_processor_proto\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07summary\x18\x01 \x01(\t\"0\n\rSearchRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"K\n\x0eSearchResponse\x12\x12\n\nconfidence\x18\x01 \x01(\x02\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"*\n\x06Upload\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06\x62\x61se64\x18\x02 \x01(\t2\xea\x02\n\x17TextProcessorController\x12L\n\tSummarize\x12\x1d.text_processor_proto.Request\x1a\x1e.text_processor_proto.Response\"\x00\x12T\n\x11SentimentAnalysis\x12\x1d.text_processor_proto.Request\x1a\x1e.text_processor_proto.Response\"\x00\x12I\n\x0f\x43ognitiveUpload\x12\x1c.text_processor_proto.Upload\x1a\x16.google.protobuf.Empty\"\x00\x12`\n\x0f\x43ognitiveSearch\x12#.text_processor_proto.SearchRequest\x1a$.text_processor_proto.SearchResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_processor.text_processor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=90
  _REQUEST._serialized_end=113
  _RESPONSE._serialized_start=115
  _RESPONSE._serialized_end=142
  _SEARCHREQUEST._serialized_start=144
  _SEARCHREQUEST._serialized_end=192
  _SEARCHRESPONSE._serialized_start=194
  _SEARCHRESPONSE._serialized_end=269
  _UPLOAD._serialized_start=271
  _UPLOAD._serialized_end=313
  _TEXTPROCESSORCONTROLLER._serialized_start=316
  _TEXTPROCESSORCONTROLLER._serialized_end=678
# @@protoc_insertion_point(module_scope)
