
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-18T10:23:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7557ff03e87e2d3da3f4001d83b12712451f3e08",
 "version": "23.05.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
