
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-02T20:48:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e198af528d9b1c06cb230f521ceae2c80680ad2",
 "version": "1.18.4.post0.dev88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
