# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.5.dev12+g37593b4.d20230602'
__version_tuple__ = version_tuple = (0, 2, 5, 'dev12', 'g37593b4.d20230602')
