
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-19T15:05:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5fa0501b23877468407a5d5611731cabe5c5841",
 "version": "23.05.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
