
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T12:48:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ea09dd66f4b6f953f9cb2787c18a858ae2b03fc",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
