
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-01T02:12:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f79c6b7cf45cb5f8da4e2f841e7ae17eb56d6ccc",
 "version": "v2.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
