
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-02T11:41:09+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "314bac8bd375408c488a5c803081de68ad0a9d11",
 "version": "1.8.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
