
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-31T12:28:53+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a39f45ba0e9daf6ee48a9bf149b7f214ae36226",
 "version": "1.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
