
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-01T16:07:41+0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7067d738653aef4186551c6119cd932aafb2af3f",
 "version": "3.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
