
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T11:42:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3df36b790f682c14f9da71cfd7e09fa5fccbf6d",
 "version": "5.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
