
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-02T20:26:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d35796ff66cf7aa109052b569924ccc6011b071f",
 "version": "4.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
