# Generated by Django 3.2.15 on 2022-11-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220701_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicesubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='devicesubscription',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='senttodevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='senttodevice',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceSubscription',
        ),
        migrations.DeleteModel(
            name='NotificationTopic',
        ),
        migrations.DeleteModel(
            name='SentToDevice',
        ),
    ]
