# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev10+g6856e54.d20230601'
__version_tuple__ = version_tuple = (0, 1, 'dev10', 'g6856e54.d20230601')
