# coding: utf-8

"""
    Deci Platform API

    Train, deploy, optimize and serve your models using Deci's platform, in your cloud or on premise.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deci_lab_client.configuration import Configuration


class Architectures(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_architectures': 'list[UserArchitecture]',
        'autonacs': 'list[AutonacArchitecture]'
    }

    attribute_map = {
        'user_architectures': 'userArchitectures',
        'autonacs': 'autonacs'
    }

    def __init__(self, user_architectures=None, autonacs=None, local_vars_configuration=None):  # noqa: E501
        """Architectures - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._user_architectures = None
        self._autonacs = None
        self.discriminator = None

        self.user_architectures = user_architectures
        self.autonacs = autonacs

    @property
    def user_architectures(self):
        """Gets the user_architectures of this Architectures.  # noqa: E501


        :return: The user_architectures of this Architectures.  # noqa: E501
        :rtype: list[UserArchitecture]
        """
        return self._user_architectures

    @user_architectures.setter
    def user_architectures(self, user_architectures):
        """Sets the user_architectures of this Architectures.


        :param user_architectures: The user_architectures of this Architectures.  # noqa: E501
        :type: list[UserArchitecture]
        """
        if self.local_vars_configuration.client_side_validation and user_architectures is None:  # noqa: E501
            raise ValueError("Invalid value for `user_architectures`, must not be `None`")  # noqa: E501

        self._user_architectures = user_architectures

    @property
    def autonacs(self):
        """Gets the autonacs of this Architectures.  # noqa: E501


        :return: The autonacs of this Architectures.  # noqa: E501
        :rtype: list[AutonacArchitecture]
        """
        return self._autonacs

    @autonacs.setter
    def autonacs(self, autonacs):
        """Sets the autonacs of this Architectures.


        :param autonacs: The autonacs of this Architectures.  # noqa: E501
        :type: list[AutonacArchitecture]
        """
        if self.local_vars_configuration.client_side_validation and autonacs is None:  # noqa: E501
            raise ValueError("Invalid value for `autonacs`, must not be `None`")  # noqa: E501

        self._autonacs = autonacs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Architectures):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Architectures):
            return True

        return self.to_dict() != other.to_dict()
