# coding: utf-8

"""
    Deci Platform API

    Train, deploy, optimize and serve your models using Deci's platform, in your cloud or on premise.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deci_lab_client.configuration import Configuration


class BodyLogin(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'grant_type': 'str',
        'username': 'str',
        'password': 'str',
        'scope': 'str',
        'client_id': 'str',
        'client_secret': 'str'
    }

    attribute_map = {
        'grant_type': 'grant_type',
        'username': 'username',
        'password': 'password',
        'scope': 'scope',
        'client_id': 'client_id',
        'client_secret': 'client_secret'
    }

    def __init__(self, grant_type=None, username=None, password=None, scope='', client_id=None, client_secret=None, local_vars_configuration=None):  # noqa: E501
        """BodyLogin - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._grant_type = None
        self._username = None
        self._password = None
        self._scope = None
        self._client_id = None
        self._client_secret = None
        self.discriminator = None

        if grant_type is not None:
            self.grant_type = grant_type
        self.username = username
        self.password = password
        if scope is not None:
            self.scope = scope
        if client_id is not None:
            self.client_id = client_id
        if client_secret is not None:
            self.client_secret = client_secret

    @property
    def grant_type(self):
        """Gets the grant_type of this BodyLogin.  # noqa: E501


        :return: The grant_type of this BodyLogin.  # noqa: E501
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this BodyLogin.


        :param grant_type: The grant_type of this BodyLogin.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                grant_type is not None and not re.search(r'password', grant_type)):  # noqa: E501
            raise ValueError(r"Invalid value for `grant_type`, must be a follow pattern or equal to `/password/`")  # noqa: E501

        self._grant_type = grant_type

    @property
    def username(self):
        """Gets the username of this BodyLogin.  # noqa: E501


        :return: The username of this BodyLogin.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this BodyLogin.


        :param username: The username of this BodyLogin.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and username is None:  # noqa: E501
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this BodyLogin.  # noqa: E501


        :return: The password of this BodyLogin.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this BodyLogin.


        :param password: The password of this BodyLogin.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and password is None:  # noqa: E501
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def scope(self):
        """Gets the scope of this BodyLogin.  # noqa: E501


        :return: The scope of this BodyLogin.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this BodyLogin.


        :param scope: The scope of this BodyLogin.  # noqa: E501
        :type: str
        """

        self._scope = scope

    @property
    def client_id(self):
        """Gets the client_id of this BodyLogin.  # noqa: E501


        :return: The client_id of this BodyLogin.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this BodyLogin.


        :param client_id: The client_id of this BodyLogin.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this BodyLogin.  # noqa: E501


        :return: The client_secret of this BodyLogin.  # noqa: E501
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this BodyLogin.


        :param client_secret: The client_secret of this BodyLogin.  # noqa: E501
        :type: str
        """

        self._client_secret = client_secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyLogin):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodyLogin):
            return True

        return self.to_dict() != other.to_dict()
