# coding: utf-8

"""
    Deci Platform API

    Train, deploy, optimize and serve your models using Deci's platform, in your cloud or on premise.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deci_lab_client.configuration import Configuration


class BodySignInWithProvider(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'provider_credential': 'str',
        'invite_token': 'str'
    }

    attribute_map = {
        'provider_credential': 'provider_credential',
        'invite_token': 'invite_token'
    }

    def __init__(self, provider_credential=None, invite_token=None, local_vars_configuration=None):  # noqa: E501
        """BodySignInWithProvider - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._provider_credential = None
        self._invite_token = None
        self.discriminator = None

        self.provider_credential = provider_credential
        if invite_token is not None:
            self.invite_token = invite_token

    @property
    def provider_credential(self):
        """Gets the provider_credential of this BodySignInWithProvider.  # noqa: E501


        :return: The provider_credential of this BodySignInWithProvider.  # noqa: E501
        :rtype: str
        """
        return self._provider_credential

    @provider_credential.setter
    def provider_credential(self, provider_credential):
        """Sets the provider_credential of this BodySignInWithProvider.


        :param provider_credential: The provider_credential of this BodySignInWithProvider.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and provider_credential is None:  # noqa: E501
            raise ValueError("Invalid value for `provider_credential`, must not be `None`")  # noqa: E501

        self._provider_credential = provider_credential

    @property
    def invite_token(self):
        """Gets the invite_token of this BodySignInWithProvider.  # noqa: E501


        :return: The invite_token of this BodySignInWithProvider.  # noqa: E501
        :rtype: str
        """
        return self._invite_token

    @invite_token.setter
    def invite_token(self, invite_token):
        """Sets the invite_token of this BodySignInWithProvider.


        :param invite_token: The invite_token of this BodySignInWithProvider.  # noqa: E501
        :type: str
        """

        self._invite_token = invite_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodySignInWithProvider):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodySignInWithProvider):
            return True

        return self.to_dict() != other.to_dict()
