# coding: utf-8

"""
    Deci Platform API

    Train, deploy, optimize and serve your models using Deci's platform, in your cloud or on premise.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from deci_lab_client.configuration import Configuration


class BodyRegisterUserArchitecture(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'architecture_name': 'str'
    }

    attribute_map = {
        'architecture_name': 'architecture_name'
    }

    def __init__(self, architecture_name=None, local_vars_configuration=None):  # noqa: E501
        """BodyRegisterUserArchitecture - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._architecture_name = None
        self.discriminator = None

        self.architecture_name = architecture_name

    @property
    def architecture_name(self):
        """Gets the architecture_name of this BodyRegisterUserArchitecture.  # noqa: E501


        :return: The architecture_name of this BodyRegisterUserArchitecture.  # noqa: E501
        :rtype: str
        """
        return self._architecture_name

    @architecture_name.setter
    def architecture_name(self, architecture_name):
        """Sets the architecture_name of this BodyRegisterUserArchitecture.


        :param architecture_name: The architecture_name of this BodyRegisterUserArchitecture.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and architecture_name is None:  # noqa: E501
            raise ValueError("Invalid value for `architecture_name`, must not be `None`")  # noqa: E501

        self._architecture_name = architecture_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyRegisterUserArchitecture):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodyRegisterUserArchitecture):
            return True

        return self.to_dict() != other.to_dict()
