
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-30T16:53:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "58bea879e505d9fbeb9b1b8bd4ff0174beb6526d",
 "version": "2.14.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
