
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T19:09:03+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "16296fb2ed047302b32f43f2a13d242f80542d8c",
 "version": "2.9.5.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
