
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-29T23:04:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "763f8c29e8996d06bb69a43b426177cc85892bbb",
 "version": "0.0.174"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
